// Deep content library for Sanatana platform
// Justifications, sacred practices, cosmic timeline, meditations, books, body-spirit map

export const WHY_CARDS = [
  {
    id: 'meditation',
    icon: 'Brain',
    color: 'from-cyan-400 to-blue-600',
    title: 'Why meditate?',
    tagline: 'The most well-studied practice in wellness science.',
    scientific:
      "Neuroscience shows meditation physically remodels the brain. Long-term practitioners show thicker gray matter in the prefrontal cortex (attention, decision-making) and hippocampus (memory), and a smaller, less reactive amygdala (fear response) — studies by Sara Lazar at Harvard and others. Mindfulness-Based Stress Reduction (MBSR) programs consistently reduce cortisol, blood pressure, and markers of inflammation. Elizabeth Blackburn's Nobel-winning work on telomeres found long-term meditators have longer telomeres — a biological marker of cellular aging. Regular practice improves working memory, emotional regulation, immune function, and sleep quality.",
    spiritual:
      "In every tradition, meditation is the doorway. Patanjali's Yoga Sutras describe dhyana as the seventh limb, leading to samadhi. The Buddha's entire path — the Noble Eightfold Path — culminates in right concentration and right mindfulness. Christian mystics practice hesychasm and contemplative prayer. Sufis whirl in dhikr, remembering the divine name. Meditation is not an escape from life; it is training in being fully present to it, until the meditator dissolves into what is being watched.",
    benefits: [
      'Measurable stress and anxiety reduction',
      'Improved focus, memory, emotional regulation',
      'Lower blood pressure and inflammation',
      'Increased self-awareness and empathy',
      'Deeper sleep and slower biological aging',
      'A stable inner witness that suffering cannot touch',
    ],
  },
  {
    id: 'wisdom',
    icon: 'BookOpen',
    color: 'from-amber-300 to-orange-500',
    title: 'Why learn ancient wisdom?',
    tagline: 'Every civilization has faced the same questions we face today.',
    scientific:
      "Modern psychology keeps rediscovering what contemplatives have known for millennia. Positive psychology validated gratitude, forgiveness, and purpose as central to well-being — all pillars of ancient practice. Cognitive Behavioral Therapy shares deep roots with Stoic philosophy and Buddhist psychology. Cross-cultural anthropology reveals that ritual, story, and community are not optional — they are how the human nervous system regulates itself across generations. When we study wisdom traditions, we are studying a 3,000-year experiment on how to be human.",
    spiritual:
      "Sanatana Dharma — the 'eternal way' — is not a religion but a recognition. The same insights arise independently in the Upanishads, the Dhammapada, the Tao Te Ching, the Sermon on the Mount, and Rumi's poetry. When we compare these voices honestly, we don't lose faith — we deepen it. We stop mistaking the finger pointing at the moon for the moon itself. Wisdom is what remains after all the disagreements are removed.",
    benefits: [
      'Perspective on modern anxiety through timeless lenses',
      'Shared vocabulary for meaning across cultures',
      'Ethical frameworks tested by centuries',
      'Freedom from thinking your suffering is unique',
      'Roots in a lineage larger than the self',
    ],
  },
  {
    id: 'interconnection',
    icon: 'Network',
    color: 'from-fuchsia-400 to-purple-600',
    title: 'Why "everything is connected"?',
    tagline: 'From quantum fields to ecosystems to consciousness.',
    scientific:
      "Quantum entanglement shows that particles once in contact remain correlated across arbitrary distance. Ecology reveals that no organism is separable from its environment — remove one species and forests can collapse. Systems neuroscience shows the brain is not a set of modules but a densely interconnected web where damage anywhere reshapes everywhere. Epigenetics shows your grandmother's trauma or nourishment can shape your gene expression. The universe is not made of things — it is made of relationships.",
    spiritual:
      "The Buddha called this pratityasamutpada — dependent origination: 'When this is, that is; when this is not, that is not.' The Upanishads say 'Tat tvam asi' — you are that. The Tao Te Ching describes the ten thousand things arising from one. Indra's Net, in Hua-Yen Buddhism, imagines the universe as an infinite web of jewels, each reflecting all others. Compassion is not a moral duty — it is the natural response to seeing that there is no separate self to protect.",
    benefits: [
      'Foundation for genuine compassion',
      'Ecological and ethical clarity',
      'Freedom from the loneliness of the isolated self',
      'Framework for seeing patterns across disciplines',
      'A living answer to "why does anything I do matter?"',
    ],
  },
  {
    id: 'sanatana',
    icon: 'Infinity',
    color: 'from-emerald-300 to-teal-600',
    title: 'Why "Sanatana Dharma"?',
    tagline: 'Not a religion — a name for what is eternally true.',
    scientific:
      "Sanatana means 'eternal, without beginning or end.' Dharma means 'that which upholds.' Together: the principles that hold reality together — gravity, entropy, evolution, cause and effect, the drive of consciousness to know itself. These are not beliefs. They are observed. Science and Sanatana are not rivals — science is Sanatana's method of external inquiry, while contemplation is its method of inner inquiry. Both are asking: what is real?",
    spiritual:
      "Sanatana Dharma predates the label 'Hinduism' by millennia and includes streams that became Buddhism, Jainism, and Sikhism. Its texts (the Vedas, Upanishads, Gita, Yoga Sutras) do not demand belief — they invite direct experience. It has no single founder, no exclusive book, no requirement to reject others. Its four aims of life — dharma (purpose), artha (prosperity), kama (love), moksha (liberation) — honor the whole human, not a fragment. This is why it can hold a scientist, a mystic, a householder, and a monk in the same embrace.",
    benefits: [
      'A framework that does not conflict with science',
      'Space for both devotion and skeptical inquiry',
      'No requirement to reject other traditions',
      'Honors both worldly and transcendent life',
      'A living, updatable body of practice',
    ],
  },
];

export const MALA = {
  name: 'Japa Mala',
  subtitle: 'The 108-bead prayer garland',
  intro:
    "A mala is not superstition — it is one of the world's oldest cognitive training devices. Tibetan Buddhists, Hindu yogis, Sikhs, Sufi Muslims (misbaha, 99 beads), Catholic Christians (rosary), and Orthodox Christians (komboskini) all use bead loops. The reason is the same across cultures: repeated invocation with a tactile counter quiets the mind's default-mode network and produces measurable calm.",
  why108: [
    'Sun\u2019s diameter fits ~108 times into the distance between Earth and Sun; Moon\u2019s ~108 times into Earth\u2013Moon distance (approximation).',
    '108 marma (energy) points in the traditional yogic body.',
    '9 planets \u00d7 12 zodiac houses = 108.',
    '1 = God/higher, 0 = emptiness, 8 = infinity \u2014 the whole spiritual journey encoded.',
    'Practical: 108 repetitions is long enough to settle the nervous system, short enough to sustain focus.',
  ],
  types: [
    { name: 'Rudraksha', tradition: 'Shiva devotees; grounding, protection.' },
    { name: 'Tulsi', tradition: 'Vishnu/Krishna devotees; purity, devotion.' },
    { name: 'Sandalwood', tradition: 'Universal; cooling, calming.' },
    { name: 'Sphatik (Crystal)', tradition: 'Clarity, healing.' },
    { name: 'Lotus Seed', tradition: 'Devi; awakening, transcendence.' },
    { name: 'Bodhi Seed', tradition: 'Buddhist; enlightenment.' },
  ],
  process: [
    'Sit facing east or north, spine upright. Take three deep breaths.',
    'Set a clear intention (sankalpa): the mantra you will repeat and why.',
    'Hold the mala in your right hand, draped over the middle finger.',
    'Use your thumb to gently pull each bead toward you, one per repetition. Never use the index finger \u2014 it represents ego.',
    'When you reach the guru bead (larger, tasseled), do NOT cross it. Reverse direction and continue for another round.',
    'Repeat the chosen mantra with each bead. Common ones: Om, Om Namah Shivaya, Om Mani Padme Hum, Gayatri, Rama Rama, or Ya Rahman.',
    'When finished, sit in silence for at least a minute. Touch the mala to your heart before setting it down.',
  ],
  benefits: [
    'Focused-attention practice measurably reduces mind-wandering.',
    'Tactile counting anchors distracted attention gently, without force.',
    'Mantra repetition activates rhythmic breath, calming the vagus nerve.',
    'The physical mala becomes a conditioned cue: touching it triggers the calm state after weeks of practice.',
    'Consistent 108-count builds a daily container for reflection.',
  ],
};

export const DEEKSHA = {
  name: 'Deeksha',
  subtitle: 'The transmission from teacher to student',
  intro:
    "Deeksha means 'initiation' \u2014 the moment when a lineage of practice is formally handed to a seeker by a qualified teacher (guru). It is one of the oldest known models of accelerated learning: instead of reinventing the wheel, the student receives a compressed transmission of what generations of practitioners have already verified.",
  why: [
    'Practices done without proper initiation can be ineffective or destabilizing (especially kundalini and advanced pranayama).',
    'A teacher can perceive your specific temperament and prescribe the right practice \u2014 like personalized medicine.',
    'The teacher\u2013student relationship itself is a practice ground for humility and trust.',
    'Deeksha creates an unbroken chain (parampara) linking you to the original insight.',
    'The energy/attention of a realized teacher is said to catalyze what solitary practice cannot.',
  ],
  types: [
    { name: 'Mantra Deeksha', desc: 'A specific mantra is whispered to the student, to be their lifelong companion.' },
    { name: 'Shaktipat Deeksha', desc: 'Transmission of energetic awakening by touch, gaze, thought, or word (Kashmir Shaivism, Siddha Yoga).' },
    { name: 'Kriya Deeksha', desc: 'Initiation into specific breath and meditation techniques (Kriya Yoga lineage).' },
    { name: 'Vidya Deeksha', desc: 'Initiation into a specific tradition of knowledge (Sri Vidya, Vedanta, etc.).' },
    { name: 'Sannyasa Deeksha', desc: 'Formal renunciation \u2014 the monk\u2019s vows.' },
    { name: 'Diksha in Buddhism (Abhisheka)', desc: 'Empowerment into a tantric practice by an authorized lama.' },
  ],
  process: [
    'Seek a teacher through study of their lineage, teachings, and the fruits in their students. Do not rush.',
    'Approach with humility. Traditionally the student brings a small offering (dakshina) \u2014 fruit, flowers, cloth, whatever is genuinely given.',
    'The teacher may test the seeker with questions, or a period of preparatory practice.',
    'The transmission itself is often brief \u2014 a mantra spoken into the ear, a gesture, a look. The simplicity is deceptive.',
    'After deeksha, daily practice is committed to. This is the real initiation \u2014 not the ceremony, but the years that follow.',
    'The relationship continues: reporting back, refining practice, deepening trust.',
  ],
  benefits: [
    'A verified, tradition-tested practice rather than guesswork.',
    'Direct feedback from a teacher who has walked the path.',
    'Community of fellow initiates (sangha) that reinforces practice.',
    'Faster progress by avoiding common pitfalls.',
    'A living relationship with the tradition, not just books.',
  ],
  caution:
    'Deeksha is powerful and can be misused. A genuine teacher never coerces, exploits, or demands secrecy that harms. The final authority is always your discernment.',
};

export const PUJA_VIDHANAM = {
  name: 'Daily Puja Vidhanam',
  subtitle: 'The traditional 16-step home worship (Shodashopachara)',
  intro:
    "Puja is not superstition or transaction. It is a choreography that engages every sense \u2014 sight, sound, smell, touch, taste \u2014 in a single act of remembrance. Modern neuroscience recognizes this as multi-sensory embodied cognition: a ritual done daily reshapes the nervous system faster than intellectual reflection alone. The 16 steps (upacharas) are a technology for hosting the sacred inside a household.",
  preparation: [
    'Bathe and wear clean, preferably natural fabric clothing.',
    'Clean the puja space. Face east or north.',
    'Gather: a small lamp (deepa), incense, flowers, water in a small vessel (kalasha), a bell, fruits or a simple sweet, tulsi or bilva leaves if appropriate, sandalwood paste or kumkum.',
    'Sit in a comfortable, spine-erect posture.',
    'Perform three deep breaths, then Achamana (sip water three times with mantras) and Pranayama (breath control) to prepare.',
    'Sankalpa: state clearly the day, place, and intention of the puja.',
    'Ganapati Smarana: begin with a brief invocation of Ganesha, remover of obstacles.',
  ],
  steps: [
    { n: 1, sanskrit: 'Avahana', english: 'Invocation', desc: 'Invite the divine presence to be present in the murti (form) before you. A gesture of the hands, a mantra.' },
    { n: 2, sanskrit: 'Asana', english: 'Seat', desc: 'Offer a seat \u2014 a flower or grain of rice placed at the base of the murti.' },
    { n: 3, sanskrit: 'Padya', english: 'Washing the feet', desc: 'Symbolically wash the feet of the deity with water.' },
    { n: 4, sanskrit: 'Arghya', english: 'Welcome water', desc: 'Offer water for the hands \u2014 traditional welcome for an honored guest.' },
    { n: 5, sanskrit: 'Achamana', english: 'Sipping water', desc: 'Offer water for the mouth, purifying.' },
    { n: 6, sanskrit: 'Snana', english: 'Bath', desc: 'Bathe the murti \u2014 with water, or with panchamrita (milk, curd, ghee, honey, sugar), then water again.' },
    { n: 7, sanskrit: 'Vastra', english: 'Clothing', desc: 'Offer new cloth or thread symbolizing garments.' },
    { n: 8, sanskrit: 'Yajnopavita', english: 'Sacred thread', desc: 'Offer the sacred thread if applicable to the deity.' },
    { n: 9, sanskrit: 'Gandha', english: 'Fragrance', desc: 'Apply sandalwood paste, kumkum, or perfumed oil to the murti.' },
    { n: 10, sanskrit: 'Pushpa', english: 'Flowers', desc: 'Offer fresh flowers \u2014 traditionally those loved by the specific deity.' },
    { n: 11, sanskrit: 'Dhupa', english: 'Incense', desc: 'Light incense and circle it around the murti. The smoke rising = prayer rising.' },
    { n: 12, sanskrit: 'Deepa', english: 'Lamp', desc: 'Light the ghee or oil lamp. Wave it in circles (aarti). Light dispelling darkness = wisdom dispelling ignorance.' },
    { n: 13, sanskrit: 'Naivedya', english: 'Food offering', desc: 'Offer prepared food \u2014 fruits, sweets, cooked food. It becomes prasada after offering.' },
    { n: 14, sanskrit: 'Tambula', english: 'Betel', desc: 'Offer betel leaves and nuts \u2014 traditional post-meal digestive and honor gift.' },
    { n: 15, sanskrit: 'Namaskara', english: 'Salutation', desc: 'Prostrate or bow with folded hands. Offer mantras of praise, chant the deity\u2019s names.' },
    { n: 16, sanskrit: 'Visarjana', english: 'Farewell', desc: 'Respectfully ask the divine presence to return to its abode, or remain in the murti until tomorrow. Take the flowers and prasada as blessed.' },
  ],
  after: [
    'Distribute prasada to family or eat it in silence.',
    'Extinguish the lamp gently with your fingers or a wave of the hand \u2014 never by blowing.',
    'Sit for one to five minutes of silent gratitude before rising.',
    'A short daily puja (10\u201315 min) done consistently is far more powerful than an elaborate one done rarely.',
  ],
  benefits: [
    'Trains ritualized attention \u2014 a form of embodied meditation.',
    'Marks the day with a sacred pause, resetting the nervous system.',
    'Builds relationship with the chosen form of the divine (ishta devata).',
    'Cultivates gratitude, humility, and beauty in ordinary life.',
    'Anchors family and lineage in a shared daily rhythm.',
    'Neuroscience: multi-sensory ritual strengthens memory consolidation and emotional regulation.',
  ],
};

export const COSMIC_TIMELINE = [
  { era: 'Big Bang', when: '13.8 billion years ago', color: 'from-pink-500 to-fuchsia-600',
    science: 'Space, time, and energy erupt from a singularity. In the first 10\u207B\u00b3\u00b2 seconds, cosmic inflation stretches quantum fluctuations into the seeds of galaxies. Temperature: ~10\u00b3\u00b2 K.',
    wisdom: 'The Nasadiya Sukta (Rig Veda 10.129) describes a state before existence and non-existence, from which "that One" arose by the heat of its own aspiration \u2014 a striking parallel to inflation.' },
  { era: 'First Stars', when: '~200 million years after Big Bang', color: 'from-amber-300 to-orange-500',
    science: 'Hydrogen collapses under gravity, igniting the first stars. They forge helium, then carbon, oxygen, iron \u2014 the elements of life.',
    wisdom: '"Aham Brahmasmi" \u2014 the atoms in your bones were born in a star that exploded before Earth existed. You are quite literally stardust remembering itself.' },
  { era: 'Milky Way Forms', when: '~13.6 billion years ago', color: 'from-purple-500 to-indigo-600',
    science: 'Our galaxy assembles from smaller proto-galaxies. Its spiral arms are density waves, not solid structures.',
    wisdom: 'Many ancient cultures charted the Milky Way as a river, a road of souls, or a divine spine (the celestial Sushumna).' },
  { era: 'Sun & Solar System', when: '~4.6 billion years ago', color: 'from-yellow-400 to-orange-500',
    science: 'A collapsing molecular cloud forms the Sun. Dust disks around it clump into planets. Earth stabilizes after a Mars-sized body strikes it, ejecting material that becomes the Moon.',
    wisdom: 'Surya (Sun) is central to Sanatana cosmology and Vedic ritual. The Gayatri mantra addresses the light of that sun.' },
  { era: 'Life Begins', when: '~3.7 billion years ago', color: 'from-emerald-400 to-teal-600',
    science: 'Simple self-replicating molecules give rise to prokaryotic life in oceans. Photosynthesis appears ~2.4 billion years ago, oxygenating the atmosphere.',
    wisdom: 'The Puranas describe the ten avatars of Vishnu beginning with Matsya (fish) \u2014 an evolutionary sequence from water to amphibian to human, prefiguring Darwin.' },
  { era: 'Cambrian Explosion', when: '~540 million years ago', color: 'from-cyan-400 to-blue-600',
    science: 'Complex multicellular life diversifies rapidly. Eyes evolve. Vertebrates appear.',
    wisdom: 'A useful reminder: consciousness has been experimenting for over half a billion years in bodies utterly unlike ours.' },
  { era: 'Homo Sapiens', when: '~300,000 years ago', color: 'from-red-400 to-pink-500',
    science: 'Anatomically modern humans emerge in Africa. Behavioral modernity (art, ritual, symbolic thought) crystallizes ~70,000 years ago.',
    wisdom: 'The moment the universe became aware it was a universe.' },
  { era: 'First Civilizations', when: '~5,000 years ago', color: 'from-amber-500 to-yellow-600',
    science: 'Sumer, Egypt, Indus Valley, China. Writing, agriculture, cities, law.',
    wisdom: 'The Vedas begin to be composed (oral tradition older still). The core spiritual questions receive their first written formulation.' },
  { era: 'Axial Age', when: '~2,500 years ago', color: 'from-violet-400 to-purple-600',
    science: 'Karl Jaspers\u2019 term for the period 800\u2013200 BCE when spiritual/philosophical revolution occurred independently across the world.',
    wisdom: 'Buddha, Mahavira, Confucius, Lao Tzu, the Upanishadic sages, and the Greek philosophers all live within a few centuries \u2014 as if humanity crossed a threshold together.' },
  { era: 'World Religions', when: '~2,000 years ago \u2013 present', color: 'from-fuchsia-400 to-pink-600',
    science: 'Christianity, Islam, and later Sikhism arise. Global trade routes disseminate ideas.',
    wisdom: 'Each tradition points at the same moon from a different mountain. Comparing them enriches faith rather than dilutes it.' },
  { era: 'Scientific Revolution', when: '~500 years ago', color: 'from-blue-400 to-cyan-500',
    science: 'Copernicus, Newton, Darwin, Einstein. Method-driven knowledge accelerates exponentially.',
    wisdom: 'Not the opposite of spirituality \u2014 the same drive to know the real, aimed outward.' },
  { era: 'Now', when: 'This moment', color: 'from-white to-slate-300',
    science: 'You are a 13.8-billion-year-old process reading these words on a lit screen powered by fusion fossils.',
    wisdom: 'The only place awakening ever happens.' },
  { era: 'Future?', when: 'Unwritten', color: 'from-slate-300 to-purple-400',
    science: 'AGI, interplanetary life, neural interfaces, longevity science, climate reckoning.',
    wisdom: 'The tradition\u2019s answer: the tools change, the questions do not. Wisdom is what lets us wield the tools well.' },
];

export const MEDITATIONS = [
  { id: 'breath', name: 'Anapana \u00b7 Breath', duration: 10, level: 'Beginner', color: 'from-cyan-400 to-blue-500',
    desc: 'Simply watch the breath at the nostrils. The foundation of every tradition.',
    steps: ['Sit spine-upright, eyes soft or closed', 'Feel the breath at the nostrils, not the belly', 'When the mind wanders, gently return to the breath', 'Do not control the breath, just observe', 'End with three intentional deep breaths'] },
  { id: 'body', name: 'Vipassana \u00b7 Body Scan', duration: 20, level: 'Beginner', color: 'from-emerald-400 to-teal-500',
    desc: 'Sweep attention through the body, meeting each sensation with equanimity.',
    steps: ['Start at the top of the head', 'Slowly move attention downward, region by region', 'Note pleasant, unpleasant, neutral \u2014 without reacting', 'Feel the body as a field of vibration', 'Rest in whole-body awareness at the end'] },
  { id: 'mantra', name: 'Mantra Japa', duration: 15, level: 'Beginner', color: 'from-fuchsia-400 to-purple-500',
    desc: 'Rhythmic repetition of a sacred sound. Best with a 108-bead mala.',
    steps: ['Choose a mantra you feel drawn to (Om, So Hum, Om Namah Shivaya, or received)', 'Repeat in sync with the breath', 'Optionally count with a mala', 'When the mantra becomes automatic, listen to it instead of repeating', 'Let the silence between repetitions grow'] },
  { id: 'loving', name: 'Metta \u00b7 Loving-kindness', duration: 15, level: 'Intermediate', color: 'from-pink-400 to-rose-500',
    desc: 'Radiate goodwill outward in expanding circles.',
    steps: ['Wish yourself well: "May I be safe, happy, healthy, at ease"', 'Extend to a loved one', 'Extend to a neutral person', 'Extend to someone difficult', 'Extend to all beings everywhere'] },
  { id: 'chakra', name: 'Chakra Awakening', duration: 25, level: 'Intermediate', color: 'from-purple-500 to-indigo-600',
    desc: 'Move attention through the seven traditional energy centers.',
    steps: ['Ground at the base (muladhara, root, red)', 'Move to sacral (svadhisthana, orange)', 'Solar plexus (manipura, yellow)', 'Heart (anahata, green)', 'Throat (vishuddha, blue)', 'Third eye (ajna, indigo)', 'Crown (sahasrara, violet/white)', 'Rest in the space that contains them all'] },
  { id: 'silent', name: 'Silent Sitting', duration: 30, level: 'Advanced', color: 'from-slate-400 to-slate-600',
    desc: 'No object. Just presence. Ramana Maharshi\u2019s "Who am I?".',
    steps: ['Sit with no technique', 'When a thought arises, ask "To whom does this arise?"', 'Rest as the awareness that notices', 'Do not push, do not pull', 'Be nothing in particular'] },
  { id: 'sleep', name: 'Yoga Nidra \u00b7 Sleep', duration: 20, level: 'All levels', color: 'from-indigo-400 to-purple-500',
    desc: 'Conscious deep-rest \u2014 an hour of sleep in twenty minutes.',
    steps: ['Lie flat, palms up', 'Set a sankalpa (single-sentence intention)', 'Rotate attention through 61 body points', 'Follow the breath as it becomes very subtle', 'Return with intention intact'] },
  { id: 'walking', name: 'Walking Meditation', duration: 15, level: 'All levels', color: 'from-amber-400 to-orange-500',
    desc: 'Meditation moves out of the cushion and into life.',
    steps: ['Walk at half your normal speed', 'Feel each phase: lifting, moving, placing', 'Coordinate with the breath', 'Let the eyes be soft and forward', 'The path is the practice'] },
];

export const SACRED_BOOKS = [
  { id: 'gita', title: 'Bhagavad Gita', tradition: 'Hinduism', when: '~500\u2013200 BCE',
    about: 'A dialogue between Arjuna and Krishna on the eve of battle. The most concise summary of yoga, karma, jnana, and bhakti in the Sanskrit canon.', pages: '700 verses, 18 chapters',
    themes: ['Duty vs desire', 'Yoga of action, wisdom, devotion', 'The immortal Self', 'Nature\u2019s three qualities'] },
  { id: 'upanishads', title: 'Principal Upanishads', tradition: 'Hinduism', when: '~800\u2013300 BCE',
    about: 'The philosophical crown of the Vedas. The great equations: Atman = Brahman, Tat Tvam Asi, Neti Neti.', pages: '~10 primary texts',
    themes: ['The nature of Self', 'Brahman \u2014 the absolute', 'Meditation and inquiry', 'Death and immortality'] },
  { id: 'dhammapada', title: 'Dhammapada', tradition: 'Buddhism', when: '~250 BCE (compiled)',
    about: 'The essential sayings of the Buddha in 423 verses. Read one a day for a year.', pages: '26 chapters',
    themes: ['The mind is everything', 'Impermanence', 'The Middle Way', 'Freedom from craving'] },
  { id: 'tao', title: 'Tao Te Ching', tradition: 'Taoism', when: '~6th\u20134th century BCE',
    about: 'Lao Tzu\u2019s 81 short chapters on the Tao (the Way) and Te (its expression). Perhaps the most translated book after the Bible.', pages: '81 verses',
    themes: ['Wu wei (non-forcing action)', 'The value of emptiness', 'Simplicity as power', 'Water as teacher'] },
  { id: 'quran', title: 'Quran', tradition: 'Islam', when: '610\u2013632 CE',
    about: 'The primary scripture of Islam, revealed to Muhammad over 23 years. 114 suras (chapters).', pages: '~600 pages',
    themes: ['Tawhid (unity of God)', 'Compassion & mercy', 'Justice', 'Direct relationship with the Divine'] },
  { id: 'bible', title: 'Bible', tradition: 'Christianity', when: '~1200 BCE\u2013100 CE',
    about: 'A library of 66 (Protestant) or more books: history, poetry, prophecy, gospel, letters, apocalypse.', pages: 'Old & New Testament',
    themes: ['Covenant', 'Redemption', 'The kingdom within', 'Love as ultimate ethic'] },
  { id: 'guru', title: 'Guru Granth Sahib', tradition: 'Sikhism', when: '1604 CE (compiled)',
    about: 'The eternal Guru of the Sikhs. Poetry by Guru Nanak and others, plus Hindu and Muslim saints.', pages: '1430 pages',
    themes: ['Ik Onkar (One God)', 'Naam Simran (remembrance)', 'Seva (service)', 'Equality of all'] },
  { id: 'yogasutras', title: 'Yoga Sutras of Patanjali', tradition: 'Yoga', when: '~200 BCE\u2013200 CE',
    about: 'The definitive manual of classical yoga in 196 concise aphorisms.', pages: '4 chapters',
    themes: ['Eight limbs of yoga', 'Stilling the mind', 'Samadhi', 'The nature of consciousness'] },
];

export const BODY_MAP = [
  { part: 'Crown / Brain', color: 'from-violet-400 to-purple-600',
    science: 'Long-term meditation increases gray matter in the prefrontal cortex and hippocampus; reduces amygdala reactivity. The default-mode network (self-referential thinking) quiets during deep meditation.',
    spirit: 'Sahasrara chakra. The seat of pure consciousness in yogic anatomy. Kundalini rises here for union with Shiva.' },
  { part: 'Third Eye / Pineal', color: 'from-indigo-400 to-blue-600',
    science: 'The pineal gland regulates melatonin and circadian rhythm; some research suggests it may produce trace DMT during REM sleep and death.',
    spirit: 'Ajna chakra. Seat of intuition and inner vision. Called the "eye of Shiva."' },
  { part: 'Throat', color: 'from-sky-400 to-blue-500',
    science: 'Vagal tone (measurable via HRV) is trained by chanting, humming, and slow exhale. Higher vagal tone = better emotional regulation.',
    spirit: 'Vishuddha chakra. The gateway of speech and truth. Mantra practice directly stimulates it.' },
  { part: 'Heart', color: 'from-emerald-400 to-teal-500',
    science: 'The heart has ~40,000 neurons of its own (the "little brain in the heart"). Loving-kindness meditation demonstrably slows heart rate and increases empathy.',
    spirit: 'Anahata chakra. Bhakti (devotion) awakens here. The "cave of the heart" in Upanishads is the seat of the Self.' },
  { part: 'Solar Plexus', color: 'from-yellow-400 to-amber-500',
    science: 'The enteric nervous system in the gut contains ~500 million neurons. 90% of serotonin is produced here. Gut\u2013brain axis shapes mood and cognition.',
    spirit: 'Manipura chakra. Seat of willpower and vital fire (agni). Stoked by kapalabhati and agni-sara.' },
  { part: 'Breath / Lungs', color: 'from-cyan-400 to-blue-400',
    science: 'Slow breathing (4\u20136 breaths/minute) activates the parasympathetic nervous system, lowers cortisol, increases HRV, and stimulates the vagus nerve.',
    spirit: 'Prana \u2014 the vital current. Pranayama is literally the "extension of life force." The breath is the bridge between voluntary and involuntary systems.' },
  { part: 'Sacral', color: 'from-orange-400 to-red-500',
    science: 'Reproductive hormones influence mood, motivation, creativity. Trauma is often stored in the pelvic region (Bessel van der Kolk).',
    spirit: 'Svadhisthana chakra. Creativity, sensuality, emotional flow.' },
  { part: 'Root / Base', color: 'from-red-500 to-pink-600',
    science: 'The base of the spine houses key sympathetic ganglia. Grounding practices (feet on earth, walking barefoot) measurably reduce inflammation markers.',
    spirit: 'Muladhara chakra. Where kundalini is said to lie coiled. Safety, stability, survival.' },
];

export const CHAKRA_QUIZ = [
  { chakra: 'Muladhara \u00b7 Root', q: 'I feel physically safe and grounded in my daily life.' },
  { chakra: 'Svadhisthana \u00b7 Sacral', q: 'I enjoy creativity, pleasure, and healthy emotional flow.' },
  { chakra: 'Manipura \u00b7 Solar', q: 'I have willpower and can act on my intentions.' },
  { chakra: 'Anahata \u00b7 Heart', q: 'I can give and receive love without fear or condition.' },
  { chakra: 'Vishuddha \u00b7 Throat', q: 'I speak my truth clearly and listen with presence.' },
  { chakra: 'Ajna \u00b7 Third Eye', q: 'I trust my intuition and see beyond surface appearances.' },
  { chakra: 'Sahasrara \u00b7 Crown', q: 'I feel connected to something larger than myself.' },
];
