// Additional content: Life Questions, World Sacred Sites, Sacred Music

export const LIFE_QUESTIONS = [
  {
    id: 'suffering',
    q: 'Why do I suffer?',
    scientific: "Neuroscience shows suffering has two layers: the primary sensation (pain, loss, threat) and the secondary story your mind builds about it (rumination, catastrophizing, self-blame). Studies at UCLA show that naming an emotion ('this is sadness') reduces activity in the amygdala within seconds. Chronic suffering is often a nervous system stuck in a fight-flight-freeze loop, treatable with breathwork, therapy, exercise, and sleep. Evolutionarily, suffering evolved as a signal — physical pain warns of danger, social pain motivates connection.",
    spiritual: "The Buddha's First Noble Truth: life includes dukkha (suffering, or unsatisfactoriness). His Second Truth: it arises from tanha (craving and clinging). His Third: it can end. His Fourth: the Eightfold Path is the way. The Bhagavad Gita teaches that suffering comes from mistaking the body-mind for the self. Christian and Sufi mystics say suffering is the friction that polishes the soul — 'the wound is where the Light enters' (Rumi).",
    philosophical: "Stoics (Epictetus, Marcus Aurelius) distinguish between events (outside your control) and your judgment of them (inside your control). Suffering, they argue, lives in the judgment. Existentialists (Frankl, Camus) insist suffering becomes bearable only when it carries meaning. Advaita Vedanta says suffering ends when you see the sufferer was never who you truly were.",
    historical: "Every civilization has grappled with this. Ancient Mesopotamians blamed capricious gods; medieval Europeans framed suffering as divine test; the Enlightenment reframed it as a problem to be solved. Today's mental health revolution combines all three: biology, meaning, and community. The oldest human question remains the newest.",
    synthesis: "Pain is unavoidable. Suffering — the story we spin around pain — is largely trainable. Every tradition agrees the exit is through it, not around it: attention, meaning, and connection.",
  },
  {
    id: 'consciousness',
    q: 'What is consciousness?',
    scientific: "The 'hard problem' (David Chalmers, 1995): why is there something it's like to be you? Neuroscience maps neural correlates of consciousness (NCC), showing certain brain states accompany certain experiences, but cannot explain why experience exists at all. Global Workspace Theory (Baars, Dehaene) proposes consciousness as a broadcast across the brain; Integrated Information Theory (Tononi) proposes it's a property of any system with enough integrated complexity. No theory has closed the explanatory gap.",
    spiritual: "Vedanta reverses the question: matter arises within consciousness, not the other way around. 'Brahman is consciousness' (Prajnanam Brahma). The Yoga Sutras describe the mind as a modification of consciousness, and enlightenment as the mind falling silent while awareness remains. Buddhism speaks of rigpa — pristine awareness that is aware of itself. Sufism calls it the mirror in which the Beloved sees itself.",
    philosophical: "Descartes: 'I think, therefore I am' — consciousness is the one undeniable fact. Panpsychists (Whitehead, Chalmers, Strawson) argue consciousness is fundamental like mass or charge. Illusionists (Dennett, Frankish) argue our sense of consciousness is a useful representation, not an inner theater. Phenomenologists (Husserl, Merleau-Ponty) study consciousness by describing it from the inside.",
    historical: "Ancient Egyptians located consciousness in the heart; Greeks in the brain (Hippocrates) or diaphragm (Aristotle). Every meditative tradition has taken consciousness as its laboratory. Modern neuroscience finally joined the investigation only in the last century — a very young science studying its own instrument.",
    synthesis: "Whatever consciousness is, it is what is reading these words right now. It is closer than your next thought, and no theory has yet caught it. Perhaps that is a clue.",
  },
  {
    id: 'god',
    q: 'Does God exist?',
    scientific: "Science cannot test claims about a being outside spacetime — that is a category error. What science can say: no experimental evidence requires a designer; the universe's fine-tuning is intriguing but does not compel a personal creator; feelings of God-presence correlate with temporal lobe activity and certain meditative states. Science is agnostic by method, not by verdict.",
    spiritual: "Traditions disagree on details but converge on structure: there is a ground of being from which everything arises. Hinduism calls it Brahman (impersonal) or Ishvara (personal). Judaism, Christianity, and Islam name a personal creator. Buddhism sidesteps: liberation does not require the question. Sufism collapses it: 'wherever you turn, there is the face of God' (Quran 2:115). Direct experience is the only test that finally settles it — and it is settleable only for the one experiencing.",
    philosophical: "Aquinas offered five arguments (motion, causation, contingency, degree, design). Kant argued God cannot be proven by reason but must be posited by practical morality. Nietzsche declared God dead as a cultural fact. Modern analytic philosophy (Plantinga, Swinburne) revived rigorous theism; naturalists (Rowe, Mackie) argue the problem of evil is decisive. Advaita cuts through: the God you are searching for is doing the searching.",
    historical: "Every human culture has had a concept of the sacred. Whether this reflects a universal cognitive template or a universal encounter is contested. What is certain: the God-question has driven our best art, ethics, science, and cruelty. It refuses to be settled.",
    synthesis: "Ask a smaller question first: does something exist that is deeper than my ego and larger than my life? Traditions call it God; philosophers call it Being; scientists call it the universe. The name may matter less than the recognition.",
  },
  {
    id: 'death',
    q: 'What happens after death?',
    scientific: "Neuroscience: consciousness appears tightly coupled with brain function. When the brain dies, measurable consciousness ceases. Near-death experiences (Parnia, van Lommel studies) show unexpected reports during clinical death, but cannot yet distinguish surviving consciousness from residual brain activity or brain-based hallucination. Biology: your atoms return to the earth and continue in other bodies. Information theory: some argue consciousness cannot survive without a substrate; others speculate about information persistence.",
    spiritual: "Hindus and Buddhists: rebirth guided by karma, continuing until liberation (moksha/nirvana). Abrahamic traditions: soul continues to judgment, then heaven, hell, or intermediate state. Taoists: return to the Tao. Indigenous traditions: ancestors remain present. Advaita: what dies was never the real you; that which knows the dying does not die.",
    philosophical: "Epicurus: 'When death is, I am not; when I am, death is not' — a call to serenity through non-existence. Heidegger: authentic living requires facing being-toward-death. Ernest Becker: much of human culture is a denial of death. The Stoics practiced memento mori daily.",
    historical: "Every burial ever found — from Neanderthal flower graves to the Pyramids to the modern hospice — testifies that humans have never accepted death as final. Whether this is wishful thinking or intuition of something real remains contested.",
    synthesis: "No one knows. Live as if today is real (it is), and as if consciousness is precious (it demonstrably is), and let the rest be a question you carry, not one you answer prematurely.",
  },
  {
    id: 'who',
    q: 'Who am I?',
    scientific: "Neuroscience: 'you' are a construction. The default-mode network stitches memory, sensation, and prediction into a narrative self. Split-brain studies (Sperry, Gazzaniga) show that severing the corpus callosum produces two centers of awareness in one body. Body ownership illusions show 'I' can shift into a rubber hand in minutes. The self is real as a functional pattern, less real as a solid thing.",
    spiritual: "The Upanishads answer: Neti, neti — 'not this, not this.' You are not the body (it changes), not the mind (it changes), not the roles (they change). You are the awareness in which all changing appears. Ramana Maharshi's whole teaching is one question: 'Who am I?' pursued until the questioner dissolves. Buddhism arrives similarly: no fixed self, only processes.",
    philosophical: "Locke: self is continuity of memory. Hume: no self is ever found in introspection — only bundles of perceptions. Descartes: whatever thinks is the self. Existentialists: self is what you make of yourself. Advaita and phenomenology converge: the observing awareness is more fundamental than the observed self-story.",
    historical: "The concept of a bounded individual self is not universal. Many indigenous cultures locate selfhood in kinship, land, and ancestors. Modern Western individualism is roughly 300 years old — a very recent human experiment.",
    synthesis: "You are certainly not nothing. But you are almost certainly not the small, defended thing you often take yourself to be. Sit long enough with the question and something quieter than the answer arises.",
  },
  {
    id: 'love',
    q: 'What is love?',
    scientific: "Neurochemistry of love: attraction (dopamine, norepinephrine), attachment (oxytocin, vasopressin), and long-term bonding (opioid systems). fMRI shows romantic love activates the same reward circuits as addiction. Compassionate love (loving-kindness meditation) increases vagal tone, immune markers, and empathic accuracy. Attachment theory (Bowlby, Ainsworth) shows the shape of early love shapes adult relationships.",
    spiritual: "Christianity places agape (self-giving love) at the center of ethics. Islam repeats rahma (mercy/compassion) as God's first name. Bhakti (devotional love) is one of the four yogas in the Gita. Buddhism cultivates metta (loving-kindness) and karuna (compassion) toward all beings. Sufis describe union with the Beloved through love that shatters the ego. Every tradition agrees: love is not what you feel, it is what you do.",
    philosophical: "Plato's Symposium: love as the desire to possess the good forever; erotic love as ladder to the divine. Aristotle: philia (friendship) is the highest love, based on shared virtue. Kierkegaard: love is a duty, not a feeling. Iris Murdoch: love is 'the extremely difficult realization that something other than oneself is real.'",
    historical: "Romantic love as we know it was invented (or at least intensified) by the troubadours in 12th-century Provence. Before that, marriage was largely economic; love was directed at gods, families, or friends. Today Western culture has perhaps over-loaded romantic love with metaphysical weight that older cultures spread across many relationships.",
    synthesis: "Love is at once a chemical, a discipline, a metaphysic, and a mystery. When the chemicals fade, the discipline remains. When the discipline is sincere, the mystery deepens.",
  },
  {
    id: 'purpose',
    q: 'What is my purpose?',
    scientific: "Psychology (Viktor Frankl, Martin Seligman): having a sense of purpose predicts longer life, better health, lower depression, higher resilience. Blue Zones research (Buettner) found ikigai (Japanese for 'reason for being') in most centenarians. Purpose need not be grand — regular acts aligned with your values suffice. Rick Weissbourd's work: purpose typically forms at the intersection of what you're good at, what you love, and what the world needs.",
    spiritual: "Bhagavad Gita: your dharma is your unique duty according to your nature and station. Doing another's dharma perfectly is worse than doing your own imperfectly. Buddhism: relieve suffering — your own and others'. Christianity: love God and love your neighbor. Sufism: polish the mirror of the heart. Purpose is not discovered so much as recognized — a fit between who you are and what is needed.",
    philosophical: "Aristotle: eudaimonia — human flourishing through virtuous action according to one's nature. Existentialists: no pre-given purpose; you must create one. Nietzsche: give birth to a dancing star. Camus: even in absurdity, we must imagine Sisyphus happy.",
    historical: "For most of history, purpose was inherited: your father's trade, your community's role, your tradition's task. Modern life offers unprecedented freedom and unprecedented anxiety — you must now author your own purpose, often without guidance.",
    synthesis: "Purpose is less a lightning bolt than a compass. Start with what you cannot NOT do, refine by service, and check the direction weekly. The journey itself becomes the answer.",
  },
  {
    id: 'fate',
    q: 'Is there fate, or am I free?',
    scientific: "Neuroscience of free will: Libet's experiments (1980s) showed the brain initiates action before conscious awareness — challenging naive free will. But newer research (Schurger) suggests these signals are noise, not decisions. Quantum indeterminacy is real but probably irrelevant to macroscopic brain activity. What is well-established: behavior is deeply shaped by genes, upbringing, hormones, gut microbes, and context — while conscious deliberation still measurably affects outcomes.",
    spiritual: "Hinduism: karma shapes what arises to you, but how you respond is free — this is why sadhana (practice) matters. Bhagavad Gita: 'You have a right to action, never to the fruit.' Sufism speaks of tawakkul — trust that lets you act fully without controlling outcomes. Buddhism: dependent origination — nothing is uncaused, but the mind is trainable, so future causes are shapeable. Christianity often holds free will and providence together as paradox.",
    philosophical: "Hard determinists (Sam Harris): no free will, and that's fine. Libertarians (van Inwagen): genuine free will exists. Compatibilists (Dennett): free will and determinism can both be true — what matters is that your actions flow from your reasons. Advaita: fate is real for the ego; freedom is real for the Self.",
    historical: "Ancient Greeks: even the gods bowed to Moira (fate). Calvin: predestination. Islam: qadar — divine decree balanced with human accountability. Modernity swung hard toward autonomy, and now swings back as we see how much of us is not chosen.",
    synthesis: "You are both more determined and more free than you feel. Practice acts on the tiny margin of freedom until that margin becomes the whole life.",
  },
  {
    id: 'meaning',
    q: 'How do I find meaning?',
    scientific: "Meaning correlates with three factors (research by Michael Steger et al.): coherence (the world makes sense), purpose (I'm going somewhere), and significance (my life matters). Interventions that reliably increase meaning: acts of service, deep relationships, contact with nature, awe experiences, creative work, and contemplative practice.",
    spiritual: "Every tradition offers a container of meaning: dharma (Hindu), bodhicitta (Buddhist), covenant (Jewish), imitatio Christi (Christian), remembrance of God (Islamic), the Tao (Taoist). Meaning is not something you find — it is something you enter through commitment to a practice larger than yourself.",
    philosophical: "Frankl (Auschwitz survivor): meaning is possible even in suffering — through work, love, or courageous suffering. Camus: acknowledge the absurd, then live with revolt, freedom, and passion. Susan Wolf: meaning arises when you're actively engaged in projects of objective worth.",
    historical: "Traditional cultures had meaning built into the structure of life. Modernity dismantled that structure in exchange for freedom, and left us with the task of re-building meaning individually. The great danger of our era is not despair but distraction.",
    synthesis: "Meaning is not thought — it is done. Serve one person today. Notice one moment of beauty. The abstract question dissolves in the concrete act.",
  },
  {
    id: 'peace',
    q: 'How can I become peaceful?',
    scientific: "Peace is a nervous-system state: high vagal tone, dominant parasympathetic activity, coherent heart-rate variability. Reliable ways to induce it: slow diaphragmatic breathing (4-6 breaths/minute), meditation, exercise, sleep, sunlight, cold exposure, prosocial connection. The default-mode network — the source of most rumination — quiets during flow states and meditation.",
    spiritual: "The Bhagavad Gita: 'One whose mind is undisturbed by sorrow, who has no craving for pleasure, who is free from attachment, fear, and anger — this one is called a sage of steady wisdom.' The Buddha: peace comes from letting go of grasping. Jesus: 'Peace I leave with you, my peace I give unto you — not as the world gives.' Rumi: 'The quieter you become, the more you can hear.'",
    philosophical: "Stoics: peace comes from mastering judgment, not events. Epicureans: through simple pleasures and freedom from fear. Zhuangzi: peace comes from wu wei — not-forcing action.",
    historical: "Cultures with strong contemplative traditions consistently report higher measures of subjective well-being at all income levels. The modern world has more comfort and less peace than perhaps any age before — a paradox worth taking seriously.",
    synthesis: "Peace is not a place you reach. It is a nervous system trained by daily practice. Start with three minutes of slow breathing today.",
  },
  {
    id: 'happiness',
    q: 'What is real happiness?',
    scientific: "Positive psychology distinguishes hedonic happiness (pleasure) from eudaimonic well-being (meaning, growth, contribution). Hedonic happiness has strong adaptation — the lottery winner returns to baseline within a year. Eudaimonic well-being is more durable. Reliable increases: gratitude practice, close relationships, service, meaningful work, sleep, movement.",
    spiritual: "The Upanishads describe ananda — bliss — as the nature of Brahman itself, not something added to us. The Bhagavad Gita: 'The happiness which at first seems like poison but in the end is like nectar — that is the happiness of goodness.' Buddhism: sukha (real happiness) arises when suffering's causes are removed, not when pleasures are added.",
    philosophical: "Aristotle: happiness is not a feeling but an activity of soul in accord with virtue. Stoics: happiness is freedom from disturbance (ataraxia). Utilitarians: maximize pleasure minimize pain. Advaita: happiness is the natural state; only ignorance obscures it.",
    historical: "The idea that everyone deserves happiness is a modern one — arriving with the Enlightenment. Before that, most cultures aimed for honor, salvation, or duty, and happiness was a fortunate side-effect.",
    synthesis: "Chasing happiness usually kills it. Building a good life — one relationship, one act of service, one honest hour at a time — usually delivers it as a byproduct.",
  },
  {
    id: 'ego',
    q: 'What is the ego?',
    scientific: "Neuroscience: the sense of a bounded, continuous self is produced largely by the default-mode network (DMN), which becomes hyperactive in depression and quiet in flow and meditation. It is a functional simulation — useful for planning, terrible when it thinks it is all of you. Psilocybin and long-term meditation both reduce DMN activity and often produce ego-dissolution experiences.",
    spiritual: "Advaita: ahamkara — the 'I-maker' — is the mistaken identification of Self with body-mind. Buddhism: anatta — no fixed self exists, though the illusion of one does. Sufism: the nafs must be tamed through remembrance until fana (annihilation of ego in the divine) occurs. Christianity: 'unless a grain of wheat falls into the earth and dies, it remains alone.'",
    philosophical: "Freud invented the modern usage: ego mediates between id (drives) and superego (norms). Jung: ego is the center of the conscious mind, not the Self (the greater totality). Buddhist philosophers argue Freud rediscovered ancient insight in modern language.",
    historical: "Older cultures typically had less ego-inflation because identity was communal and rooted in role. Modern selfhood — hyper-individual, always self-branding — is historically anomalous and psychologically costly.",
    synthesis: "The ego is a tool, not an enemy. You need one to drive to work. Just do not let it think it is the driver of your entire life.",
  },
  {
    id: 'religions',
    q: 'Why do religions differ so much?',
    scientific: "Cultural evolution (Boyd, Henrich): religions co-evolved with the societies that carried them, adapted to specific climates, food systems, and political structures. Certain features (moralizing gods, ritual, sacred texts) recur because they solve universal cooperation problems. Others differ because different environments demand different solutions.",
    spiritual: "The mystical cores of religions differ far less than their surfaces. Rumi, Meister Eckhart, Ramana Maharshi, and Chan Master Huineng say strikingly similar things about non-dual awareness — despite writing in Persian, Latin, Tamil, and Chinese, centuries apart. The differences are largely in language, imagery, ritual, and social organization — not in the terminus.",
    philosophical: "John Hick's pluralism: religions are different responses to the same Ultimate Reality, filtered through cultural lens. Wittgenstein: religious language is a form of life, not a set of propositions. Exclusivists disagree. Perennial philosophy (Aldous Huxley, Frithjof Schuon) argues an eternal metaphysic underlies all traditions.",
    historical: "Religions diverge along trade routes, empires, and languages. Mahayana Buddhism looks little like Theravada; Sufi Islam little like Wahhabi Islam; Orthodox Christianity little like Pentecostal Christianity. Yet all four contain the same central insights. History shows unity beneath diversity — and diversity within every apparent unity.",
    synthesis: "Different fingers, one moon. When people fight about the finger, they have already forgotten to look up.",
  },
  {
    id: 'science-spirit',
    q: 'How can science and spirituality coexist?',
    scientific: "They already do, in most working scientists' lives. Surveys (Pew, Ecklund) find roughly half of US scientists identify with a religion or spiritual practice. Science is a method for investigating measurable phenomena; spirituality is a method for investigating consciousness from the inside. They ask different questions with different tools.",
    spiritual: "Every serious tradition welcomes rigorous inquiry — the Buddha's 'come and see for yourself'; the Upanishadic 'know thyself'; the Sufi 'unveiling'; the Jesuit's 'discernment.' Spirituality without inquiry becomes superstition. Science without reverence becomes technocracy. Together they are the two eyes of one human seeing.",
    philosophical: "Stephen Jay Gould called them 'non-overlapping magisteria.' Others (Barbour, Polkinghorne, Ken Wilber) argue they overlap and can enrich each other. The Dalai Lama: 'If science proves some belief of Buddhism wrong, then Buddhism will have to change.' That is the right posture in both directions.",
    historical: "Newton wrote more on theology than physics. Georges Lemaître, who proposed the Big Bang, was a Catholic priest. Vivekananda addressed the World Parliament of Religions in 1893 already speaking of harmony between science and Vedanta. The 'war between science and religion' is largely a 19th-century myth.",
    synthesis: "Science tells you how the universe works. Spirituality tells you how to live in it. You need both.",
  },
  {
    id: 'change',
    q: 'How do I actually change?',
    scientific: "Real change is neural — new synaptic pathways, strengthened through repetition. Willpower alone fails (Baumeister); systems succeed (Fogg, Clear). Change is easier when: cue is unavoidable, action is small, reward is immediate, environment supports it, identity aligns with it. Meditation, journaling, exercise, and sleep are force multipliers.",
    spiritual: "The Gita: 'The mind is restless, but it can be tamed by regular practice and by dispassion.' Buddha's Eightfold Path is a system of change — right view, intention, speech, action, livelihood, effort, mindfulness, concentration. Sufis speak of tazkiyah — polishing the heart, layer by layer. All traditions agree: consistent small practice beats sporadic heroic effort.",
    philosophical: "Aristotle: 'We are what we repeatedly do. Excellence is not an act, but a habit.' Confucius: transformation happens through ritual (li) and self-cultivation over decades. Existentialists insist you become through choice — but they concede that choice is easier when the ground has been prepared.",
    historical: "Every tradition of human formation — monastic, martial, artistic, scientific — uses the same recipe: mentor, discipline, deliberate practice, community, feedback. The technologies of change are more universal than the philosophies that carry them.",
    synthesis: "You do not change by trying harder. You change by installing better structures and letting them work on you for a long time. Trust the compounding.",
  },
];

export const WORLD_TEMPLES = [
  { name: 'Kedarnath', country: 'India', region: 'Asia', tradition: 'Hinduism', lat: 30.73, lng: 79.07,
    image: 'https://images.unsplash.com/photo-1603766806347-54cdf3745953?auto=format&fit=crop&w=1200&q=80',
    note: 'Jyotirlinga of Shiva at 3,583m in the Himalayas. Miraculously survived the 2013 flood.' },
  { name: 'Varanasi (Kashi)', country: 'India', region: 'Asia', tradition: 'Hinduism', lat: 25.32, lng: 82.97,
    image: 'https://images.unsplash.com/photo-1561361058-c24cecda7c25?auto=format&fit=crop&w=1200&q=80',
    note: "The world's oldest continuously inhabited city, sacred to Shiva. To die here is said to grant moksha." },
  { name: 'Meenakshi Temple', country: 'India', region: 'Asia', tradition: 'Hinduism', lat: 9.92, lng: 78.12,
    image: 'https://images.unsplash.com/photo-1621996659490-3275b4d0d951?auto=format&fit=crop&w=1200&q=80',
    note: 'Madurai. Fourteen gopurams covered in over 30,000 sculpted figures — a stone Bhagavata.' },
  { name: 'Tirumala', country: 'India', region: 'Asia', tradition: 'Hinduism', lat: 13.68, lng: 79.35,
    image: 'https://images.unsplash.com/photo-1609859745858-95eb5c34cae1?auto=format&fit=crop&w=1200&q=80',
    note: "Venkateswara Temple — one of the world's richest and most visited pilgrimage sites." },
  { name: 'Golden Temple', country: 'India', region: 'Asia', tradition: 'Sikhism', lat: 31.62, lng: 74.87,
    image: 'https://images.unsplash.com/photo-1587899765491-a4c98c4a5b28?auto=format&fit=crop&w=1200&q=80',
    note: 'Harmandir Sahib, Amritsar. Serves free langar (community meal) to 100,000+ people daily.' },
  { name: 'Bodh Gaya', country: 'India', region: 'Asia', tradition: 'Buddhism', lat: 24.70, lng: 84.99,
    image: 'https://images.unsplash.com/photo-1592393991860-9d5cddca8daf?auto=format&fit=crop&w=1200&q=80',
    note: 'Where the Buddha attained enlightenment under the Bodhi tree. The tree that stands today is a direct descendant.' },
  { name: 'Angkor Wat', country: 'Cambodia', region: 'Asia', tradition: 'Hindu/Buddhist', lat: 13.41, lng: 103.87,
    image: 'https://images.unsplash.com/photo-1573352763925-82bd5dfc31d1?auto=format&fit=crop&w=1200&q=80',
    note: 'The largest religious monument in the world, an architectural miniature of the Hindu cosmos.' },
  { name: 'Borobudur', country: 'Indonesia', region: 'Asia', tradition: 'Buddhism', lat: -7.61, lng: 110.20,
    image: 'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?auto=format&fit=crop&w=1200&q=80',
    note: "World's largest Buddhist temple. Ascending its terraces is a walking meditation from earth to enlightenment." },
  { name: 'Potala Palace', country: 'Tibet', region: 'Asia', tradition: 'Buddhism', lat: 29.66, lng: 91.12,
    image: 'https://images.unsplash.com/photo-1580881091335-4989b5cd39ac?auto=format&fit=crop&w=1200&q=80',
    note: 'Winter palace of the Dalai Lamas from 1649 to 1959. Perched at 3,700m.' },
  { name: 'Mount Kailash', country: 'Tibet', region: 'Asia', tradition: 'Hindu/Buddhist/Bon/Jain', lat: 31.07, lng: 81.31,
    image: 'https://images.unsplash.com/photo-1541661814024-ef4bab48ba0f?auto=format&fit=crop&w=1200&q=80',
    note: 'The mountain never climbed. Sacred to four traditions; 52 km circumambulation by pilgrims.' },
  { name: 'Kinkaku-ji', country: 'Japan', region: 'Asia', tradition: 'Zen Buddhism', lat: 35.04, lng: 135.73,
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80',
    note: 'The Golden Pavilion in Kyoto. Zen aesthetics of impermanence and reflection.' },
  { name: 'Ise Grand Shrine', country: 'Japan', region: 'Asia', tradition: 'Shinto', lat: 34.45, lng: 136.72,
    image: 'https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?auto=format&fit=crop&w=1200&q=80',
    note: 'Dedicated to Amaterasu. Ritually rebuilt every 20 years for the past 1,300 years.' },
  { name: 'Kaaba', country: 'Saudi Arabia', region: 'Middle East', tradition: 'Islam', lat: 21.42, lng: 39.83,
    image: 'https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?auto=format&fit=crop&w=1200&q=80',
    note: 'The direction all Muslims face in prayer. Every Muslim who is able circumambulates it once in their lifetime.' },
  { name: 'Dome of the Rock', country: 'Jerusalem', region: 'Middle East', tradition: 'Islam/Judaism/Christianity', lat: 31.78, lng: 35.24,
    image: 'https://images.unsplash.com/photo-1544967082-d9d25d867d66?auto=format&fit=crop&w=1200&q=80',
    note: 'Sacred to three Abrahamic religions. Built in 691 CE atop the Foundation Stone.' },
  { name: 'Western Wall', country: 'Jerusalem', region: 'Middle East', tradition: 'Judaism', lat: 31.78, lng: 35.23,
    image: 'https://images.unsplash.com/photo-1544923503-a1f6d3b8b1a4?auto=format&fit=crop&w=1200&q=80',
    note: 'The last remnant of the Second Temple. Prayers pressed between its stones for millennia.' },
  { name: 'Rumi\u2019s Tomb', country: 'Turkey', region: 'Middle East', tradition: 'Sufi Islam', lat: 37.87, lng: 32.50,
    image: 'https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?auto=format&fit=crop&w=1200&q=80',
    note: 'Konya. Where the 13th-century Sufi mystic Jalaluddin Rumi is buried, still visited by seekers of every faith.' },
  { name: 'Hagia Sophia', country: 'Turkey', region: 'Middle East', tradition: 'Christian \u2192 Muslim', lat: 41.01, lng: 28.98,
    image: 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&w=1200&q=80',
    note: 'Built 537 CE. Cathedral, mosque, museum, and mosque again \u2014 a mirror of religious history.' },
  { name: 'St Peter\u2019s Basilica', country: 'Vatican', region: 'Europe', tradition: 'Catholic Christianity', lat: 41.90, lng: 12.45,
    image: 'https://images.unsplash.com/photo-1516475429286-465d815a0df7?auto=format&fit=crop&w=1200&q=80',
    note: 'Built over the tomb of Saint Peter. The largest church in the world.' },
  { name: 'Chartres Cathedral', country: 'France', region: 'Europe', tradition: 'Christianity', lat: 48.45, lng: 1.48,
    image: 'https://images.unsplash.com/photo-1590064829005-b8b39caa8d09?auto=format&fit=crop&w=1200&q=80',
    note: 'Gothic masterpiece with the famous labyrinth. Walked as a pilgrimage substitute in the Middle Ages.' },
  { name: 'Mont Saint-Michel', country: 'France', region: 'Europe', tradition: 'Christianity', lat: 48.64, lng: -1.51,
    image: 'https://images.unsplash.com/photo-1580074309247-14ba53e57bdd?auto=format&fit=crop&w=1200&q=80',
    note: 'Abbey rising from tidal flats, dedicated to Archangel Michael. A place of pilgrimage since the 8th century.' },
  { name: 'Iona Abbey', country: 'Scotland', region: 'Europe', tradition: 'Celtic Christianity', lat: 56.33, lng: -6.39,
    image: 'https://images.unsplash.com/photo-1517166284681-c1c3a05c31d2?auto=format&fit=crop&w=1200&q=80',
    note: 'St Columba landed here in 563 CE. Considered a \u201Cthin place\u201D where heaven and earth meet.' },
  { name: 'Stonehenge', country: 'England', region: 'Europe', tradition: 'Pre-historic sacred site', lat: 51.18, lng: -1.83,
    image: 'https://images.unsplash.com/photo-1599833975787-5c143f373c30?auto=format&fit=crop&w=1200&q=80',
    note: 'Neolithic monument aligned to the solstices. Its exact purpose remains debated.' },
  { name: 'Chichen Itza', country: 'Mexico', region: 'Americas', tradition: 'Maya', lat: 20.68, lng: -88.57,
    image: 'https://images.unsplash.com/photo-1518638150340-f706e86654de?auto=format&fit=crop&w=1200&q=80',
    note: 'The pyramid of Kukulkan: on equinoxes, a serpent of shadow descends its staircase.' },
  { name: 'Machu Picchu', country: 'Peru', region: 'Americas', tradition: 'Inca', lat: -13.16, lng: -72.55,
    image: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&w=1200&q=80',
    note: 'Sacred royal estate of the Inca, aligned to solstices and stars, 2,430m above sea level.' },
  { name: 'Uluru', country: 'Australia', region: 'Oceania', tradition: 'Anangu (Indigenous)', lat: -25.35, lng: 131.03,
    image: 'https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?auto=format&fit=crop&w=1200&q=80',
    note: 'A living sacred site for the Anangu people. Its songlines record 50,000+ years of stewardship.' },
  { name: 'Great Pyramid', country: 'Egypt', region: 'Africa', tradition: 'Ancient Egyptian', lat: 29.98, lng: 31.13,
    image: 'https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?auto=format&fit=crop&w=1200&q=80',
    note: 'The last surviving Wonder of the Ancient World. Aligned to true north with astonishing precision.' },
  { name: 'Lalibela', country: 'Ethiopia', region: 'Africa', tradition: 'Ethiopian Christianity', lat: 12.03, lng: 39.05,
    image: 'https://images.unsplash.com/photo-1580058572462-8a2ecd90fd35?auto=format&fit=crop&w=1200&q=80',
    note: 'Eleven medieval churches carved downward into solid rock. Still an active pilgrimage site.' },
];

// Sacred music: YouTube video IDs (avoid embedding costs, wide availability)
export const SACRED_MUSIC = [
  { id: 'V-a3SS4KaJU', title: 'Om Chanting \u00b7 108 Times', tradition: 'Hindu', category: 'Mantra',
    color: 'from-amber-400 to-orange-600', note: 'The primordial sound. Vibrates at ~136.1 Hz \u2014 the resonant frequency of Earth.' },
  { id: 'g0e-x27FQxU', title: 'Gayatri Mantra \u00b7 108 Times', tradition: 'Vedic', category: 'Mantra',
    color: 'from-yellow-400 to-amber-500', note: 'The most sacred Vedic mantra, addressing the light of consciousness itself.' },
  { id: 'jHhogPCTF4M', title: 'Om Namah Shivaya', tradition: 'Shaiva', category: 'Mantra',
    color: 'from-purple-500 to-fuchsia-600', note: 'The five-syllable mantra of Shiva. Panchakshari.' },
  { id: 'B4E9GkjS4Sk', title: 'Mahamrityunjaya Mantra', tradition: 'Hindu', category: 'Mantra',
    color: 'from-rose-500 to-pink-600', note: 'Rig Veda 7.59.12 \u2014 the great mantra of liberation from fear of death.' },
  { id: 'oxV-hFDwl-Y', title: 'Tibetan Singing Bowls', tradition: 'Buddhist', category: 'Bowls',
    color: 'from-cyan-400 to-blue-500', note: 'Overtones that quiet the default-mode network.' },
  { id: 'yQvyOZFqvcU', title: 'Gregorian Chant', tradition: 'Christian', category: 'Chant',
    color: 'from-slate-300 to-purple-400', note: 'Monastic sung prayer. Studies show slows breathing and heart rate.' },
  { id: 'iJnR2wDGSf8', title: 'Sufi Qawwali', tradition: 'Sufi Islam', category: 'Devotional',
    color: 'from-emerald-400 to-teal-500', note: 'Nusrat Fateh Ali Khan and the tradition of ecstatic devotional song.' },
  { id: 'WPni755-Krg', title: 'Nature Sounds \u00b7 Forest', tradition: 'Universal', category: 'Ambient',
    color: 'from-emerald-500 to-green-600', note: 'Studies show forest sounds reduce cortisol within minutes.' },
  { id: '1CVE9-YKPTM', title: 'Binaural Beats \u00b7 Theta 6Hz', tradition: 'Modern', category: 'Frequency',
    color: 'from-indigo-400 to-purple-500', note: 'Evidence is mixed but many practitioners find it aids meditation depth.' },
];
