// Deep lore: Aghoris, Sadhus, Gods, Avatars
// Every entry includes decorations, weapons, body-part connections, and formation stories.

export const AGHORIS = {
  intro: "Aghoris are a small, radical Shaiva sect that practices the path of non-duality by embracing what mainstream society rejects. Their name literally means 'not terrifying' (a-ghora) — a reminder that once you see the divine in everything, nothing can frighten you. They meditate in cremation grounds (shmashana), wear ashes of the dead, and worship Shiva in his fiercest form as Bhairava.",
  origin: "The lineage traces to Baba Kinaram of Varanasi (c. 1601-1771 CE), though the practice draws from far older Kapalika and Kalamukha traditions rooted in tantric Shaivism dating back to at least the 6th-7th century CE. Kinaram founded the Kina Ram Ashram at Krim Kund in Varanasi, still the sect's headquarters.",
  philosophy: "The core teaching: purity and impurity are illusions of the conditioned mind. What society labels 'polluted' (corpses, ashes, human waste, meat, intoxicants) contains the same Brahman as what it labels 'sacred'. By meditating in the graveyard the Aghori dissolves the ego's aversions and attachments simultaneously — the fastest, most dangerous route to non-dual realization.",
  practices: [
    { name: 'Shava Sadhana', dev: 'शव साधना', desc: 'Meditation seated upon a corpse — literal confrontation with the fear of death. The corpse is treated as a Shiva-lingam of consciousness.' },
    { name: 'Panchamakara', dev: 'पञ्चमकार', desc: 'The Five Ms: madya (wine), mamsa (meat), matsya (fish), mudra (parched grain), maithuna (union) — used as ritual substances to break dualistic conditioning. Done wrongly, they destroy the sadhaka.' },
    { name: 'Chita Bhasma', dev: 'चिता भस्म', desc: 'Smearing the body with ash from the funeral pyre — a constant meditation on impermanence and the reduction of all matter to dust.' },
    { name: 'Kapala Kriya', dev: 'कपाल क्रिया', desc: 'Use of a human skull (kapala) as an eating bowl — the ultimate reminder that the self is not the body.' },
    { name: 'Bhairava Mantra', dev: 'भैरव मन्त्र', desc: 'Repetition of Bhairava mantras, especially "Om Hreem Batukaya Aapaduddharanaya Kuru Kuru Batukaya Hreem" — invoking Shiva as protector against death itself.' },
  ],
  symbols: [
    { item: 'Ash (Bhasma)', meaning: 'The final form of every body — worn to remember the equality of all matter.' },
    { item: 'Rudraksha mala', meaning: 'Beads formed from Shiva\'s tears — used to count mantras and channel Rudra energy.' },
    { item: 'Kapala (skull bowl)', meaning: 'Symbolic of the ego that has been transcended; also a portable meditation device.' },
    { item: 'Trishul (trident)', meaning: 'The three gunas — sattva, rajas, tamas — pierced and unified by consciousness.' },
    { item: 'Damaru (small drum)', meaning: 'The sound of creation — the primordial vibration Shiva plays to sustain reality.' },
    { item: 'Naked or minimal cloth', meaning: 'Digambara — "clothed by the directions". Renunciation of social identity.' },
  ],
  famous: [
    { name: 'Baba Kinaram', dev: 'बाबा किनाराम', about: 'Founder of the modern Aghori lineage. His samadhi (tomb) at Krim Kund, Varanasi remains a pilgrimage site. Said to have lived 170 years.' },
    { name: 'Baba Kalu Ram', about: 'Kinaram\'s guru — a mysterious figure said to have initiated him at the burning ghats.' },
    { name: 'Baba Bhagwan Ram', about: '20th century Aghori who reformed the sect toward social service — leprosy care, tuberculosis treatment, and mass education. Died 1992.' },
    { name: 'Vimalananda', about: 'The Aghori guru whose life was documented by Robert Svoboda in the "Aghora" trilogy — the most detailed English record of the path.' },
  ],
  misconceptions: "Popular media reduces Aghoris to cannibalism and shock value. In reality, cannibalism is rare, symbolic, and never involves killing. The majority of contemporary Aghoris are peaceful ascetics who tend cremation grounds, provide medical care to lepers and outcastes, and live as reminders that death is the great teacher.",
  color: 'from-slate-500 to-purple-800',
  dev: 'अघोर',
};

export const SADHUS = {
  intro: "A sadhu (सधु, 'good one' or 'accomplished one') is a Hindu holy man or woman who has renounced worldly life to pursue moksha — liberation. Estimates suggest 4-5 million active sadhus in India today. They are not a single group but a vast constellation of orders, philosophies, and disciplines, each with its own initiation, dress, and practice.",
  types: [
    { name: 'Naga Sadhus', dev: 'नागा साधु', color: 'from-orange-400 to-red-600',
      about: 'The warrior-ascetics of the Dashanami order, founded by Adi Shankaracharya. They remain naked (naga) year-round, smear ash over their bodies, and traditionally trained as an army to defend Hindu temples against invaders. They appear en masse at the Kumbh Mela.',
      practice: 'Extreme austerities (tapas), weapons training, wrestling, mantra-yoga.',
      identify: 'Naked, ash-smeared, long matted jata hair, tridents, sometimes swords.' },
    { name: 'Aghori', dev: 'अघोरी', color: 'from-slate-500 to-purple-800',
      about: 'Tantric ascetics of the Kapalika/Kina Ram tradition. See separate detailed section.',
      practice: 'Cremation-ground sadhana, non-dual embrace of the taboo.',
      identify: 'Ash-covered, skull bowl, human bone ornaments, dwelling in shmashanas.' },
    { name: 'Vairagi / Bairagi', dev: 'वैरागी', color: 'from-amber-300 to-yellow-600',
      about: 'Vaishnava renunciates devoted to Vishnu, Rama or Krishna. Founded largely by Ramanuja and Ramananda. Non-violent, wear white or saffron, mark their foreheads with the U-shaped Vaishnava tilak.',
      practice: 'Bhakti — devotion, kirtan, temple service, pilgrimage.',
      identify: 'White or saffron robes, tulsi mala, urdhva-pundra tilak, no ash.' },
    { name: 'Udasi', dev: 'उदासी', color: 'from-blue-400 to-indigo-600',
      about: 'Founded by Baba Sri Chand (1494-1629), elder son of Guru Nanak. A bridge sect between Hinduism and Sikhism — celibate, ash-wearing, matted-haired ascetics who accept Sikh gurus and Vedic scripture equally.',
      practice: 'Meditation, ashram service, wandering.',
      identify: 'Ochre or brown robe, long matted hair, ash marks, sometimes a small drum.' },
    { name: 'Kanphata / Nath Yogis', dev: 'कानफटा नाथ', color: 'from-yellow-300 to-orange-500',
      about: 'The "split-eared" yogis of Guru Gorakhnath\'s Nath sampradaya. During initiation the cartilage of both ears is pierced to insert heavy earrings (mudra) — said to unlock a psychic channel. Practitioners of Hatha Yoga in its original form.',
      practice: 'Hatha yoga, kundalini, alchemy (rasayana), mantra.',
      identify: 'Enormous ring earrings, black wool blanket, whistle (nada), rudraksha mala.' },
    { name: 'Sanyasi (Dashanami)', dev: 'दशनामी सन्यासी', color: 'from-orange-500 to-red-500',
      about: 'The ten-named order of Advaita renunciates founded by Adi Shankaracharya in the 8th century. Named after ten suffixes: Giri, Puri, Bharati, Van, Aranya, Parvat, Sagar, Tirtha, Ashrama, Saraswati. Live in mathas across India.',
      practice: 'Study of Vedanta, meditation on "I am Brahman", teaching.',
      identify: 'Saffron robe, shaved head or top-knot, bamboo staff (danda), water pot (kamandalu).' },
    { name: 'Avadhuta', dev: 'अवधूत', color: 'from-fuchsia-400 to-purple-600',
      about: '"One who has shaken off all illusion." Enlightened beings beyond all rules and orders. May behave like children, madmen, or drunks — society cannot categorize them. Sage Dattatreya is the archetypal Avadhuta.',
      practice: 'Post-attainment; sahaja (spontaneous) living.',
      identify: 'Unpredictable — sometimes naked, sometimes elaborately dressed, always beyond convention.' },
    { name: 'Sadhvi (women sadhus)', dev: 'साध्वी', color: 'from-pink-300 to-rose-500',
      about: 'Female renunciates. Historically fewer, but growing numbers today. Present in most orders including Dashanami and Vaishnava. Some, like Anandamayi Ma and Sharada Devi, are considered fully realized.',
      practice: 'Same as male counterparts within their order.',
      identify: 'Saffron or white sari, tilak, mala.' },
    { name: 'Jangama', dev: 'जङ्गम', color: 'from-teal-400 to-emerald-600',
      about: 'The moving ("jangama") lingam-worshippers of the Lingayat / Veerashaiva tradition, founded by Basavanna in 12th-century Karnataka. Wear a small Shiva-lingam in a locket around the neck at all times.',
      practice: 'Ishtalinga meditation, service, kayaka (dignity of labor).',
      identify: 'Ishtalinga locket, ochre robes, vibhuti ash marks.' },
  ],
  becoming: "Formal renunciation (sannyasa diksha) involves a ceremony called Viraja Homa in which the initiate performs their own funeral rites — legally and spiritually declaring themselves dead to the previous life. The sacred thread, family name, caste, and worldly identity are all cast into the fire. A new name is given by the guru. The initiate then wears the robes and lives on alms.",
  color: 'from-orange-400 to-red-600',
  dev: 'साधु',
};

export const GODS = [
  {
    id: 'shiva', name: 'Shiva', dev: 'शिव',
    role: 'The Transformer · The Destroyer · Adiyogi',
    color: 'from-slate-300 to-blue-600',
    consort: 'Parvati',
    mount: 'Nandi (the bull)',
    abode: 'Mount Kailash',
    formation: "In the Shiva Purana, Shiva is beginningless (Anadi) — he exists before creation. When Brahma and Vishnu argued over who was greater, an infinite lingam of light appeared between them. Neither could find its top nor bottom. That endless pillar was Shiva — the formless from which form emerges. As a person, he is imagined as a blue-throated ascetic meditating on Mount Kailash, hair matted into a jata, the crescent moon and the Ganges resting in his locks.",
    decorations: [
      { item: 'Trishul (Trident)', dev: 'त्रिशूल', why: 'The three prongs represent the three gunas (sattva, rajas, tamas), the three states (waking, dream, deep sleep), and the three worlds (bhu, bhuva, svah). To hold the trishul is to master all three simultaneously.' },
      { item: 'Damaru (Drum)', dev: 'डमरू', why: 'A small two-sided drum whose beats are said to produce the 14 fundamental sounds of Sanskrit — the Maheshwara Sutras from which Panini derived grammar itself. The drum represents the vibration that creates and dissolves the universe.' },
      { item: 'Crescent Moon', dev: 'चन्द्र', why: 'Adorns his matted hair. The waxing crescent represents time (kaal) — Shiva contains time itself, unaffected by its cycles.' },
      { item: 'Ganga in his hair', dev: 'गङ्गा', why: 'When the Ganges descended from heaven, her force would have shattered the earth. Shiva caught her in his matted locks and let her flow gently. Symbol of consciousness holding raw cosmic power.' },
      { item: 'Third Eye', dev: 'त्रिनेत्र', why: 'The eye of wisdom (jnana-chakshu) between the brows. When opened, it burns illusion instantly — as it burned Kamadeva (desire) to ash. Corresponds to the ajna chakra.' },
      { item: 'Nag (Serpent) around neck', dev: 'नाग', why: 'Vasuki, king of nagas. The serpent represents kundalini energy fully awakened and mastered — no longer feared but worn as an ornament.' },
      { item: 'Ash smeared on body', dev: 'भस्म', why: 'Vibhuti — a constant reminder that every material form ends in ash. To wear ash is to have transcended the fear of death.' },
      { item: 'Rudraksha mala', dev: 'रुद्राक्ष', why: 'Beads formed from Shiva\'s own tears of compassion for the suffering of the world. Worn to steady the heart-rate and hold the mantra.' },
      { item: 'Tiger skin seat', dev: 'व्याघ्रचर्म', why: 'Sitting on the skin of a tiger indicates conquest over rajas (passion, aggression) — Shiva is the yogi who has mastered the beast.' },
    ],
    weapons: [
      { name: 'Trishul (Trident)', used_for: 'Destroys the three gunas, cutting through illusion. Used to slay demons like Andhaka.' },
      { name: 'Pinaka (Bow)', used_for: 'The original divine bow — the same bow strung by Rama in the Ramayana. Represents the disciplined mind that can send consciousness like an arrow to any target.' },
      { name: 'Pashupatastra', used_for: 'The ultimate weapon capable of destroying all creation. Given to Arjuna after tapasya. Never used unless the universe itself is threatened.' },
      { name: 'Trident-tipped Damaru', used_for: 'Sound itself as a weapon — the vibration that dissolves attachment.' },
    ],
    body_connections: "Shiva rules the Sahasrara (crown chakra) — the seat of pure consciousness. His blue throat (Neelakantha) marks the vishuddha chakra: after drinking the halahala poison during the churning of the ocean, Parvati held it in his throat so it would not spread. Meditation on Shiva stabilizes the ajna (third eye) and dissolves the ahamkara (ego). Nataraja's dance is a map of the entire nervous system — his raised leg is prana, his stamping foot is apana.",
    forms: ['Nataraja (Lord of Dance)', 'Bhairava (Terrifying)', 'Ardhanarishvara (Half-woman)', 'Dakshinamurthi (Silent Teacher)', 'Rudra (Fierce)', 'Lingodbhava (Pillar of Light)', 'Neelakantha (Blue-throated)', 'Pashupati (Lord of Beings)'],
  },
  {
    id: 'vishnu', name: 'Vishnu', dev: 'विष्णु',
    role: 'The Preserver · The Sustainer',
    color: 'from-blue-400 to-cyan-600',
    consort: 'Lakshmi',
    mount: 'Garuda (the eagle)',
    abode: 'Vaikuntha (on the cosmic ocean of milk, Kshira Sagara)',
    formation: "Vishnu manifests from the primordial waters. In the classical image he reclines on Ananta-Shesha, the thousand-headed serpent, upon the Ocean of Milk. From his navel grows a lotus, on which sits Brahma — from whom creation unfolds. When dharma declines, Vishnu incarnates as an Avatar to restore balance. He is the principle of preservation — the force that holds the universe together between Brahma's creation and Shiva's dissolution.",
    decorations: [
      { item: 'Kaustubha gem', dev: 'कौस्तुभ', why: 'A brilliant jewel worn on his chest — emerged from the churning of the ocean. Represents pure consciousness that all souls seek to return to.' },
      { item: 'Srivatsa mark', dev: 'श्रीवत्स', why: 'A curl of hair on his chest, where Goddess Lakshmi resides. Symbol that prosperity is inseparable from dharma.' },
      { item: 'Vaijayanti Mala', dev: 'वैजयन्ती', why: 'A garland of forest flowers with five stones representing the five elements — Vishnu wears all five within his being.' },
      { item: 'Yellow silk (Pitambara)', dev: 'पीताम्बर', why: 'Golden-yellow silk garments — the color of pure sattva, of the sun, of dharma unshaken.' },
      { item: 'Peacock feather (Krishna form)', dev: 'मयूरपिच्छ', why: 'The eye on the peacock feather represents cosmic vision — Krishna sees all past, present, and future simultaneously.' },
      { item: 'Four Arms', dev: 'चतुर्भुज', why: 'Represents his presence in all four directions and dominion over the four aims of life — dharma, artha, kama, moksha.' },
    ],
    weapons: [
      { name: 'Sudarshan Chakra', used_for: 'A spinning disc of pure will — the mind sharpened by discrimination (viveka). It follows the target of its own accord and returns. Beheaded Rahu, cut down countless demons.' },
      { name: 'Panchajanya (Conch)', used_for: 'The conch produced Om, the primordial sound. Blown to announce dharma and dispel fear. Krishna blew it to open the Mahabharata war.' },
      { name: 'Kaumodaki (Mace)', used_for: 'A mace representing the cosmic ego (mahat-tattva) — the disciplined power of intellect used to crush adharma.' },
      { name: 'Sharanga (Bow)', used_for: 'The divine bow with arrows that never miss. Used in the Rama and Krishna avatars.' },
      { name: 'Nandaka (Sword)', used_for: 'The sword of wisdom (jnana-khanda) that cuts through the knots of ignorance.' },
    ],
    body_connections: "Vishnu is associated with the ajna and anahata chakras — the heart of compassion and the eye of wisdom. His blue skin represents the infinite (like the sky and ocean). The four arms correspond to the four Vedas absorbed into his being. Devotees who chant Vishnu Sahasranama report activation of the vagus nerve — the sound patterns synchronize breath and heart.",
    forms: ['Narayana (on the cosmic waters)', 'Vaikuntha-Vishnu', 'Ranganatha (reclining)', 'Venkateshwara (Tirupati)', 'Vithoba (Pandharpur)', 'Jagannatha (Puri)'],
  },
  {
    id: 'brahma', name: 'Brahma', dev: 'ब्रह्मा',
    role: 'The Creator',
    color: 'from-red-400 to-orange-600',
    consort: 'Saraswati',
    mount: 'Hamsa (the swan)',
    abode: 'Brahmaloka / Satyaloka',
    formation: "Brahma is born from the lotus emerging from Vishnu's navel. He is the active principle of creation — the four-faced deity who chants the four Vedas simultaneously from each face. His day (kalpa) lasts 4.32 billion years — a full cycle of the universe. When he sleeps, the universe dissolves. When he wakes, it manifests again.",
    decorations: [
      { item: 'Four faces', dev: 'चतुर्मुख', why: 'Originally five; Shiva cut off the fifth for arrogance. The four represent the four Vedas, the four yugas, the four directions, and the four states of consciousness.' },
      { item: 'Kamandalu (water pot)', dev: 'कमण्डलु', why: 'Contains the primordial waters from which all life emerged. Symbol of the source.' },
      { item: 'Rudraksha mala', dev: 'रुद्राक्ष', why: 'Represents time — the beads he moves as he counts out the ages of creation.' },
      { item: 'White beard', dev: 'श्वेत दाढ़ी', why: 'Signifies eternity and the wisdom of infinite creations he has witnessed.' },
    ],
    weapons: [
      { name: 'Not a warrior deity', used_for: 'Brahma is the creator, not the destroyer. His "weapon" is Vak — divine speech, the power to create by naming.' },
    ],
    body_connections: "Brahma corresponds to the muladhara (root) chakra — the point where consciousness enters matter. The Brahma-granthi (Brahma\'s knot) is the first of three energetic knots kundalini must pierce. His mount, the swan, represents viveka — the discrimination that separates milk from water, real from unreal.",
    forms: ['Prajapati (Lord of Creatures)', 'Pitamaha (Grandfather of all)', 'Hiranyagarbha (Golden Womb)'],
  },
  {
    id: 'devi', name: 'Devi / Adi Shakti', dev: 'देवी · आदि शक्ति',
    role: 'The Great Mother · Cosmic Feminine · Source of All Energy',
    color: 'from-red-400 to-fuchsia-600',
    consort: 'Shiva (in most traditions)',
    mount: 'Lion or Tiger',
    abode: 'Manidvipa (Island of Jewels)',
    formation: "In the Devi Mahatmya, when the demon Mahishasura could not be defeated by any male deity, the combined tejas (radiant energy) of all the gods emerged as a single luminous form — Durga. She was born from their light: her face from Shiva, her arms from Vishnu, her waist from Indra, her feet from Brahma. Each god also gave her a weapon. She rode out on a lion, defeated Mahishasura in nine days and nights, and revealed that all deities — including the gods themselves — are expressions of the primordial feminine energy (Shakti).",
    decorations: [
      { item: 'Ten (or eighteen) arms', dev: 'दशभुजा', why: 'Each arm holds a weapon given by a different god — she wields their combined power. Ten also corresponds to the ten directions.' },
      { item: 'Red saree', dev: 'रक्तवर्ण', why: 'Red is the color of shakti — of raw creative and destructive energy, of blood, of the muladhara chakra.' },
      { item: 'Gold jewelry', dev: 'स्वर्णाभरण', why: 'Represents the pure, imperishable core of consciousness beneath every form.' },
      { item: 'Third Eye', dev: 'त्रिनेत्र', why: 'Same as Shiva — the eye of wisdom. Devi sees through all illusion.' },
      { item: 'Lotus in hand', dev: 'पद्म', why: 'The lotus rises from mud yet remains untouched — symbol of the awakened soul.' },
    ],
    weapons: [
      { name: 'Trishul (from Shiva)', used_for: 'Piercing the three gunas.' },
      { name: 'Sudarshan Chakra (from Vishnu)', used_for: 'The disc of discriminating wisdom.' },
      { name: 'Vajra (from Indra)', used_for: 'Thunderbolt — instant liberation from ignorance.' },
      { name: 'Bow and arrows (from Vayu)', used_for: 'Directed prana.' },
      { name: 'Sword (from Kala)', used_for: 'Wisdom cutting through time.' },
      { name: 'Conch (from Varuna)', used_for: 'The primordial sound.' },
      { name: 'Lotus (from Brahma)', used_for: 'Pure awareness.' },
      { name: 'Noose (Pasha, from Yama)', used_for: 'Binding ego and drawing souls back to source.' },
      { name: 'Snake (from Shesha)', used_for: 'Kundalini itself.' },
    ],
    body_connections: "Devi is Shakti — the very energy of consciousness. She resides as kundalini coiled at the muladhara. Every chakra is a form of Devi: Dakini (root), Rakini (sacral), Lakini (solar plexus), Kakini (heart), Shakini (throat), Hakini (third eye), Yakini (crown). To awaken kundalini is to invite Devi to travel up the sushumna and unite with Shiva at the sahasrara — the ultimate non-dual realization.",
    forms: ['Durga', 'Kali', 'Lakshmi', 'Saraswati', 'Parvati', 'Chamunda', 'Bhuvaneshwari', 'Tripura Sundari', 'The Ten Mahavidyas'],
  },
  {
    id: 'ganesha', name: 'Ganesha', dev: 'गणेश',
    role: 'Remover of Obstacles · Lord of Beginnings',
    color: 'from-yellow-400 to-orange-600',
    consort: 'Riddhi and Siddhi',
    mount: 'Mushaka (the mouse)',
    abode: 'Beside his parents at Kailash / everywhere invoked at the start of a task',
    formation: "Parvati created Ganesha from the turmeric paste on her body while bathing. She breathed life into him and asked him to guard the door. When Shiva returned and was blocked by this unknown boy, he beheaded him in anger. Seeing Parvati's grief, Shiva sent his ganas to bring the head of the first creature they found — an elephant. He affixed the elephant head to the boy and revived him, declaring: 'This one shall be worshipped before all other gods. No ritual may begin without invoking him.' Thus he became Vinayaka — the leader who is worshipped first.",
    decorations: [
      { item: 'Elephant head', dev: 'गजमुख', why: 'The elephant is the largest land animal and yet the gentlest — represents the union of great power with great wisdom. Also, the head that was cut is the ego; the elephant head is universal consciousness attached to a human body.' },
      { item: 'Broken tusk', dev: 'एकदन्त', why: 'Ganesha broke his own tusk to use as a pen when Vyasa dictated the Mahabharata — signifies willingness to sacrifice the material (tusk of ego) for the eternal (dharma written down).' },
      { item: 'Large ears', dev: 'शूर्पकर्ण', why: 'Fan-like ears that filter — hear everything, retain only what is essential.' },
      { item: 'Large belly', dev: 'लम्बोदर', why: 'Contains the entire universe — every experience, good or bad, digested equally.' },
      { item: 'Modaka in hand', dev: 'मोदक', why: 'The sweet dumpling — the reward of spiritual practice. Sweet on the inside; you must break through the outer shell to taste it.' },
      { item: 'Mouse (mount)', dev: 'मूषक', why: 'Desires nibble away at everything — the mouse of desire, tamed and used as a vehicle, becomes a servant instead of a master.' },
    ],
    weapons: [
      { name: 'Ankusha (goad)', used_for: 'The elephant goad — used to turn the mind from wandering, to direct kundalini.' },
      { name: 'Pasha (noose)', used_for: 'Binds attachment to ego, drawing it back toward center.' },
      { name: 'Broken tusk', used_for: 'A weapon of sacrifice — he threw it at the moon once for laughing at him, teaching that ridicule breeds karma.' },
      { name: 'Axe (Parashu)', used_for: 'Cuts attachments to results — inherited from his father Shiva.' },
    ],
    body_connections: "Ganesha rules the muladhara chakra — the root, where kundalini rests. He is the doorkeeper who must be invoked before the energy can rise. His trunk curved to the left indicates the ida nadi; curved right, the pingala. Om is said to be the visual form of Ganesha — the curves of the letter map to his trunk and belly.",
    forms: ['Vinayaka', 'Ganapati', 'Ekadanta', 'Vakratunda', 'Mahaganapati', 'Ballalesh (child Ganesha)', 'Heramba'],
  },
  {
    id: 'hanuman', name: 'Hanuman', dev: 'हनुमान',
    role: 'God of Devotion · Strength · Selfless Service',
    color: 'from-orange-500 to-red-600',
    consort: 'Brahmacharya (eternal celibacy)',
    mount: 'None — he flies',
    abode: 'Wherever the name of Rama is sung',
    formation: "Hanuman is the son of Anjana and the wind god Vayu, and considered an incarnation of Shiva (as Rudravatara). As a child he mistook the rising sun for a ripe mango and leaped to eat it. Indra struck him with the vajra, breaking his jaw — hence 'Hanuman' (one with a jaw). Vayu withdrew air from the universe in protest, forcing all the gods to restore Hanuman and grant him a boon each. He became invincible, immortal, and could shrink to atom-size or grow mountain-large. In service to Rama during the Ramayana, he crossed the ocean, burned Lanka, and brought the Sanjivani herb — becoming the archetype of bhakti (devotion).",
    decorations: [
      { item: 'Mace (Gada)', dev: 'गदा', why: 'The weapon of ego-shattering discipline. Symbol of tapasya and one-pointed devotion.' },
      { item: 'Red vermillion body', dev: 'सिन्दूर', why: 'Once Hanuman saw Sita applying sindoor for Rama\'s long life. He smeared his entire body — total devotion multiplied.' },
      { item: 'Sacred thread (Janeu)', dev: 'यज्ञोपवीत', why: 'Marks him as a Brahman scholar — he knew all four Vedas and nine Vyakaranas.' },
      { item: 'Ring of Rama in mouth', dev: 'मुद्रिका', why: 'The ring he carried across the ocean to Sita — sign that the seeker\'s task is to carry the Name.' },
      { item: 'Sanjivani mountain', dev: 'सञ्जीवनी पर्वत', why: 'Sometimes shown carrying an entire mountain — when he could not identify the specific herb, he brought the whole mountain. Symbol: when in doubt, offer everything.' },
    ],
    weapons: [
      { name: 'Gada (Mace)', used_for: 'His primary weapon — destroys the ego. Used to shatter demons of Lanka.' },
      { name: 'Fists and tail', used_for: 'Own body used as weapon — he needs no external aid.' },
      { name: 'Ram Naam (the Name of Rama)', used_for: 'His true weapon. Chanting Ram-Ram protected him from all danger.' },
    ],
    body_connections: "Hanuman is associated with prana itself (being son of Vayu). Practitioners of pranayama invoke him. He rules the manipura chakra — solar plexus, seat of will and courage. Hanuman Chalisa recitation is documented to reduce cortisol and increase heart-rate variability — the rhythm literally regulates the vagus nerve.",
    forms: ['Bal Hanuman (child)', 'Panchmukhi Hanuman (five-faced)', 'Sankata Mochan (remover of troubles)', 'Veer Hanuman (warrior)'],
  },
  {
    id: 'kartikeya', name: 'Kartikeya / Murugan / Skanda', dev: 'कार्तिकेय',
    role: 'God of War · Wisdom · Youth · Commander of the Divine Army',
    color: 'from-yellow-500 to-orange-500',
    consort: 'Devasena and Valli',
    mount: 'Mayura (the peacock)',
    abode: 'Shiva\'s heart · Palani, Tiruchendur, Swamimalai (the six abodes of Murugan)',
    formation: "The demon Tarakasura could only be killed by a son of Shiva. But Shiva was in deep meditation after Sati's death. The gods sent Kamadeva to disrupt him — Shiva burned Kamadeva to ash. Eventually Parvati won Shiva as her consort. Their union created sparks of divine energy so intense the earth could not hold them. The Krittikas (six star-nymphs of the Pleiades) nursed the six sparks, and they merged into one six-faced boy — Kartikeya. He led the divine army and slew Tarakasura on his sixth day.",
    decorations: [
      { item: 'Six faces (Shanmukha)', dev: 'षण्मुख', why: 'Sees in all directions simultaneously — no blind spot in awareness. The six faces also represent the six chakras below sahasrara.' },
      { item: 'Twelve arms', dev: 'द्वादशभुज', why: 'Two per face — a full field of action in every direction.' },
      { item: 'Peacock mount', dev: 'मयूर', why: 'The peacock devours snakes — Kartikeya\'s consciousness devours the poisonous ego. The peacock also represents beauty and pride, subdued and made into a vehicle.' },
    ],
    weapons: [
      { name: 'Vel (divine spear)', used_for: 'Given by Parvati — the spear of discriminating wisdom (jnana-shakti) that pierces the ego with one thrust. Killed Tarakasura and Surapadman.' },
      { name: 'Bow and arrows', used_for: 'For warfare — but every arrow is a mantra.' },
      { name: 'Vajra', used_for: 'Inherited from Indra — thunderbolt of instant clarity.' },
    ],
    body_connections: "Kartikeya rules the six chakras below sahasrara — his six faces are literally the six energy centers. His vel piercing the crown chakra of the demon Surapadman is a mythological metaphor for kundalini piercing the sahasrara. Devotees walk the Kavadi with pierced tongues and cheeks — a body practice that redirects pain into devotion.",
    forms: ['Murugan (Tamil Nadu)', 'Skanda', 'Subramanya', 'Kumara', 'Shanmukha', 'Karthik'],
  },
  {
    id: 'kali', name: 'Kali', dev: 'काली',
    role: 'Fierce Mother · Destroyer of Ego · Devourer of Time',
    color: 'from-slate-800 to-red-800',
    consort: 'Shiva',
    mount: 'Shiva (lying beneath her)',
    abode: 'Cremation grounds, tantric shrines, Kalighat',
    formation: "When Durga faced the demon Raktabija — whose every drop of blood spawned another demon — she could not win. In her extreme rage, from her forehead sprang Kali: black as void, tongue lolling, garlanded with skulls. Kali drank every drop of Raktabija's blood before it could touch the earth, and consumed every clone. Drunk on victory, she began to dance and threatened to shatter the universe. Shiva lay down in her path — when her foot touched him, she stuck out her tongue in shock (the classic pose) and stopped. Consciousness (Shiva) tames energy (Kali) with pure surrender.",
    decorations: [
      { item: 'Black skin', dev: 'कृष्णवर्णा', why: 'Black contains all colors — Kali is the primordial darkness before any light. She is Kaal (time), and time appears black because it consumes everything.' },
      { item: 'Garland of 51 skulls (or 50)', dev: 'मुण्डमाला', why: 'Represents the 50 letters of the Sanskrit alphabet — Kali contains all language, all thought, all sound. Also: severed heads = severed egos of her devotees.' },
      { item: 'Belt of severed arms', dev: 'भुजमाला', why: 'The arms represent karma — every action bound to consequence. Kali severs karma itself.' },
      { item: 'Tongue out', dev: 'ललजिह्वा', why: 'Shock at treading on Shiva — but also: the tongue of primordial hunger, of Vak (divine speech), of Kundalini rising.' },
      { item: 'Nakedness', dev: 'दिगम्बरा', why: 'Digambara — clothed in the directions. She is beyond all disguise, all social convention.' },
    ],
    weapons: [
      { name: 'Kharga (curved sword)', used_for: 'Cuts through the roots of ego with one blow. The blade is knowledge (vidya).' },
      { name: 'Trishul', used_for: 'Same three gunas — destroyed simultaneously.' },
      { name: 'Severed head (in hand)', used_for: 'Not a weapon — a trophy. The dead ego of her devotees, offered to her willingly.' },
      { name: 'Bowl of blood', used_for: 'Held in another hand — she drinks the blood of Raktabija before it can breed more demons.' },
    ],
    body_connections: "Kali is the raw kundalini shakti when it moves — untamed, unstoppable. She rules the muladhara during awakening. Devotees of Kali (like Ramakrishna) describe her as the direct experience of the mother behind all phenomena. She is what remains when every concept of God has been destroyed.",
    forms: ['Dakshina Kali (right-footed, benevolent)', 'Bhadrakali', 'Shmashan Kali (cremation ground)', 'Mahakali'],
  },
  {
    id: 'durga', name: 'Durga', dev: 'दुर्गा',
    role: 'The Invincible Mother · Slayer of Mahishasura',
    color: 'from-red-400 to-yellow-500',
    consort: 'Shiva (as Parvati form)',
    mount: 'Lion (or tiger)',
    abode: 'Mount Vindhya · everywhere she is invoked',
    formation: "Same origin as Devi (see above) — born from the combined tejas of all the gods to slay Mahishasura, the buffalo demon that no male deity could defeat. Her nine forms are worshipped over the nine nights of Navaratri.",
    decorations: [
      { item: 'Ten arms', dev: 'दशभुजा', why: 'Each holds a weapon from a different god — her power is the collected power of the cosmos.' },
      { item: 'Red saree', dev: 'रक्ताम्बरा', why: 'Color of raw shakti and dharmic fury.' },
      { item: 'Lion mount', dev: 'सिंहवाहिनी', why: 'She rides the very energy she has mastered — courage subdued and ridden.' },
      { item: 'Foot on Mahisha', dev: 'महिषासुरमर्दिनी', why: 'Iconography always shows her spear piercing the buffalo demon\'s neck — dharma always wins over the animal ego.' },
    ],
    weapons: [
      { name: 'All the divine weapons — see Devi', used_for: 'Trishul, chakra, sword, bow, mace, conch, lotus, noose, thunderbolt.' },
    ],
    body_connections: "Durga rules the manipura chakra — the solar plexus, seat of dharmic courage. Her nine forms (Navadurga) map onto the nine planets (Navagraha) and the nine gates of the body.",
    forms: ['Shailaputri', 'Brahmacharini', 'Chandraghanta', 'Kushmanda', 'Skandamata', 'Katyayani', 'Kalaratri', 'Mahagauri', 'Siddhidatri (the nine forms)'],
  },
  {
    id: 'lakshmi', name: 'Lakshmi', dev: 'लक्ष्मी',
    role: 'Goddess of Wealth · Prosperity · Fortune · Beauty',
    color: 'from-pink-400 to-yellow-500',
    consort: 'Vishnu',
    mount: 'Owl (Uluka)',
    abode: 'Vaikuntha (with Vishnu)',
    formation: "During the churning of the ocean of milk (Samudra Manthan), fourteen treasures emerged. Lakshmi rose from the churned waters, seated on a lotus, holding lotuses. She looked at all the gods and demons and chose Vishnu as her consort — dharma. Wealth follows dharma, not the other way around.",
    decorations: [
      { item: 'Four hands', dev: 'चतुर्भुजा', why: 'Symbolize the four goals of life — dharma, artha, kama, moksha. She grants all four.' },
      { item: 'Lotuses', dev: 'पद्म', why: 'Lotus rises pure from muddy water — wealth honestly earned rises from struggle.' },
      { item: 'Gold coins pouring', dev: 'हिरण्य वृष्टि', why: 'From her right hand — but only where dharma dwells.' },
      { item: 'Two elephants beside her', dev: 'गजलक्ष्मी', why: 'Symbols of royal power and rainfall (prosperity).' },
      { item: 'Red or golden saree', dev: 'पीताम्बरा', why: 'Red — passion of creation. Gold — imperishable.' },
    ],
    weapons: [
      { name: 'She holds no weapon', used_for: 'Lakshmi never fights. When adharma dominates, she simply leaves — the greatest punishment is her absence.' },
    ],
    body_connections: "Lakshmi is associated with the ida nadi and the moon — she governs the cool, receptive, nurturing side of energy. She is the shakti of Vishnu — his sustaining power. Her mount, the owl, sees in darkness — wealth wisely used sees where others are blind.",
    forms: ['Ashtalakshmi (eight forms — for wealth, grain, courage, victory, progeny, wisdom, food, and royal fortune)', 'Gaja-Lakshmi', 'Dhana-Lakshmi', 'Dhanya-Lakshmi'],
  },
  {
    id: 'saraswati', name: 'Saraswati', dev: 'सरस्वती',
    role: 'Goddess of Knowledge · Music · Arts · Speech · Wisdom',
    color: 'from-white to-blue-400',
    consort: 'Brahma',
    mount: 'Hamsa (swan) or peacock',
    abode: 'On the tongue of every sincere student',
    formation: "Saraswati emerged from Brahma's mouth as pure Vak (speech). When Brahma looked at his own creation and felt lonely, she manifested from within him — a river of pure knowledge. She is older than the Vedas, for she is what makes them speakable. Also present as the sacred river Saraswati that once flowed alongside the Indus (recent geological evidence supports its existence, now buried).",
    decorations: [
      { item: 'White saree', dev: 'श्वेताम्बरा', why: 'White = pure sattva. Knowledge untainted by ego or desire.' },
      { item: 'Veena (stringed instrument)', dev: 'वीणा', why: 'The seven strings correspond to the seven notes and seven chakras. Music tunes consciousness.' },
      { item: 'Book (Pustaka)', dev: 'पुस्तक', why: 'The Vedas in her hand — she is the embodiment of the eternal knowledge.' },
      { item: 'Mala', dev: 'माला', why: 'Meditation counted — knowledge without meditation is dead information.' },
      { item: 'Swan mount', dev: 'हंसवाहिनी', why: 'The hamsa can separate milk from water — the sign of viveka (discrimination).' },
    ],
    weapons: [
      { name: 'She holds no weapon', used_for: 'Her only "weapon" is Vak — speech that removes ignorance. The most powerful force there is.' },
    ],
    body_connections: "Saraswati rules the vishuddha (throat) chakra — the seat of speech and expression. Reciting Saraswati mantras before study is scientifically shown to improve retention through calming pre-frontal cortex. Her river is the sushumna nadi itself — the central channel of consciousness.",
    forms: ['Sharada', 'Vagishwari', 'Mahasaraswati', 'Bharati'],
  },
  {
    id: 'surya', name: 'Surya', dev: 'सूर्य',
    role: 'The Sun God · Source of Life · Cosmic Light',
    color: 'from-yellow-300 to-orange-600',
    consort: 'Sanjna and Chhaya',
    mount: 'Chariot drawn by seven horses',
    abode: 'The Sun itself',
    formation: "Surya is the visible face of the invisible Brahman. In the Vedas, he is called Savitri (the impeller) — the source of all life on Earth. His seven horses represent the seven colors of visible light (long before Newton's prism, the Rig Veda described his rays as sapta-ashva, seven horses). His son is Yama (death) — sun and death both children of light. He also fathered Manu (humanity's ancestor) and Karna (of the Mahabharata).",
    decorations: [
      { item: 'Golden chariot', dev: 'रथ', why: 'Represents the daily cycle — the sun\'s chariot rides across the sky each day.' },
      { item: 'Seven horses', dev: 'सप्ताश्व', why: 'Seven horses = seven colors of visible spectrum. Explicitly named in Rig Veda long before scientific optics.' },
      { item: 'Aruna (charioteer)', dev: 'अरुण', why: 'Aruna means "dawn" — legless (dawn has no legs, it simply appears). He drives the chariot of light.' },
      { item: 'Two lotuses', dev: 'द्विकर पद्म', why: 'Sun is what makes lotuses open — he holds them to remind us he is behind all growth.' },
      { item: 'Golden crown', dev: 'स्वर्णकिरीट', why: 'Corona — the sun\'s crown of plasma, visible during eclipse.' },
    ],
    weapons: [
      { name: 'Rays (Sahasrarashmi)', used_for: 'Thousand-rayed. His rays destroy darkness. Surya Namaskar sequence maps 12 postures to the 12 zodiac positions of the sun through the year.' },
    ],
    body_connections: "Surya rules the anahata chakra (heart) via the sun's role in the surya-nadi (right side, active, pingala). Sungazing at safe hours (early morning, late evening) increases serotonin and vitamin D. Surya Namaskar performed daily activates all major muscle groups and glandular systems. He is also connected to the ajna — the third eye is called the 'sun of the mind'.",
    forms: ['Aditya (twelve monthly forms)', 'Savitri', 'Bhaskara', 'Ravi', 'Martanda', 'Konark Sun (temple deity)'],
  },
];

export const AVATARS = {
  intro: "An avatar (अवतार, 'descent') is a deliberate incarnation of a deity into a physical form. Vishnu's ten avatars (Dashavatara) are the most famous, but Shiva has 19 major avatars and the Devi has innumerable forms. Each descent corresponds to a specific crisis of dharma in a specific era.",
  vishnu_avatars: [
    { n: 1, name: 'Matsya', dev: 'मत्स्य', form: 'The Fish', era: 'Krita Yuga · pre-history',
      color: 'from-blue-400 to-cyan-600',
      why: 'A great deluge threatened to erase all life. Vishnu took the form of a fish, warned King Manu, and instructed him to build a boat. Matsya guided the boat safely through the flood with a rope tied to his horn.',
      symbolism: 'Life first appeared in water — the fish avatar mirrors evolution. Matsya represents preservation of the seed of dharma through catastrophe.',
      weapons: 'Horn used to tow the ark.' },
    { n: 2, name: 'Kurma', dev: 'कूर्म', form: 'The Tortoise', era: 'Krita Yuga',
      color: 'from-emerald-400 to-teal-600',
      why: 'During the churning of the ocean of milk, the mountain Mandara used as a churning rod began to sink. Kurma dove beneath and held it up on his back so the churning could continue and Amrita (nectar of immortality) could emerge.',
      symbolism: 'Amphibious — the next step of evolution. Also: the strong, silent support beneath every great creation.',
      weapons: 'His shell — bore the entire universe.' },
    { n: 3, name: 'Varaha', dev: 'वराह', form: 'The Boar', era: 'Krita Yuga',
      color: 'from-orange-400 to-red-600',
      why: 'The demon Hiranyaksha dragged the Earth (Bhudevi) to the bottom of the cosmic ocean. Vishnu took a boar form, dove into the depths, killed the demon, and lifted Earth on his tusks.',
      symbolism: 'Land mammal — evolution continues. The boar\'s tusks lifting earth also symbolize consciousness lifting matter into meaning.',
      weapons: 'Tusks, chakra, mace.' },
    { n: 4, name: 'Narasimha', dev: 'नरसिंह', form: 'Man-Lion', era: 'Satya Yuga',
      color: 'from-yellow-500 to-red-700',
      why: 'The demon Hiranyakashipu was granted a boon: he could not be killed by man or beast, indoors or outdoors, day or night, on earth or in sky, by weapon animate or inanimate. His son Prahlada refused to stop worshipping Vishnu. To protect Prahlada, Vishnu emerged from a pillar at twilight (neither day nor night), in the form of half-man half-lion (neither man nor beast), on the threshold (neither indoors nor outdoors), placed Hiranyakashipu on his lap (neither earth nor sky), and used his claws (neither weapon animate nor inanimate).',
      symbolism: 'When rules become obstacles to dharma, dharma finds creative solutions. Also: transitional evolutionary form — half-animal, half-human.',
      weapons: 'Claws — no manufactured weapon needed.' },
    { n: 5, name: 'Vamana', dev: 'वामन', form: 'The Dwarf Brahmin', era: 'Treta Yuga',
      color: 'from-amber-400 to-yellow-600',
      why: 'The demon-king Bali conquered all three worlds. Vishnu appeared as a dwarf brahmin and asked for three paces of land. When granted, he grew to cosmic size — one step covered the earth, one step the heavens. Bali offered his own head for the third step.',
      symbolism: 'Ego is subdued by conscious surrender, not violence. The tiniest sincere request contains cosmic power.',
      weapons: 'Umbrella and water pot — no weapon; only humility.' },
    { n: 6, name: 'Parashurama', dev: 'परशुराम', form: 'Warrior-Sage with an Axe', era: 'Treta Yuga',
      color: 'from-red-500 to-orange-700',
      why: 'The kshatriya (warrior) caste had become tyrannical and killed his father Jamadagni. Parashurama, a brahmin, took up an axe and destroyed twenty-one generations of corrupt kshatriyas — restoring dharma. Believed to be immortal, still meditating in the mountains.',
      symbolism: 'When a class becomes corrupt, dharma acts through unexpected instruments. The first hybrid avatar — brahmin by birth, warrior by need.',
      weapons: 'Parashu — a divine axe given by Shiva.' },
    { n: 7, name: 'Rama', dev: 'राम', form: 'The Ideal King', era: 'Treta Yuga',
      color: 'from-green-400 to-emerald-700',
      why: 'The demon-king Ravana had captured Sita and tyrannized dharma. Rama, born to King Dasharatha of Ayodhya, was exiled for 14 years, defeated Ravana with an army of vanaras (including Hanuman), rescued Sita, and restored dharmic rule (Ram Rajya). His story is the Ramayana.',
      symbolism: 'The perfect embodiment of dharma — as son, husband, king, brother. Maryada Purushottama, "the ideal within all limits."',
      weapons: 'Sharanga bow, Brahmastra (divine arrow of last resort).' },
    { n: 8, name: 'Krishna', dev: 'कृष्ण', form: 'The Divine Statesman · Cowherd · Lover · Teacher', era: 'Dwapara Yuga',
      color: 'from-blue-500 to-indigo-700',
      why: 'The demon Kamsa oppressed the earth. Krishna was born in prison, saved by his father Vasudeva who crossed the flooded Yamuna at midnight. He grew up among cowherds, slew Kamsa as a youth, and later became the strategic mind behind the Pandavas in the Mahabharata war. On the battlefield he delivered the Bhagavad Gita to Arjuna.',
      symbolism: 'The full-spectrum avatar — mystic, warrior, lover, statesman, teacher, prankster. Represents the divine embracing every human role.',
      weapons: 'Sudarshan Chakra (spinning disc), Panchajanya (conch), Kaumodaki (mace), Sharanga (bow), Nandaka (sword). But his true weapon: dharma-yukta buddhi — reasoning aligned with dharma.' },
    { n: 9, name: 'Buddha', dev: 'बुद्ध', form: 'The Awakened One', era: 'Kali Yuga · c. 6th century BCE',
      color: 'from-yellow-300 to-orange-500',
      why: 'Rituals had become empty and violent. Vishnu incarnated as Siddhartha Gautama to teach non-violence, the middle path, and the direct investigation of suffering.',
      symbolism: 'The avatar of the intellect turning inward — no more heroism, only awareness. Included in the Dashavatara list by most Hindu traditions (some substitute Balarama).',
      weapons: 'None — the sword of prajna (wisdom) that cuts ignorance.' },
    { n: 10, name: 'Kalki', dev: 'कल्कि', form: 'The Prophesied Horseman', era: 'End of Kali Yuga · future',
      color: 'from-white to-slate-400',
      why: 'Yet to come. At the end of the Kali Yuga, when dharma is nearly extinguished, Vishnu will incarnate as Kalki — a warrior on a white horse, wielding a comet-like sword. He will destroy corruption and begin the next Krita Yuga.',
      symbolism: 'Both apocalyptic and hopeful — every dark age contains the seed of the next golden age. Modern parallels: environmental collapse, AI, potential rebirth.',
      weapons: 'Fiery sword; the white horse itself is the incarnation of speed and dharma.' },
  ],
  shiva_avatars: [
    { name: 'Adiyogi', dev: 'आदियोगी', about: 'The first yogi. Shiva as the transmitter of yoga to the Saptarishi (seven sages) at Kanti Sarovar in the Himalayas. Origin of all yoga.', color: 'from-blue-400 to-indigo-700' },
    { name: 'Dakshinamurti', dev: 'दक्षिणामूर्ति', about: 'Shiva as silent teacher facing south, seated under a banyan tree. Teaches without speaking — the four elderly rishis before him understand instantly through jnana-mudra.', color: 'from-amber-400 to-orange-600' },
    { name: 'Nataraja', dev: 'नटराज', about: 'The Cosmic Dancer. In the Ananda Tandava he dances creation, preservation, destruction, veiling, and grace simultaneously. The physicist Fritjof Capra called his dance "a metaphor for the dance of subatomic particles."', color: 'from-orange-400 to-red-600' },
    { name: 'Bhairava', dev: 'भैरव', about: 'The terrifying form. Emerged when Shiva\'s wrath became visible. Guardian of the sanctum. Also the protector-form of Kashi (Varanasi).', color: 'from-slate-700 to-purple-800' },
    { name: 'Hanuman', dev: 'हनुमान', about: 'Considered an avatar of Shiva (Rudravatara) — the eleventh Rudra born as Vayu\'s son.', color: 'from-orange-500 to-red-600' },
    { name: 'Ardhanarishvara', dev: 'अर्धनारीश्वर', about: 'Half-male, half-female. Shiva and Shakti fused in one body — the ultimate teaching of non-duality.', color: 'from-fuchsia-400 to-cyan-500' },
    { name: 'Sharabha', dev: 'शरभ', about: 'A part-lion, part-bird form Shiva took to calm Narasimha (Vishnu\'s form) whose rage would not subside even after slaying Hiranyakashipu.', color: 'from-slate-500 to-red-700' },
  ],
  devi_avatars: [
    { name: 'Sati', dev: 'सती', about: 'First wife of Shiva. Self-immolated at her father Daksha\'s yajna after he insulted Shiva. Shiva\'s grief led to the tandava; her body-parts fell across India, forming the 51 Shakti Peethas.', color: 'from-pink-500 to-red-600' },
    { name: 'Parvati', dev: 'पार्वती', about: 'Sati reborn as daughter of the mountains. Through immense tapas, she won Shiva again — the archetype of persistent devotion.', color: 'from-emerald-400 to-teal-600' },
    { name: 'Durga', dev: 'दुर्गा', about: 'Slayer of Mahishasura. See above.', color: 'from-red-400 to-yellow-500' },
    { name: 'Kali', dev: 'काली', about: 'Fierce form from Durga\'s brow. See above.', color: 'from-slate-800 to-red-800' },
    { name: 'Lakshmi', dev: 'लक्ष्मी', about: 'Consort of Vishnu; goddess of wealth. Emerged from ocean-churning.', color: 'from-pink-400 to-yellow-500' },
    { name: 'Saraswati', dev: 'सरस्वती', about: 'Consort of Brahma; goddess of wisdom.', color: 'from-white to-blue-400' },
    { name: 'The Ten Mahavidyas', dev: 'दश महाविद्या', about: 'Ten great tantric goddesses: Kali, Tara, Tripura Sundari, Bhuvaneshwari, Bhairavi, Chinnamasta, Dhumavati, Bagalamukhi, Matangi, Kamala. Each represents a specific aspect of ultimate reality and unlocks a specific siddhi.', color: 'from-purple-500 to-fuchsia-700' },
  ],
  why_incarnate: "The Bhagavad Gita (4.7-8) states it clearly: 'Yada yada hi dharmasya glanir bhavati Bharata / Abhyuthanam adharmasya tadatmanam srijamyaham / Paritranaya sadhunam vinashaya cha dushkritam / Dharmasamsthapanarthaya sambhavami yuge yuge' — 'Whenever dharma declines and adharma rises, I embody myself. To protect the good, to destroy the wicked, to re-establish dharma — I appear age after age.' The avatars mark cosmological interventions at specific historical crises.",
};
