// Life Coach, Yajna, Universe Explorer

export const COACH_DOMAINS = [
  { id: 'career', name: 'Career', color: 'from-cyan-400 to-blue-600', icon: 'Briefcase',
    tagline: 'Meaningful work, not just a job.',
    prompt: 'You are an AI life coach specializing in career. Balance modern career advice (skills, network, positioning) with wisdom on swadharma (unique calling) and karma yoga (work as offering). Ask what stage they are in. Give one practical next step. Warm but direct.' },
  { id: 'stress', name: 'Stress', color: 'from-fuchsia-400 to-purple-600', icon: 'Zap',
    tagline: 'The nervous system, retrainable.',
    prompt: 'You are an AI life coach specializing in stress. Combine polyvagal theory, breathwork, sleep science, and yogic pranayama. Prescribe a specific 3-5 minute practice they can do today. Kind, not preachy.' },
  { id: 'relationships', name: 'Relationships', color: 'from-pink-400 to-rose-500', icon: 'Heart',
    tagline: 'The hardest sadhana, the deepest fruit.',
    prompt: 'You are an AI life coach specializing in relationships. Combine attachment theory, non-violent communication, and traditional wisdom (Metta, forgiveness, Bhagavad Gita on duty). Ask about the specific dynamic. Suggest one practice or conversation.' },
  { id: 'purpose', name: 'Purpose', color: 'from-amber-400 to-orange-500', icon: 'Compass',
    tagline: 'Not one lightning bolt \u2014 a compass.',
    prompt: 'You are an AI life coach specializing in life purpose. Draw on Frankl, ikigai, dharma. Help them locate the intersection of what they love, are good at, and the world needs. Suggest one small experiment.' },
  { id: 'productivity', name: 'Productivity', color: 'from-emerald-400 to-teal-500', icon: 'Zap',
    tagline: 'Deep work, not more work.',
    prompt: 'You are an AI life coach specializing in productivity. Blend Cal Newport / Deep Work, ancient concentration practice (dharana), and honest energy management. Avoid hustle culture. Ask what they truly want to build. Suggest one system change.' },
  { id: 'habits', name: 'Habits', color: 'from-yellow-400 to-amber-500', icon: 'RefreshCw',
    tagline: 'You are your systems, not your intentions.',
    prompt: 'You are an AI life coach specializing in habit change. Combine BJ Fogg tiny habits, James Clear atomic habits, and yogic sadhana (40-day discipline). Ask the specific habit. Prescribe cue, action, reward and identity language.' },
  { id: 'health', name: 'Health', color: 'from-red-400 to-pink-500', icon: 'Activity',
    tagline: 'The body is the temple.',
    prompt: 'You are an AI life coach specializing in health. Blend evidence-based lifestyle medicine (Blue Zones, sleep science, movement, nutrition) with Ayurvedic dinacharya. NOT medical advice. Ask about their goal, suggest one small daily anchor.' },
  { id: 'learning', name: 'Learning', color: 'from-indigo-400 to-purple-500', icon: 'BookOpen',
    tagline: 'The mind is a muscle.',
    prompt: 'You are an AI life coach specializing in learning. Use Anders Ericsson deliberate practice, Barbara Oakley learning-how-to-learn, and yogic svadhyaya (self-study). Ask what they want to master. Suggest a structure.' },
];

export const YAJNA = {
  name: 'Yajna & Homa',
  subtitle: 'The fire ritual \u2014 offering as science, worship as chemistry',
  intro: "Yajna (from yaj \u2014 'to worship') is the oldest recorded organized practice on the planet, described in the Rig Veda. Fire (Agni) is invoked as messenger between the human and the cosmic. Modern research on homa smoke shows measurable antibacterial, antifungal, and air-purifying effects \u2014 confirming what the tradition always claimed. But its deeper purpose is inner: everything is offered, nothing is kept.",
  types: [
    { name: 'Agnihotra', desc: 'A short daily fire ritual performed exactly at sunrise and sunset. Two mantras, cow-dung fire, ghee, and rice. Perhaps the smallest complete yajna.' },
    { name: 'Homa', desc: 'A general fire ritual, tailored to a deity or intention. Ganapati Homa, Sudarshana Homa, Chandi Homa, Navagraha Homa, etc.' },
    { name: 'Havan', desc: 'A larger fire ritual, often for community occasions (naming, weddings, house-warming).' },
    { name: 'Yajna (great)', desc: 'The largest scale \u2014 multi-day, multi-priest rituals like Ashwamedha or Athirathram. Rare today.' },
    { name: 'Antaryaga', desc: '"Inner yajna" \u2014 the tradition\'s recognition that the outer fire is a metaphor. The true offering is the ego into the fire of awareness.' },
  ],
  procedure: [
    'Prepare a kunda (fire pit \u2014 traditionally copper or brick, geometrical).',
    'Gather: dry cow-dung cakes (or clean firewood), ghee, rice, samagri (herb mix \u2014 typically ~9 herbs including sandalwood).',
    'Sit facing east. Cover the head if traditional.',
    'Sankalpa: state the day, place, and intention aloud.',
    'Achamana + Pranayama: three sips of water, three cycles of breath.',
    'Ganapati invocation \u2014 remove obstacles.',
    'Light the fire with sacred materials. Invoke Agni with Agni Sukta.',
    'Offer ghee and samagri with each mantra, saying \u201CSvaha\u201D on each offering. Standard mantras: Gayatri, chosen deity mantra, or specific homa mantra.',
    'Aarti and prasada at the end. Fire is not put out with water \u2014 it burns down naturally.',
  ],
  science: [
    'Homa smoke tested at BARC (Bhabha Atomic Research Centre) shows significant reduction in airborne bacterial counts.',
    'Combustion of ghee + rice + specific herbs releases sesquiterpenes, phenols, and antioxidant volatile compounds.',
    'Practitioners often note observable calming effect on the nervous system \u2014 likely combined effect of firelight, mantra rhythm, and breath.',
    'Some claimed effects (weather modification, subtle-body cleansing) remain traditional \u2014 not scientifically established.',
  ],
  benefits: [
    'Grounding daily anchor \u2014 fire, mantra, breath in coordination.',
    'Purifies indoor air (well-supported for antimicrobial effect).',
    'Group cohesion when done as family or community.',
    'Trains attention through a coordinated multi-sensory ritual.',
    'Ultimately points to antaryaga \u2014 the inner offering of ego into awareness.',
  ],
};

export const UNIVERSE_SCALES = [
  { power: -35, unit: 'Planck length', desc: 'The smallest theoretically meaningful length. Below this, spacetime as we know it breaks down. 10\u207B\u00b3\u2075 meters.', color: 'from-slate-400 to-purple-500' },
  { power: -18, unit: 'Quarks', desc: 'The building blocks of protons and neutrons. Never observed alone.', color: 'from-purple-400 to-fuchsia-500' },
  { power: -15, unit: 'Atomic nucleus', desc: 'Where 99.9% of an atom\'s mass sits, in a space 10,000\u00d7 smaller than the atom itself. Mostly empty.', color: 'from-fuchsia-400 to-pink-500' },
  { power: -10, unit: 'Hydrogen atom', desc: 'The simplest atom \u2014 one proton, one electron. The material out of which almost everything else is built.', color: 'from-pink-400 to-rose-500' },
  { power: -9, unit: 'DNA helix', desc: '~2 nm wide. Your entire genome would stretch 6 feet if unrolled from a single cell.', color: 'from-rose-400 to-red-500' },
  { power: -6, unit: 'Red blood cell', desc: 'You have ~25 trillion, and make 2 million new ones every second.', color: 'from-red-400 to-orange-500' },
  { power: 0, unit: 'You', desc: 'A 1.7m-tall configuration of ~7 octillion atoms, most of which are hydrogen or oxygen \u2014 rearranged briefly into a form that asks itself what it is.', color: 'from-amber-400 to-yellow-500' },
  { power: 3, unit: 'Skyscraper (~1 km)', desc: 'About the tallest structures humans have built.', color: 'from-yellow-400 to-emerald-500' },
  { power: 6, unit: 'Earth\'s radius', desc: '6,371 km. A blue-green marble roughly this wide has held all human history.', color: 'from-emerald-400 to-teal-500' },
  { power: 8, unit: 'Earth-Moon distance', desc: '384,400 km. About 30 Earth-diameters. Sunlight bounces here in 1.3 seconds.', color: 'from-teal-400 to-cyan-500' },
  { power: 11, unit: 'Earth-Sun distance (AU)', desc: '150 million km. Light takes 8 minutes and 20 seconds to reach us. Everything you see from the sun is 8 min old.', color: 'from-cyan-400 to-blue-500' },
  { power: 12, unit: 'Sun\'s diameter', desc: 'About 1.4 million km. You could fit 1.3 million Earths inside.', color: 'from-blue-400 to-indigo-500' },
  { power: 13, unit: 'Solar system radius', desc: 'Out to Neptune. Beyond, in a vast dark ring, sits the Kuiper Belt and eventually the Oort Cloud.', color: 'from-indigo-400 to-purple-500' },
  { power: 16, unit: 'Nearest star (Proxima Centauri)', desc: '4.24 light-years. If Earth were a marble in New York, Proxima would be a marble in Tokyo.', color: 'from-purple-400 to-fuchsia-500' },
  { power: 20, unit: 'Milky Way diameter', desc: '~100,000 light-years across. Contains ~200 billion stars, and unnumbered planets.', color: 'from-fuchsia-400 to-pink-500' },
  { power: 22, unit: 'Local Group', desc: 'The Milky Way + Andromeda + ~80 smaller galaxies. Bound to each other by gravity.', color: 'from-pink-400 to-rose-500' },
  { power: 24, unit: 'Observable universe (~93 billion ly)', desc: 'The sphere from which light has had time to reach us since the Big Bang.', color: 'from-rose-400 to-orange-500' },
  { power: 26, unit: 'Universe (unknown extent)', desc: 'The whole thing may be much larger \u2014 possibly infinite. We literally cannot see beyond our horizon.', color: 'from-orange-400 to-yellow-500' },
];
