// Rituals: Poojas, Aartis, Homas, and worship implements
// Extends existing PUJA_VIDHANAM (16 steps) and YAJNA content

export const POOJA_STEPS = {
  intro: "The Shodashopachara Pooja (षोडशोपचार पूजा) — the 'sixteen-step worship' — is the classical, complete form of Hindu devotional ritual. Each step (upachara) is what a gracious host would offer an honored guest arriving at their home. Worship is treating the divine as the ultimate guest.",
  dev: 'षोडशोपचार पूजा',
  color: 'from-amber-400 to-orange-600',
  steps: [
    { n: 1, name: 'Avahana', dev: 'आवाहन', english: 'Invocation', desc: 'Invite the deity to enter the murti (image) or the puja space. Recited: "Please come, take your seat here." A conscious act of welcoming.' },
    { n: 2, name: 'Asana', dev: 'आसन', english: 'Offering a seat', desc: 'Present a flower or a small mat as a seat. The deity is now seated as your guest.' },
    { n: 3, name: 'Padya', dev: 'पाद्य', english: 'Washing the feet', desc: 'Water is offered to wash the deity\'s feet. A guest who has traveled deserves foot-washing. Sprinkled with tulsi or bilva leaf.' },
    { n: 4, name: 'Arghya', dev: 'अर्घ्य', english: 'Water for the hands', desc: 'A small conch or vessel of scented water is offered for the deity to wash their hands.' },
    { n: 5, name: 'Achamana', dev: 'आचमन', english: 'Sipping water', desc: 'Water is offered for the deity to sip — a ritual of purification traditionally done before every sacred act.' },
    { n: 6, name: 'Snana', dev: 'स्नान', english: 'The bath', desc: 'The deity is bathed with water — and often panchamrita (milk, curd, honey, ghee, sugar) followed by pure water. This is Abhisheka. For Shiva, the abhishekam is central.' },
    { n: 7, name: 'Vastra', dev: 'वस्त्र', english: 'Clothing', desc: 'Fresh cloth or thread is offered. The deity is dressed. The murti is often draped in silk.' },
    { n: 8, name: 'Yajnopavita', dev: 'यज्ञोपवीत', english: 'Sacred thread', desc: 'For male deities, the sacred thread (janeu) is offered.' },
    { n: 9, name: 'Gandha', dev: 'गन्ध', english: 'Perfume / sandalwood paste', desc: 'Sandalwood paste (chandan), kumkum (vermillion), and haldi (turmeric) are applied to the deity\'s forehead — the same tilak we wear.' },
    { n: 10, name: 'Pushpa', dev: 'पुष्प', english: 'Flowers', desc: 'Flowers are offered — each deity has favorites. Shiva: bilva, dhattura. Vishnu: tulsi, lotus. Devi: red hibiscus. Ganesha: durva grass.' },
    { n: 11, name: 'Dhupa', dev: 'धूप', english: 'Incense', desc: 'Incense is lit and waved before the deity — the smoke represents the transformation of matter into fragrant offering.' },
    { n: 12, name: 'Dipa', dev: 'दीप', english: 'Lamp', desc: 'An oil lamp (usually ghee) is offered and circled before the deity. Light — the removal of ignorance.' },
    { n: 13, name: 'Naivedya', dev: 'नैवेद्य', english: 'Food offering', desc: 'Cooked food is offered — often fruit, sweets, and a full meal (annakuta). After offering, it becomes prasada (grace) and is shared.' },
    { n: 14, name: 'Tambula', dev: 'ताम्बूल', english: 'Betel leaf & areca nut', desc: 'Offered after the meal as digestive and traditional refreshment — as one would offer a guest.' },
    { n: 15, name: 'Namaskara / Pradakshina', dev: 'नमस्कार · प्रदक्षिणा', english: 'Prostration & circumambulation', desc: 'Bow before the deity and circle the murti clockwise (usually 3 or 7 times). The devotee is now in the field of the deity.' },
    { n: 16, name: 'Visarjana', dev: 'विसर्जन', english: 'Farewell', desc: 'The deity is thanked and formally released from the murti — "Please return to your own abode." A reminder: the divine is not confined to any object.' },
  ],
  simple_version: "For daily home worship a shorter Panchopachara (5-step) or Dashopachara (10-step) version is common: light lamp → sandalwood → flowers → incense → food. Even a single sincere offering with mantra is complete pooja.",
};

export const POOJAS = {
  intro: "Puja (पूजा) is the ceremonial worship of the divine. It has infinite forms — from a single lit lamp before a household shrine to elaborate multi-day yajnas requiring dozens of priests. Every pooja has a purpose: some are performed daily to sustain dharma, some at specific times, some to fulfill desires, some purely as devotion. Here are the most important poojas across Hindu practice.",
  dev: 'पूजा विधान',
  color: 'from-orange-400 to-red-600',
  types: [
    { name: 'Nitya', dev: 'नित्य', desc: 'Daily poojas performed as a matter of dharma — no special reason, done every day. Example: Sandhya vandana, morning household worship.' },
    { name: 'Naimittika', dev: 'नैमित्तिक', desc: 'Occasional — performed at specific times or on specific occasions. Example: Ekadashi vrata, Navaratri poojas, eclipse rituals.' },
    { name: 'Kamya', dev: 'काम्य', desc: 'Desire-based — performed with a specific outcome in mind. Example: Lakshmi puja for prosperity, Navagraha puja for planetary healing.' },
    { name: 'Nishiddha', dev: 'निषिद्ध', desc: 'Prohibited — poojas that are done improperly, with anger or wrong intent, are considered nishiddha and generate demerit (papa).' },
  ],
  major: [
    {
      id: 'ganesha-puja', name: 'Ganesha Pooja', dev: 'गणेश पूजा',
      color: 'from-yellow-400 to-orange-600',
      deity: 'Ganesha (Vinayaka)',
      when: 'Before any new venture, at the start of every other pooja, daily, or during Ganesh Chaturthi (Aug-Sep).',
      purpose: 'To remove obstacles from any undertaking. Ganesha is worshipped first — before every other deity — so his blessing is called Prathama-Pujya (first-worshipped).',
      essentials: '21 durva grass sprigs, red hibiscus flowers, modaka sweets, red kumkum, sandalwood, coconut, banana, small clay idol (visarjan variant).',
      mantras: ['Om Gam Ganapataye Namaha', 'Vakratunda mahakaya suryakoti samaprabha / Nirvighnam kuru me deva sarva karyeshu sarvada'],
      steps: 'Sankalpa (statement of intent) → Kalash sthapana → Ganesha avahana → 16 upacharas → 21 durva offering → Modaka naivedya → Aarti → Pradakshina → Visarjana.',
      significance: 'Also performed daily as the opening of any elaborate ceremony — including weddings, house-warmings, and yajnas. Ganesh Chaturthi festival (10 days) is the largest Ganesha pooja in India.'
    },
    {
      id: 'lakshmi-puja', name: 'Lakshmi Pooja', dev: 'लक्ष्मी पूजा',
      color: 'from-pink-400 to-yellow-500',
      deity: 'Lakshmi (with Ganesha & Saraswati usually)',
      when: 'Diwali night (Amavasya of Kartika), every Friday, at business openings, on Akshaya Tritiya.',
      purpose: 'Invocation of prosperity, abundance, and the flow of wealth aligned with dharma. Includes the account books (chopda) of businesses being blessed.',
      essentials: 'Silver coins, lotus flowers, kamal-gatta mala, gold ornaments (placed before her), rice (akshata), red cloth, kheer (rice pudding), gold-embroidered idol.',
      mantras: ['Om Shreem Mahalakshmyai Namaha', 'Sri Suktam (Rig Veda hymn) — 15 verses'],
      steps: 'Room cleaned and decorated with rangoli → Lakshmi & Ganesha placed together → 16 upacharas → Sri Suktam recitation → gold-coin abhisheka → aarti with Om Jai Lakshmi Mata → household ledgers touched to the deity → all-night lamp lit at the door to welcome Lakshmi in.',
      significance: 'On Diwali, 900 million households across India perform this simultaneously — the largest coordinated religious ritual on Earth.'
    },
    {
      id: 'shiva-abhisheka', name: 'Rudrabhisheka', dev: 'रुद्राभिषेक',
      color: 'from-slate-300 to-blue-600',
      deity: 'Shiva (as the Shiva Lingam)',
      when: 'Mondays, Pradosham (13th tithi), Shivaratri (Feb-Mar), Sawan (July-August month).',
      purpose: 'Cools the ferocious form of Rudra and invokes his benevolent aspect. Removes karma, planetary afflictions, and grants moksha.',
      essentials: 'Shiva Lingam (or its image), copper kalasha, Ganga water, milk, curd, ghee, honey, sugar, coconut water, sandalwood water, panchamrita, bilva leaves, dhattura, bhang, ash (vibhuti).',
      mantras: ['Om Namah Shivaya (5-syllabled mantra)', 'Rudram Chamakam (Yajur Veda — the entire Sri Rudra recitation, 11 sections of Namakam + 11 of Chamakam)', 'Mahamrityunjaya Mantra'],
      steps: 'Panchagavya + bilva purification → Rudram recitation → continuous abhisheka pouring 11 or 108 substances → each substance has its own mantra → bilva archana (1008 leaves) → vibhuti offering → aarti with camphor.',
      significance: 'The full Rudrabhisheka with all 11 Rudram + Chamakam recitations takes 6-8 hours. Considered one of the most powerful poojas in the Hindu tradition. Performed at Somnath, Kedarnath, and every Jyotirlinga.'
    },
    {
      id: 'satyanarayana', name: 'Satyanarayana Vrata', dev: 'सत्यनारायण व्रत',
      color: 'from-blue-500 to-yellow-500',
      deity: 'Vishnu as Satyanarayana',
      when: 'Any Purnima (full moon), Ekadashi, after fulfillment of a wish, house-warming, weddings, promotions.',
      purpose: 'Fulfilling a promise made in gratitude — "If X happens, I will perform this pooja." Also for general well-being of family. Called a vrata because it involves a fast + specific procedure.',
      essentials: 'Sapatapadi (7-food) prasada, banana leaves, sugar, wheat flour, ghee, milk — the sacred prasada called sapaatha is made from these. Also: yellow cloth, tulsi, coconut.',
      mantras: ['Om Namo Bhagavate Vasudevaya', 'Vishnu Sahasranama (recommended)'],
      steps: 'Kalash sthapana → Satyanarayana avahana → 16 upacharas → reading of the 5 kathas (stories) of the Satyanarayana Purana → sapaatha prasada offering → aarti → distribution to community.',
      significance: 'One of the most commonly performed poojas in Indian households — accessible, inexpensive, deeply auspicious. The stories illustrate that skipping the pooja after making a vow brings suffering.'
    },
    {
      id: 'navagraha', name: 'Navagraha Shanti Pooja', dev: 'नवग्रह शान्ति पूजा',
      color: 'from-purple-400 to-indigo-600',
      deity: 'The Nine Planets — Surya, Chandra, Mangala, Budha, Guru, Shukra, Shani, Rahu, Ketu',
      when: 'When jyotisha (Vedic astrology) reveals malefic planetary phase — Sade Sati (Saturn), Rahu Kaal, Ketu Dasha, marriage delay, career blocks.',
      purpose: 'Pacification of malefic planetary influences and strengthening of beneficial ones. Balances the horoscopic karma.',
      essentials: 'Nine grains (each planet has its own), nine cloths in nine colors, nine flowers, nine metal images of the planets, offerings specific to each: ruby for Sun, pearl for Moon, red coral for Mars, emerald for Mercury, yellow sapphire for Jupiter, diamond for Venus, blue sapphire for Saturn, hessonite for Rahu, cat\'s eye for Ketu.',
      mantras: ['Individual bija mantras for each graha', 'Navagraha stotra'],
      steps: 'Sankalpa specifying afflicting planet → nine kalashas established in nine directions → each planet worshipped separately with its color, grain, and mantra → homa in each planet\'s direction → aarti.',
      significance: 'Often performed at Navagraha temples in Tamil Nadu (like the nine temples of the Kumbakonam region — each dedicated to one planet). A full Navagraha Shanti can take 4-6 hours.'
    },
    {
      id: 'chandi-homa', name: 'Chandi Homa', dev: 'चण्डी होम',
      color: 'from-red-500 to-fuchsia-700',
      deity: 'Chandi / Durga (the Devi Mahatmya form)',
      when: 'Navaratri (twice yearly), on personal crises, at times of protection needed, at large temples on ashtami/navami.',
      purpose: 'Invokes the fierce Mother Durga for protection from enemies (internal and external), removal of black magic, healing of chronic illness, and destruction of adharmic obstacles.',
      essentials: 'Fire altar (kunda), 108 or 1008 lotus flowers, red cloth, red hibiscus, chandi patha (700 verses of Devi Mahatmya), ghee for offering, samagri (herbs for fire).',
      mantras: ['Sapta-shati (700 verses of Devi Mahatmya)', 'Om Aim Hrim Klim Chamundaye Vichche', 'Argala Stotra, Kilaka Stotra, Kavacham (protective triplet before reading)'],
      steps: 'Kalash sthapana with Devi avahana → recitation of the 700 verses (takes 4-5 hours) → offering of every 108th verse into the fire → 1000 lotus offering → purnahuti (final full oblation) → aarti.',
      significance: 'The Chandi Homa on Ashtami/Navami of Navaratri is one of the most cathartic ceremonies in Hinduism. In Kerala, entire temples perform 108 Chandi Homas simultaneously (Ati-rudra Yagna scale).'
    },
    {
      id: 'ayush-homa', name: 'Ayush Homa', dev: 'आयुष्य होम',
      color: 'from-emerald-400 to-yellow-500',
      deity: 'Ayush (personified life-force) & Mrityunjaya (Shiva as conqueror of death)',
      when: 'On the day of birthday (specifically the nakshatra return, called nakshatra-janma), before major surgery, at 60/70/80/90/100 year celebrations (Shashtiabdapoorti, Sahasrachandra darsana etc.).',
      purpose: 'Long life, freedom from disease, longevity of a loved one. Considered essential on major birthdays.',
      essentials: 'Ghee, durva grass, milk-rice (payasam), 100 fresh sprigs, health-related samagri (medicinal herbs).',
      mantras: ['Mahamrityunjaya Mantra (Om Tryambakam Yajamahe Sugandhim Pushtivardhanam / Urvarukamiva Bandhanan Mrityor Mukshiya Mamritat) — 108 or 1008 times', 'Ayushya Suktam'],
      steps: 'Ganesha pooja → kalash sthapana → the birthday person seated facing east → Mahamrityunjaya Homa: each of 108/1008 mantras concludes with an offering of ghee → conclusion with panchamrita → the elder blesses with rice (akshata).',
      significance: 'Considered the highest gift to give a family member — often performed by children for aging parents. The 60th birthday Ayush Homa (Shashtiabdapoorti) is celebrated across South India as a major life event.'
    },
    {
      id: 'griha-pravesha', name: 'Griha Pravesha', dev: 'गृह प्रवेश',
      color: 'from-amber-400 to-emerald-600',
      deity: 'Vastu Purusha, Ganesha, Lakshmi, Kula devata (family deity)',
      when: 'On entering a new home for the first time — must be within an auspicious muhurta.',
      purpose: 'Purification of the new dwelling, invocation of positive energies, and blessing of every direction of the house. Placement of Vastu Purusha correctly ensures wealth, health, and harmony.',
      essentials: 'Kalasha with coconut, mango leaves, milk, decorated with turmeric-thread, rangoli at the threshold, holy water from a temple/river.',
      mantras: ['Vastu Purusha stotram', 'Ganesha atharva shirsha', 'Sri Suktam'],
      steps: 'Coconut broken at the threshold → cow enters first (in traditional versions) or a kalasha carried on the head by the wife → boiling of milk on the new stove (allowed to overflow — symbol of abundance) → Vastu Homa in the northeast → aarti in each direction → community feast.',
      significance: 'The "boiling milk" ritual is universally observed — the overflow is considered a direct blessing of Lakshmi. New homes should not be inhabited before this ceremony.'
    },
    {
      id: 'sudarshana-homa', name: 'Sudarshana Homa', dev: 'सुदर्शन होम',
      color: 'from-orange-500 to-red-600',
      deity: 'Sudarshana Chakra of Vishnu (personified as a deity)',
      when: 'When facing enemies, curses, litigation, chronic illness, or negative influences.',
      purpose: 'Cutting away negativity, breaking curses, defeating enemies (internal or external), protection during dangerous times.',
      essentials: 'Fire altar in shape of a chakra, red cloth, tulsi, ghee, tila (sesame), rakta chandana (red sandalwood), Sudarshan yantra.',
      mantras: ['Om Sahasrara Hum Phat', 'Sudarshana Kavacham (108 or 1008 verses)'],
      steps: 'Sudarshan yantra installed → invocation of the deity → intense homa with 108 to 100,000 offerings — each accompanied by "Hum Phat" (the piercing mantra) → purnahuti → final aarti.',
      significance: 'Performed at Melmaruvathur, Simhachalam, and other temples where negativity is felt strongly. Believed to break even the most stubborn spiritual attacks.'
    },
    {
      id: 'kalasarpa-shanti', name: 'Kaal Sarpa Dosha Shanti', dev: 'कालसर्प शान्ति',
      color: 'from-slate-500 to-purple-700',
      deity: 'Rahu, Ketu, and the eight great serpent kings (Ashta Naga)',
      when: 'If the birth chart has Kaal Sarpa Dosha — all seven planets between Rahu and Ketu — a serious karmic pattern.',
      purpose: 'Pacification of ancestral serpent-related karma. Reversal of the "poison" of the horoscope.',
      essentials: 'Silver serpent images (108), Naga stotra, white flowers, milk, saffron, incense.',
      mantras: ['Ashta Naga Stotra', 'Rahu-Ketu bija mantras', 'Naga Gayatri'],
      steps: 'Performed only at specific kshetras — Trimbakeshwar (Nashik), Kalahasti (Andhra Pradesh), Kukke Subramanya (Karnataka). Rare and elaborate. Involves feeding snakes (symbolic or ritual).',
      significance: 'Believed to cleanse multi-life karma related to the serpent kingdom. Performed once in a lifetime, ideally.'
    },
    {
      id: 'shraddha', name: 'Shraddha', dev: 'श्राद्ध',
      color: 'from-slate-400 to-blue-600',
      deity: 'Ancestors (Pitri Devatas) & Yama',
      when: 'On the death anniversary (tithi) of an ancestor, during Pitru Paksha (16 days in Sep-Oct), on the new moon of every month (Amavasya Tarpanam).',
      purpose: 'Discharge the Pitri Rina (debt to ancestors). Feed and honor the departed, help them move forward in their journey.',
      essentials: 'Black sesame (tila), water, rice balls (pinda), darbha grass, banana leaves, cooked food, ghee lamp.',
      mantras: ['Pitri Sukta', 'Tarpana mantras (individual for each ancestor)'],
      steps: 'Priest invited or performed by eldest son → tila-jala tarpana (sesame-water offering) → pinda daan (rice balls) → offering to crows (considered messengers of Yama) → feeding of brahmins → charity in the ancestor\'s name.',
      significance: 'The tradition holds: if shraddha is not performed, ancestors remain in a hungry, wandering state. Even non-religious households often observe this on the death anniversary. The 16 days of Pitru Paksha are dedicated to this alone.'
    },
    {
      id: 'kalasha-sthapana', name: 'Kalasha Sthapana', dev: 'कलश स्थापना',
      color: 'from-amber-400 to-yellow-600',
      deity: 'All the tirthas (holy waters), Varuna, and the deity of the ceremony',
      when: 'At the start of virtually every major pooja or yajna.',
      purpose: 'Establish a sacred container that holds the presence of all sacred waters and the invoked deity throughout the ritual.',
      essentials: 'Copper or clay pot, water, mango leaves (5 or 7), coconut, red thread (mauli), turmeric, kumkum, coins.',
      mantras: ['Kalasha invocation mantras', 'Punyaha Vachanam (declaration of auspicious day)'],
      steps: 'Base marked with rice → pot filled with water → mango leaves arranged around the mouth → coconut placed on top → thread wound around → gandha applied → invocation → the kalasha now IS the deity for the duration of the ritual.',
      significance: 'The most universal of all Hindu ritual elements — every pooja from a village shrine to a Tirumala temple begins with a kalasha. Modern archaeology has found kalashas dating to 3000 BCE in the Indus Valley.'
    },
  ],
};

export const AARTIS = {
  intro: "Aarti (आरती) is the offering of light — the concluding gesture of any pooja. A lit lamp or camphor flame is circled clockwise before the deity while a devotional song is sung, bells and cymbals accompany, and worshippers stand with folded hands. The light returns to the devotees at the end — they cup their hands over the flame, then touch their eyes and head, receiving the deity's blessing.",
  dev: 'आरती',
  color: 'from-yellow-400 to-orange-600',
  types: [
    { name: 'Deepa Aarti', dev: 'दीप आरती', desc: 'The most common — a lamp with 1, 3, 5, or 7 wicks lit in ghee. Odd numbers preferred.' },
    { name: 'Karpura Aarti', dev: 'कर्पूर आरती', desc: 'Camphor is lit on a metal plate — leaves no residue, symbolizing the ego that completely dissolves before the divine.' },
    { name: 'Panchapradipa Aarti', dev: 'पञ्चप्रदीप आरती', desc: 'A five-lamp aarti — one lamp for each element (earth, water, fire, air, ether). The complete offering.' },
    { name: 'Shanka Aarti', dev: 'शङ्ख आरती', desc: 'A conch full of water is offered along with the lamp — the waters of the primordial ocean.' },
    { name: 'Ghrita Aarti', dev: 'घृत आरती', desc: 'A ghee-only aarti — considered the purest. Used at Jyotirlingas.' },
  ],
  famous_aartis: [
    { name: 'Om Jai Jagdish Hare', deity: 'Vishnu / all deities', by: 'Pandit Shraddha Ram Phillauri (1870)', desc: 'The most universally sung aarti in Hinduism — heard in millions of households every evening.' },
    { name: 'Om Jai Lakshmi Mata', deity: 'Lakshmi', by: 'Traditional', desc: 'Sung during Diwali Lakshmi puja and every Friday.' },
    { name: 'Om Jai Shiv Omkara', deity: 'Shiva', by: 'Traditional', desc: 'Sung at Shiva temples and during Rudra Abhisheka.' },
    { name: 'Ganga Aarti', deity: 'Ganga Devi', by: 'Traditional', desc: 'Performed daily at Varanasi (Dashashwamedh Ghat), Rishikesh (Triveni Ghat), and Haridwar (Har Ki Pauri) — one of the most spectacular public rituals in India.' },
    { name: 'Bhoolokka Vaikuntam Sri Ranganatha Aarti', deity: 'Ranganatha (Vishnu)', by: 'Sri Vaishnava tradition', desc: 'Sung at Srirangam — considered the most elaborate reclining Vishnu temple.' },
  ],
  procedure: "The lamp is held in the right hand. Traditional pattern: 4 clockwise circles at the deity's feet, then 2 at the navel, then 3 at the face, then 7 full-body circles — 16 total. After the deity, the flame is offered to the priest/worshippers who touch it and then their eyes and head. The dish is passed around and everyone participates.",
  meaning: "Every aarti says the same thing without words: 'You are the light. I bring you a small light to acknowledge yours. May your light dispel all darkness in me.'",
};

export const PUJA_IMPLEMENTS = {
  intro: "The tools of Hindu worship — each with a specific function, symbolism, and history. Together they form a portable sacred technology that has traveled largely unchanged from Vedic times to today's home altar.",
  dev: 'पूजा सामग्री',
  color: 'from-emerald-400 to-cyan-500',
  items: [
    { name: 'Kalasha', dev: 'कलश', purpose: 'The sacred pot — copper or brass, filled with water, topped with mango leaves and a coconut. Represents Vishnu, the cosmic waters, and the invoked deity of the ceremony. Present at almost every pooja.' },
    { name: 'Panchapatra', dev: 'पञ्चपात्र', purpose: 'A small five-spouted vessel holding water for offerings (arghya, padya, achamana). Made of copper or silver. The devotee\'s personal ritual cup.' },
    { name: 'Uddharani', dev: 'उद्धरणी', purpose: 'A small spoon used to offer water from the panchapatra. Never touched by the fingers directly during ritual.' },
    { name: 'Deepa / Diya', dev: 'दीप', purpose: 'The oil lamp — usually brass or clay, with cotton wicks in ghee or sesame oil. One lamp = one deity present. Never blown out; extinguished with a flower or a hand-fan.' },
    { name: 'Ghanta', dev: 'घण्टा', purpose: 'The bell — struck at the beginning and end of aarti. Sound wave-form has been shown to briefly synchronize brain alpha activity. Also considered to purify the space.' },
    { name: 'Shankha', dev: 'शङ्ख', purpose: 'The conch — Panchajanya, Vishnu\'s conch. Blown at the start of major poojas. Its natural spiral is the golden ratio; its sound produces the OM waveform. Also holds water for abhisheka.' },
    { name: 'Aarti Plate (Thali)', dev: 'आरती थाली', purpose: 'A metal plate holding the lit lamp, flowers, kumkum, and rice for offering. Circled before the deity during aarti.' },
    { name: 'Dhoop-daani', dev: 'धूपदानी', purpose: 'The incense holder — burns dhoop (compressed incense) or agarbatti (stick incense) or ral/loban (raw resin on charcoal).' },
    { name: 'Kumkum / Sindoor', dev: 'कुङ्कुम', purpose: 'Red powder made from turmeric + slaked lime — worn on the forehead of the deity and the devotee. Symbolizes shakti (feminine energy) and the awakened ajna chakra.' },
    { name: 'Chandan', dev: 'चन्दन', purpose: 'Sandalwood paste — cooling, fragrant. Applied to the murti and the devotee\'s forehead. Vaishnavas apply a U or Y shape (urdhva-pundra); Shaivas apply three horizontal lines (tripundra).' },
    { name: 'Akshata', dev: 'अक्षत', purpose: 'Unbroken rice grains — often mixed with turmeric. Offered to the deity as a symbol of imperishable devotion. "Akshata" literally means "not broken".' },
    { name: 'Tulsi Mala', dev: 'तुलसी माला', purpose: 'A necklace of 108 beads made from the wood of the tulsi (holy basil) plant. Worn by Vaishnavas and used for japa. Tulsi is considered the plant-form of the goddess.' },
    { name: 'Rudraksha Mala', dev: 'रुद्राक्ष माला', purpose: 'A necklace of 108 rudraksha beads — the seed of the Elaeocarpus tree. Sacred to Shiva. Recent studies suggest wearing 108 rudraksha may stabilize heart rate variability.' },
    { name: 'Naivedya Plate', dev: 'नैवेद्य पात्र', purpose: 'A separate plate on which cooked food is offered. Never eaten from directly by the devotee before offering; becomes prasada after the offering.' },
    { name: 'Yantra', dev: 'यन्त्र', purpose: 'A geometric metal or paper diagram installed at the shrine — the visual "circuit board" of a deity. Sri Yantra, Sudarshan Yantra, and Vastu Yantra are the most common.' },
    { name: 'Vibhuti / Bhasma', dev: 'विभूति · भस्म', purpose: 'Sacred ash — from a homa fire, from cow dung, or from a specific sacred source. Worn as tripundra by Shaivas. Reminds the wearer: everything ends as ash.' },
    { name: 'Panchamrita', dev: 'पञ्चामृत', purpose: 'The five nectars: milk, curd, ghee, honey, and sugar. Used in abhisheka. After the bath, the mixture becomes prasada — considered one of the most auspicious offerings.' },
    { name: 'Camphor (Karpura)', dev: 'कर्पूर', purpose: 'White cubic camphor — lit at the end of aarti. Burns completely without residue. Symbolizes the ego surrendering fully — nothing remains.' },
  ],
};

export const HOMAS = {
  intro: "Homa (होम) — also called Havan or Yagna — is the fire ritual. Substances are offered into a consecrated fire while mantras invoke specific deities. Fire is considered the direct messenger (agni-doota) between humans and the divine. Each homa targets a specific outcome. Below are the ones commonly performed today beyond the general daily Agnihotra.",
  dev: 'होम',
  color: 'from-orange-500 to-red-700',
  types: [
    {
      name: 'Ganapati Homa', dev: 'गणपति होम',
      when: 'At the start of any major ritual, before new ventures.',
      purpose: 'Removal of obstacles. Always performed first.',
      offerings: 'Ghee, durva grass, modaka, jaggery, black sesame.',
      duration: '1-2 hours.',
      color: 'from-yellow-400 to-orange-600',
    },
    {
      name: 'Mrityunjaya Homa', dev: 'मृत्युञ्जय होम',
      when: 'Before surgery, in serious illness, on birthdays (especially milestone ones).',
      purpose: 'Longevity, healing, protection from untimely death.',
      offerings: 'Ghee, durva, medicinal herbs, milk-rice, 108 or 1008 Mahamrityunjaya offerings.',
      duration: '3-4 hours (108 mantras) up to 12 hours (1008 mantras).',
      color: 'from-slate-300 to-blue-600',
    },
    {
      name: 'Sudarshana Homa', dev: 'सुदर्शन होम',
      when: 'To break enemies, curses, and negative energies.',
      purpose: 'Protection, victory in litigation, cutting away black magic.',
      offerings: 'Red sesame, red flowers, ghee.',
      duration: '2-3 hours.',
      color: 'from-orange-500 to-red-700',
    },
    {
      name: 'Chandi Homa', dev: 'चण्डी होम',
      when: 'Navaratri, personal crises, protection from black magic.',
      purpose: 'Invocation of the fierce Divine Mother for maximum protection.',
      offerings: '1008 red lotus flowers, ghee, saptashati recitations at every 108th offering.',
      duration: '6-8 hours.',
      color: 'from-red-500 to-fuchsia-700',
    },
    {
      name: 'Ayushya Homa', dev: 'आयुष्य होम',
      when: 'Birthdays (nakshatra return), 60/70/80th year celebrations.',
      purpose: 'Long life, longevity of loved ones.',
      offerings: 'Ghee, durva, milk-rice, medicinal herbs.',
      duration: '3-4 hours.',
      color: 'from-emerald-400 to-yellow-500',
    },
    {
      name: 'Navagraha Homa', dev: 'नवग्रह होम',
      when: 'When planetary afflictions are indicated in the horoscope.',
      purpose: 'Pacification of planetary energies.',
      offerings: 'Nine grains, nine woods, nine colored offerings — each in a different direction.',
      duration: '4-5 hours.',
      color: 'from-purple-400 to-indigo-600',
    },
    {
      name: 'Rudra Homa', dev: 'रुद्र होम',
      when: 'Shivaratri, Sawan month, Mondays.',
      purpose: 'Cools the fierce form of Rudra. Grants moksha-inclined blessings.',
      offerings: 'Bilva leaves, ghee, milk, dhattura, bhang, black sesame.',
      duration: '4-6 hours (with full Rudram-Chamakam).',
      color: 'from-slate-300 to-blue-600',
    },
    {
      name: 'Ati-Rudra Yajna', dev: 'अतिरुद्र यज्ञ',
      when: 'Rare — large-scale community events (once in decades).',
      purpose: 'Universal peace, rain, national prosperity.',
      offerings: '14,641 recitations of the Rudram (11 x 11 x 11 x 11), 121 priests, massive fire altars.',
      duration: '11 days.',
      color: 'from-slate-300 to-blue-600',
    },
    {
      name: 'Somayajna', dev: 'सोमयज्ञ',
      when: 'Rare classical Vedic yajna performed by hereditary Srauti families.',
      purpose: 'Original Vedic ritual — invokes Indra, Vayu, and cosmic forces. Central offering: soma juice (identity of the plant still debated).',
      offerings: 'Soma juice, ghee, animal offerings historically (now symbolic).',
      duration: '5-12 days.',
      color: 'from-amber-400 to-yellow-600',
    },
  ],
  fire_structure: "The homa kunda (fire pit) is dug in specific geometric shapes for different purposes: square (universal), circular (Shakti), triangular (destruction of negativity), lotus-shaped (Lakshmi), star-shaped (protection). The pit is dug 1-3 feet deep and lined with sand. Fire is kindled with samidha (fire-wood, usually pipal, mango, or palasha) using mantras — never a match if traditional.",
  offering_mantra: "Every offering is punctuated by 'Swaha' (स्वाहा) — literally 'well-said' — the mantra that carries the offering to the deity through Agni. The devotee is instructed: with each Swaha, offer not just the substance but the ego attached to it.",
};

export const DAILY_RITUAL = {
  intro: "The Hindu day, at its most complete, is a continuous ritual. Below is the traditional daily routine (nitya karma) followed by the Brahmana householder — much of which is still practiced today across observant families.",
  dev: 'नित्य कर्म',
  color: 'from-amber-400 to-purple-600',
  schedule: [
    { time: 'Brahma Muhurta · 4:00-6:00 AM', name: 'Ushah Kala Snana', dev: 'उषा काल स्नान', desc: 'Wake before sunrise, view the palms (Karagre vasate Lakshmih shloka), sip water (achamana), bathe. Considered the most powerful window for meditation.' },
    { time: 'Sunrise · 6:00 AM', name: 'Pratah Sandhya', dev: 'प्रातः सन्ध्या', desc: 'The dawn Sandhya Vandana — a fixed 20-minute ritual including achamana, pranayama, Gayatri japa (108 times), Surya arghya (offering water to the sun), and meditation.' },
    { time: 'Morning · 7:00-9:00 AM', name: 'Nitya Puja', dev: 'नित्य पूजा', desc: 'Daily household worship — the family shrine gets a small pooja: lamp, incense, flower, mantra, aarti. 15-30 minutes.' },
    { time: 'Before Meals', name: 'Bhojana Vidhi', dev: 'भोजन विधि', desc: 'Sprinkle water around the plate (chit-shakti offering), offer five morsels (Pancha-Yajna) to Prana, Apana, Vyana, Samana, Udana — before eating. Grace before food.' },
    { time: 'Noon · 12:00 PM', name: 'Madhyahnika Sandhya', dev: 'माध्याह्निक सन्ध्या', desc: 'Noon Sandhya Vandana — briefer than dawn, with Surya arghya at midday.' },
    { time: 'Afternoon', name: 'Svadhyaya', dev: 'स्वाध्याय', desc: 'Study of scripture — Gita, Upanishads, Puranas — for at least 30 minutes.' },
    { time: 'Sunset · 6:00 PM', name: 'Sayam Sandhya', dev: 'सायं सन्ध्या', desc: 'Sunset Sandhya Vandana — the sun is thanked for the day. Deepam Karotu shloka lights the evening lamp.' },
    { time: 'Evening · 7:00-8:00 PM', name: 'Sayam Pooja', dev: 'सायं पूजा', desc: 'Evening household worship — usually a longer aarti, family gathered, children reciting shlokas.' },
    { time: 'Night · Before Sleep', name: 'Shayana Vidhi', dev: 'शयन विधि', desc: 'Chant Ram or Om, remember the day\'s actions honestly, forgive and ask forgiveness (kshama prarthana), sleep facing east or south.' },
  ],
  five_debts: "The householder is said to be born with five debts (Pancha Rina): to the sages (Rishi rina), to the ancestors (Pitri rina), to the gods (Deva rina), to fellow humans (Manushya rina), and to other beings (Bhuta rina). The five daily yajnas (Pancha Mahayajnas) discharge these debts: Brahma yajna (study), Pitri yajna (tarpana), Deva yajna (homa), Manushya yajna (hospitality), Bhuta yajna (feeding animals).",
};
