// Ancient Knowledge, Learning Paths, Daily Practices, Daily Challenges, Mysteries

export const ANCIENT_KNOWLEDGE = [
  {
    id: 'ayurveda',
    name: 'Ayurveda',
    subtitle: 'The 5,000-year-old science of life',
    color: 'from-emerald-400 to-teal-600',
    tagline: "India's traditional medicine, now studied by WHO and Ivy League labs.",
    overview: "Ayurveda ('science of life' in Sanskrit) is a comprehensive traditional health system originating in the Indian subcontinent around 3,000 BCE. Codified in the Charaka Samhita and Sushruta Samhita, it treats every person as a unique constitution (prakriti) rather than a template. The World Health Organization officially recognizes Ayurveda and India runs a Ministry of AYUSH dedicated to it. Modern research validates several of its herbs and practices, while others remain traditional wisdom awaiting proper study.",
    doshas: [
      { name: 'Vata', desc: 'Air + space. Governs movement, breath, nervous system. Imbalance: anxiety, dryness, insomnia.', color: 'from-slate-400 to-blue-500' },
      { name: 'Pitta', desc: 'Fire + water. Governs digestion, metabolism, intelligence. Imbalance: inflammation, anger, acidity.', color: 'from-orange-400 to-red-500' },
      { name: 'Kapha', desc: 'Earth + water. Governs structure, immunity, stability. Imbalance: sluggishness, weight gain, congestion.', color: 'from-emerald-400 to-teal-500' },
    ],
    pillars: [
      { name: 'Ahara (Food)', desc: 'Eat according to constitution, season, time of day. Warm cooked food; six tastes at each meal.' },
      { name: 'Nidra (Sleep)', desc: '10 PM to 6 AM. Sleep is the great restorer, more important than diet or exercise for most imbalances.' },
      { name: 'Brahmacharya (Vitality)', desc: 'Conserving vital energy through moderation in food, senses, and sexual expression.' },
      { name: 'Dinacharya (Daily routine)', desc: 'Rising before sunrise, tongue scraping, oil pulling, self-massage (abhyanga), pranayama, meditation.' },
    ],
    evidence: [
      'Turmeric (curcumin) has thousands of peer-reviewed studies on anti-inflammatory action.',
      'Ashwagandha shown to reduce cortisol and improve stress markers (multiple RCTs).',
      'Nasal irrigation (jala neti) is now standard ENT recommendation.',
      'Oil pulling reduces oral bacteria (small studies).',
      'Some claims (astrological timing of herbs, subtle-body theory) remain outside standard evidence.',
    ],
  },
  {
    id: 'yoga',
    name: 'Yoga',
    subtitle: "Patanjali's eight-limbed path",
    color: 'from-purple-400 to-fuchsia-600',
    tagline: 'Not stretching. A complete science of consciousness.',
    overview: "Yoga (from yuj — 'to unite') is far more than postures. The Yoga Sutras of Patanjali (c. 200 BCE - 200 CE) describe an eight-limbed path (ashtanga) leading from ethical foundations through breath and posture to the deepest states of meditation. Modern research on the physical limbs (asana, pranayama) is extensive; research on the deeper limbs is beginning.",
    limbs: [
      { n: 1, name: 'Yama', desc: 'Ethical restraints toward the world: non-violence, truth, non-stealing, moderation, non-hoarding.' },
      { n: 2, name: 'Niyama', desc: 'Ethical observances toward self: purity, contentment, discipline, self-study, surrender.' },
      { n: 3, name: 'Asana', desc: 'Steady, comfortable posture. Originally: a seat for meditation. Now popularly: the full physical practice.' },
      { n: 4, name: 'Pranayama', desc: 'Extension and regulation of life-force through breath. Powerful nervous system training.' },
      { n: 5, name: 'Pratyahara', desc: 'Withdrawing the senses from external objects; turning attention inward.' },
      { n: 6, name: 'Dharana', desc: 'One-pointed concentration on a single object.' },
      { n: 7, name: 'Dhyana', desc: 'Meditation \u2014 sustained flow of attention; the object begins to reveal itself.' },
      { n: 8, name: 'Samadhi', desc: 'Absorption. The observer and observed merge. The goal.' },
    ],
    branches: [
      { name: 'Jnana Yoga', desc: 'The path of wisdom \u2014 self-inquiry and discrimination.' },
      { name: 'Bhakti Yoga', desc: 'The path of devotion \u2014 love directed to the divine.' },
      { name: 'Karma Yoga', desc: 'The path of selfless action \u2014 work as offering.' },
      { name: 'Raja Yoga', desc: 'The royal path \u2014 meditation and mental discipline.' },
      { name: 'Hatha Yoga', desc: 'Balancing solar/lunar energies through body practices.' },
      { name: 'Kundalini Yoga', desc: 'Awakening dormant energy at the base of the spine.' },
      { name: 'Kriya Yoga', desc: 'Specific breath, mantra, and meditation techniques.' },
      { name: 'Tantra Yoga', desc: 'Embracing all of life as sacred (much wider than pop-culture usage).' },
    ],
    evidence: [
      'Yoga significantly reduces chronic low-back pain, stress, and depression (Cochrane reviews).',
      'Improves flexibility, balance, and strength across all age groups.',
      'Pranayama measurably improves HRV and lung function.',
      'Long-term practice associated with cortical thickening in areas linked to attention.',
    ],
  },
  {
    id: 'vastu',
    name: 'Vastu Shastra',
    subtitle: 'The ancient science of harmonious architecture',
    color: 'from-amber-400 to-orange-500',
    tagline: 'How the space you live in shapes your consciousness.',
    overview: "Vastu Shastra ('science of dwelling') is the traditional Indian system of architecture, first described in the Vedas and elaborated in texts like the Mayamatam and Manasara. It draws on five elements (earth, water, fire, air, space), the eight directions, cosmic geometry (the vastu-purusha mandala), and natural forces (sunlight, magnetism, air flow). Many principles have practical merit; some claims (planetary influence on rooms) remain traditional.",
    directions: [
      { dir: 'North', element: 'Water', use: 'Wealth, career; place office, safe, or study here.' },
      { dir: 'North-East', element: 'Water + Air', use: 'Sacred space, meditation, water sources. Most auspicious corner.' },
      { dir: 'East', element: 'Air', use: 'Sunlight entry; main entrance, dining, prayer.' },
      { dir: 'South-East', element: 'Fire', use: 'Kitchen (agni corner).' },
      { dir: 'South', element: 'Fire', use: 'Rest and storage; not for water or main entry.' },
      { dir: 'South-West', element: 'Earth', use: 'Master bedroom \u2014 heaviest, most stable corner.' },
      { dir: 'West', element: 'Earth', use: 'Dining, kids room; setting sun energy.' },
      { dir: 'North-West', element: 'Air', use: 'Guest room, storage; \u2018air\u2019 for movement.' },
    ],
    principles: [
      'Face the sunrise: main entrance ideally East or North.',
      'Center of home (Brahmasthan) should be clear \u2014 no heavy furniture, pillars, or bathrooms.',
      'Kitchen fire in South-East corner; cook facing East.',
      'Bedroom in South-West for stability of sleep and relationships.',
      'Water features in North-East (natural drainage direction on Indian subcontinent).',
      'Sleep with head to South (aligned with earth\u2019s magnetic field for restful sleep, per tradition).',
    ],
    evidence: [
      'Many principles overlap with sound climatic design for tropical latitudes.',
      'Circadian benefits of east-facing bedrooms are well-documented.',
      'Feng shui (China\u2019s parallel tradition) shows similar overlap with modern environmental psychology.',
      'Specific metaphysical claims (planetary rulership of directions) are traditional \u2014 not tested.',
    ],
  },
  {
    id: 'sanskrit',
    name: 'Sanskrit',
    subtitle: 'The perfected language',
    color: 'from-fuchsia-400 to-purple-500',
    tagline: 'A language engineered for precision \u2014 and possibly for computers.',
    overview: "Sanskrit (Samskrta \u2014 'refined, perfected') is one of the oldest documented languages, formalized by Panini's Ashtadhyayi (c. 500 BCE) in 3,959 sutras \u2014 the most complete grammar ever written for any language before the 20th century. NASA researcher Rick Briggs argued in 1985 that Sanskrit has the qualities of a natural artificial-intelligence programming language: unambiguous, generative from small root elements.",
    features: [
      { name: 'Root system (dhatu)', desc: '~2,000 verbal roots generate the entire vocabulary through systematic derivation.' },
      { name: 'Sandhi (euphonic combination)', desc: 'Precise rules for how sounds merge across word boundaries \u2014 crucial for correct chanting.' },
      { name: 'Free word order', desc: 'Case endings carry meaning, so word order is flexible for poetry and rhythm.' },
      { name: 'Sound as meaning', desc: 'Mantras are said to work through the vibration itself, not just the semantic content.' },
      { name: 'Recursion', desc: 'Panini\u2019s grammar uses recursive rules \u2014 essentially describing the language as a formal system.' },
    ],
    keyWords: [
      { word: 'Namaste', meaning: 'The divine in me bows to the divine in you.' },
      { word: 'Ahimsa', meaning: 'Non-harming \u2014 the first ethical rule of yoga.' },
      { word: 'Dharma', meaning: 'That which upholds; duty, purpose, natural law.' },
      { word: 'Karma', meaning: 'Action, and the seeds action plants.' },
      { word: 'Moksha', meaning: 'Liberation from the cycle of suffering.' },
      { word: 'Atman', meaning: 'The unchanging Self, distinct from the changing self.' },
      { word: 'Brahman', meaning: 'The ground of all being; the absolute.' },
      { word: 'Prana', meaning: 'Vital life-force, expressed most obviously through breath.' },
      { word: 'Guru', meaning: 'Dispeller of darkness; teacher.' },
      { word: 'Om', meaning: 'The primordial sound; the seed of all mantras.' },
    ],
  },
  {
    id: 'geometry',
    name: 'Sacred Geometry',
    subtitle: 'The universe speaks in shapes',
    color: 'from-cyan-400 to-blue-500',
    tagline: 'From DNA to galaxies to the Parthenon \u2014 the same patterns keep appearing.',
    overview: "Sacred geometry is the study of geometric patterns and ratios that recur across nature, sacred art, and cosmic structure. From the golden ratio in nautilus shells and sunflower seeds to the Sri Yantra and the Kaaba's dimensions, humans have long noticed that reality favors certain proportions.",
    patterns: [
      { name: 'Golden Ratio (Phi \u2248 1.618)', desc: 'Appears in nautilus shells, galaxies, human bodies, Parthenon, Vitruvian Man.' },
      { name: 'Flower of Life', desc: 'Overlapping circles forming a symmetrical pattern; found from Egypt to China.' },
      { name: 'Sri Yantra', desc: 'Nine interlocking triangles \u2014 the mother of all yantras; represents cosmos and consciousness.' },
      { name: 'Metatron\u2019s Cube', desc: 'Contains all five Platonic solids \u2014 the building blocks of matter (Plato\u2019s Timaeus).' },
      { name: 'Fibonacci Spiral', desc: 'Number sequence (1,1,2,3,5,8...) governing plant growth, hurricanes, and galaxies.' },
      { name: 'Vesica Piscis', desc: 'Intersection of two equal circles; the geometric basis of much sacred art.' },
      { name: 'Fractals', desc: 'Self-similar patterns at every scale \u2014 broccoli, lungs, coastlines, mystical mandalas.' },
    ],
    evidence: [
      'Golden ratio in art and nature is well-documented (though some claims are exaggerated).',
      'Fractals are mathematically real and pervasive (Mandelbrot).',
      'Platonic solids correspond to real crystal structures.',
      'Sacred geometric patterns have documented calming effects (mandala coloring studies).',
      'Metaphysical claims about energy from shapes remain traditional.',
    ],
  },
  {
    id: 'astrology',
    name: 'Jyotisha (Vedic Astrology)',
    subtitle: 'The science of time \u2014 or the art of pattern-reading',
    color: 'from-indigo-400 to-purple-600',
    tagline: 'A traditional belief system, presented honestly: not scientifically validated as predictive.',
    overview: "Jyotisha ('light-science') is the traditional Indian system of astrology, one of the six Vedangas (limbs of the Vedas). Unlike Western tropical astrology, it uses the sidereal zodiac tied to fixed stars. It divides life into planetary periods (dashas), analyzes birth charts (kundali), and prescribes remedial measures (mantras, gems, charity).",
    keyElements: [
      { name: 'Nine Grahas (planets)', desc: 'Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn, Rahu (N. lunar node), Ketu (S. lunar node).' },
      { name: '12 Rashis (signs)', desc: 'Similar to Western but sidereal; ~24 days offset from tropical.' },
      { name: '27 Nakshatras (lunar mansions)', desc: 'Finer division of the sky \u2014 each with its own deity, symbol, and psychological signature.' },
      { name: 'Dashas (planetary periods)', desc: 'Vimshottari system: each planet rules a specific number of years across your life.' },
      { name: 'Yogas (planetary combinations)', desc: 'Specific patterns considered auspicious or challenging.' },
    ],
    honest: "Modern scientific studies (e.g., the Shawn Carlson double-blind test in Nature, 1985) do NOT find astrological predictions to perform better than chance. However: (a) many people report astrological consultation as psychologically useful for reflection, (b) the Nakshatra system contains sophisticated psychology of temperament, and (c) astrology has been culturally central for millennia and deserves respectful study as a wisdom tradition, not as physics. Sanatana approach: present the tradition honestly, without overclaiming.",
  },
  {
    id: 'palmistry',
    name: 'Hasta Samudrika (Palmistry)',
    subtitle: 'Reading personality in the hand',
    color: 'from-pink-400 to-rose-500',
    tagline: 'A traditional practice \u2014 evidence for prediction is weak, but for personality-hint is intriguing.',
    overview: "Hasta samudrika shastra is the Indian tradition of reading the hand as a map of character and destiny. Every ancient culture has some form of palmistry \u2014 Chinese, Greek, Egyptian. Modern research: prints of the hand (dermatoglyphics) do carry real information (genetic disorders, temperament markers), but 'prediction of future events' has not been scientifically validated.",
    lines: [
      { name: 'Life Line', desc: 'Curves around the thumb. Traditionally: vitality, life-force, major changes. Modern: hand-use pattern.' },
      { name: 'Head Line', desc: 'Runs across the palm. Intellectual style \u2014 analytical if straight, creative if wavy.' },
      { name: 'Heart Line', desc: 'Runs beneath the fingers. Emotional style and relationships.' },
      { name: 'Fate Line', desc: 'Vertical line up the palm center. Career and life-direction; not everyone has one.' },
    ],
    honest: 'Take palmistry as a mirror for reflection, not a crystal ball. The best palmists are essentially skilled therapists reading body language.',
  },
  {
    id: 'temple-architecture',
    name: 'Temple Architecture',
    subtitle: 'Where cosmology becomes stone',
    color: 'from-amber-500 to-yellow-600',
    tagline: 'Every Hindu temple is a scale model of the universe.',
    overview: "Hindu temple architecture (Vastu Vidya + Shilpa Shastra) is a systematic translation of Vedic cosmology into stone. Every element has meaning: the tower (shikhara) is Mount Meru; the sanctum (garbhagriha, 'womb-house') is the darkness from which creation arose; circumambulation (pradakshina) is the sun's path.",
    parts: [
      { name: 'Garbhagriha', desc: 'The inner sanctum \u2014 dark, small, containing only the deity. The cosmic womb.' },
      { name: 'Shikhara / Vimana', desc: 'The tower rising above the sanctum \u2014 Mount Meru, the axis of the universe.' },
      { name: 'Mandapa', desc: 'Pillared hall for gathering \u2014 the manifest world where devotees stand.' },
      { name: 'Gopuram', desc: 'Monumental entrance tower (South Indian style) \u2014 the mountain-shaped gate to the sacred.' },
      { name: 'Pradakshina Patha', desc: 'The circumambulation path \u2014 walking around the sanctum aligns you with cosmic order.' },
      { name: 'Dhvaja', desc: 'The temple flag \u2014 flown to announce the deity is in residence.' },
      { name: 'Tank / Kalyani', desc: 'Sacred water reservoir \u2014 for ritual bathing before entry.' },
    ],
    styles: [
      { name: 'Nagara (North Indian)', desc: 'Beehive-shaped tower with curvilinear sides. Khajuraho, Bhubaneswar, Kedarnath.' },
      { name: 'Dravida (South Indian)', desc: 'Pyramidal storeys with prominent gopuram. Meenakshi, Brihadeeswarar, Tirupati.' },
      { name: 'Vesara', desc: 'Hybrid of Nagara and Dravida. Hoysala temples of Karnataka.' },
      { name: 'Kalinga (Eastern)', desc: 'Distinctive of Odisha. Jagannath Puri, Konark Sun Temple.' },
    ],
  },
];

export const LEARNING_PATHS = [
  {
    id: 'beginner',
    name: 'Beginner Path',
    subtitle: 'Zero experience, thirty days.',
    color: 'from-emerald-400 to-teal-600',
    duration: '4 weeks',
    weeks: [
      { title: 'Week 1: Ground yourself', items: [
        'Read: "Why meditate?" and "Why learn ancient wisdom?" on our Why page',
        'Practice: 5 minutes of breath meditation daily (Anapana)',
        'Journal: One line each night \u2014 what did I notice about my mind today?',
        'Optional: Listen to Om chanting once during the day',
      ]},
      { title: 'Week 2: Meet the traditions', items: [
        'Read: Bhagavad Gita summary (or Dhammapada) via our Books page',
        'Practice: 10 minutes breath meditation; add 3 min gratitude reflection',
        'Explore: One Life Question that speaks to you \u2014 read all four perspectives',
        'Reflect: Which tradition\'s language most resonates for you? Why?',
      ]},
      { title: 'Week 3: Body awareness', items: [
        'Read: Body + Spirit page \u2014 the anatomy of practice',
        'Practice: Body scan meditation (Vipassana) 15 minutes daily',
        'Add: 5 minutes of slow diaphragmatic breathing (4-6 breaths/min)',
        'Take: Chakra Balance test \u2014 note the weakest',
      ]},
      { title: 'Week 4: First ritual', items: [
        'Read: The 16-step Puja Vidhanam \u2014 not to perform yet, just understand',
        'Practice: A simple morning candle-lighting with 3 breaths and one intention',
        'Try: One 21-day gratitude journaling challenge',
        'Reflect: Journal for 10 min on what changed in you this month',
      ]},
    ],
  },
  {
    id: 'intermediate',
    name: 'Intermediate Path',
    subtitle: 'You have a practice \u2014 deepen it.',
    color: 'from-amber-400 to-orange-500',
    duration: '8 weeks',
    weeks: [
      { title: 'Week 1-2: Comparative depth', items: [
        'Study: Compare Religions across all six topics we cover',
        'Read: Yoga Sutras or Dhammapada in full (summary + one primary text)',
        'Practice: 20-minute daily sit \u2014 alternate breath and body scan',
      ]},
      { title: 'Week 3-4: Neuroscience of meditation', items: [
        'Read: Search key terms \u2014 default-mode network, HRV, vagal tone',
        'Practice: Metta (loving-kindness) meditation daily for two weeks',
        'Track: Note mood before/after each session',
      ]},
      { title: 'Week 5-6: Ethics and meaning', items: [
        'Study: Yamas and Niyamas \u2014 the ten ethical foundations of yoga',
        'Read: Life Questions on purpose, meaning, and change',
        'Practice: Add pranayama (Nadi Shodhana \u2014 alternate nostril) 10 min',
      ]},
      { title: 'Week 7-8: Devotion and inquiry', items: [
        'Choose one form of the sacred that moves you (deity, teacher, principle)',
        'Practice: 10 min mantra japa (with 108-bead mala if available)',
        'Ask (silently, before sleep): "Who am I?" \u2014 the Ramana Maharshi practice',
      ]},
    ],
  },
  {
    id: 'advanced',
    name: 'Advanced Path',
    subtitle: 'For serious seekers.',
    color: 'from-purple-500 to-fuchsia-600',
    duration: 'Ongoing',
    weeks: [
      { title: 'Foundation', items: [
        'Daily: 45-60 min meditation, minimum. Two sits (morning + evening) preferred.',
        'Weekly: A half-day of silence.',
        'Monthly: A full day off screens and speaking (mauna).',
      ]},
      { title: 'Study (choose depth over breadth)', items: [
        'Non-duality: Ashtavakra Gita, Ribhu Gita, Ramana Maharshi\'s "Talks"',
        'Buddhist path: Bhikkhu Bodhi\'s "In the Buddha\'s Words," Ajahn Chah',
        'Christian mystical: Meister Eckhart, The Cloud of Unknowing',
        'Sufi: Rumi\'s Masnavi, Ibn Arabi\'s "Bezels of Wisdom" (with commentary)',
      ]},
      { title: 'Practice', items: [
        'Formal deeksha from a qualified teacher in a lineage you trust',
        'Retreat: 10 days silent retreat at least once (Vipassana, Zen sesshin, or similar)',
        'Advanced pranayama only under a teacher (kumbhaka, kapalabhati at scale)',
        'Self-inquiry: "Who am I?" as continuous background attention',
      ]},
      { title: 'Warning signs', items: [
        'Spiritual bypassing: using practice to avoid unresolved psychology. See a therapist.',
        'Guru worship without discernment: healthy respect \u2260 loss of critical thinking.',
        'Ascetic extremism: the body is a temple, not an enemy.',
        'Comparing your inner experience with others\'. Do not.',
      ]},
    ],
  },
];

export const DAILY_PRACTICES = {
  intro: "The daily rhythm the traditions converge on. Not rigid \u2014 adapt to your life. Consistency of 15 minutes beats occasional heroics.",
  segments: [
    { time: 'Brahma Muhurta (4:30 - 6:00 AM)', color: 'from-indigo-500 to-purple-500',
      practices: [
        { name: 'Wake before sunrise', desc: 'Traditionally the most conducive time for meditation \u2014 sattvic (calm) energy dominates.' },
        { name: 'Cold water on face + tongue scraping', desc: 'Ayurvedic morning hygiene. Removes overnight ama (residue).' },
        { name: 'Drink warm water', desc: 'Kickstarts digestion; some add lemon or ginger.' },
      ]},
    { time: 'Morning (6:00 - 9:00 AM)', color: 'from-amber-400 to-orange-500',
      practices: [
        { name: 'Meditation (20-45 min)', desc: 'The most important practice \u2014 do it before anything else.' },
        { name: 'Pranayama (10-15 min)', desc: 'Nadi Shodhana or Bhramari for balance; Kapalabhati for energy (moderation).' },
        { name: 'Asana or light exercise', desc: 'Sun salutations (surya namaskar), walking, or a brief yoga sequence.' },
        { name: 'Reading (10-15 min)', desc: 'A page of scripture or wisdom text \u2014 read slowly, once.' },
        { name: 'Sankalpa', desc: 'One clear intention for the day, spoken silently.' },
      ]},
    { time: 'Afternoon (12:00 - 2:00 PM)', color: 'from-yellow-400 to-amber-500',
      practices: [
        { name: 'Main meal here', desc: 'Ayurveda: digestion is strongest when the sun is highest. Eat with attention.' },
        { name: '3 breaths before eating', desc: 'A moment of gratitude \u2014 for the food, the farmers, the sun, the rain.' },
        { name: 'Brief walk (10 min)', desc: 'Aids digestion; contact with nature resets the nervous system.' },
      ]},
    { time: 'Evening (5:30 - 7:00 PM)', color: 'from-orange-500 to-red-500',
      practices: [
        { name: 'Sandhya (twilight practice)', desc: 'The moment between day and night \u2014 traditionally a threshold time for meditation.' },
        { name: 'Aarti or lamp lighting', desc: 'A small ritual to mark the transition; family gathering point.' },
        { name: 'Light meal', desc: 'Sunset dinner ideal for digestion and sleep.' },
      ]},
    { time: 'Night (9:00 - 10:30 PM)', color: 'from-purple-500 to-indigo-500',
      practices: [
        { name: 'Journal (10 min)', desc: 'Three prompts: What did I do well? What did I miss? What am I grateful for?' },
        { name: 'Screens off', desc: 'At least 30 min before bed. Blue light and doomscrolling wreck sleep.' },
        { name: 'Yoga Nidra or breathing (10 min)', desc: 'Conscious deep-rest before natural sleep.' },
        { name: 'Sleep by 10 PM', desc: 'The 10 PM \u2013 2 AM window is when growth hormone peaks; sleep science confirms this rhythm.' },
      ]},
  ],
};

export const CHALLENGES = [
  {
    id: '7day',
    name: '7-Day Meditation Starter',
    duration: 7,
    color: 'from-emerald-400 to-teal-500',
    tagline: 'Zero to daily habit in one week.',
    days: [
      'Day 1: Sit 3 minutes. Just watch the breath at the nostrils.',
      'Day 2: Sit 5 minutes. Same practice. Notice the mind wandering.',
      'Day 3: Sit 7 minutes. Add: count breaths from 1 to 10 and start over.',
      'Day 4: Sit 10 minutes. Same. Do not judge \u2014 return gently.',
      'Day 5: Sit 10 minutes. Try naming feelings as they arise: "sadness", "excitement".',
      'Day 6: Sit 12 minutes. Then journal three lines about the sit.',
      'Day 7: Sit 15 minutes. You now have a habit. Continue at 15 min for a month.',
    ],
  },
  {
    id: '21day',
    name: '21-Day Gratitude',
    duration: 21,
    color: 'from-amber-400 to-yellow-500',
    tagline: 'Three weeks. One rewired brain.',
    days: [
      'Days 1-7: Each night, write 3 specific things you are grateful for today. Not "family" \u2014 "the way my daughter laughed at breakfast."',
      'Days 8-14: Each morning, before your feet touch the floor, name 3 things silently.',
      'Days 15-21: Once per day, tell one person exactly what you appreciate about them and why.',
      'The neuroscience: Gratitude practice measurably increases prefrontal activation and shifts default-mode negativity within 21 days (Emmons, Wood studies).',
    ],
  },
  {
    id: '30day',
    name: '30-Day Mindfulness',
    duration: 30,
    color: 'from-cyan-400 to-blue-500',
    tagline: 'Mindfulness beyond the cushion.',
    days: [
      'Week 1: Formal sit \u2014 15 min breath meditation daily.',
      'Week 2: Add "mindful eating" \u2014 first bite of every meal, chew 20 times, taste it fully.',
      'Week 3: Add "mindful transitions" \u2014 3 breaths between activities (before driving, before opening a door, before conversation).',
      'Week 4: Add "mindful listening" \u2014 for one week, in every conversation, listen without formulating a response.',
      'By day 30: mindfulness starts to happen without effort. This is the beginning.',
    ],
  },
  {
    id: '40day',
    name: '40-Day Discipline (Sadhana)',
    duration: 40,
    color: 'from-fuchsia-500 to-purple-600',
    tagline: 'The traditional length for lasting change.',
    days: [
      '40 days is the length used by yogic and Sikh traditions (chalisa), Christian Lent, Muslim Ramadan.',
      'Choose ONE practice. Just one. Same time, same duration, same place \u2014 40 days without skipping.',
      'Examples: 20 min meditation daily; 108-bead mantra japa; no complaining; no social media; walk one hour outside.',
      'Days 1-10: The novelty carries you.',
      'Days 11-25: Resistance peaks. This is where 90% quit. Do not.',
      'Days 26-40: The practice becomes part of you. Something shifts.',
      'On day 41: You have completed a sadhana. Traditionally, this is when transformation is said to become stable.',
    ],
  },
];

export const MYSTERIES = [
  {
    name: 'Puma Punku, Bolivia',
    color: 'from-amber-400 to-orange-500',
    facts: 'Andesite blocks up to 130 tons, cut with astonishing precision, dated to c. 500 CE. Interlocking H-shaped stones fit within millimeters.',
    hypotheses: 'Mainstream: skilled Tiwanaku stonemasons with sophisticated but conventional techniques. Speculation: much older civilization, or unusual technology now lost. Evidence favors the mainstream view but the precision remains striking.',
  },
  {
    name: 'Gobekli Tepe, Turkey',
    color: 'from-emerald-400 to-teal-500',
    facts: 'Massive stone-carved temple complex in southern Turkey, dated to c. 9,500 BCE \u2014 predating agriculture, cities, and pottery by thousands of years.',
    hypotheses: 'Rewrites the story of civilization: monumental religion may have preceded farming, not followed it. This is now the accepted view among archaeologists after multiple digs.',
  },
  {
    name: 'Nazca Lines, Peru',
    color: 'from-purple-400 to-fuchsia-500',
    facts: 'Enormous geoglyphs (up to 370m) on the Peruvian desert, made 500 BCE - 500 CE by the Nazca people. Only fully visible from the air.',
    hypotheses: 'Mainstream: astronomical calendar / religious pilgrim paths / water divination rituals. Erich von D\u00e4niken\'s ancient-astronaut claims are not taken seriously by archaeology. The mystery of the intended audience remains.',
  },
  {
    name: 'The Sphinx, Egypt',
    color: 'from-yellow-400 to-amber-500',
    facts: 'Weathering patterns on the Sphinx enclosure suggest possible water erosion, which would push the monument\'s date thousands of years earlier than the 2500 BCE mainstream dating.',
    hypotheses: 'Mainstream Egyptology: dated to Khafre\'s reign (c. 2500 BCE). Robert Schoch (geologist): erosion suggests 7000-9000 BCE, requiring an older civilization. This remains a genuine unresolved debate.',
  },
  {
    name: 'Voynich Manuscript',
    color: 'from-fuchsia-400 to-pink-500',
    facts: '240-page 15th-century book in an unknown script, illustrated with unfamiliar plants and astronomical diagrams. No one has decoded it in 600+ years.',
    hypotheses: 'Elaborate hoax? Encrypted natural-history compendium? Constructed language? A hoax is unlikely for the effort involved. Genuinely unsolved.',
  },
  {
    name: 'Near-Death Experiences',
    color: 'from-cyan-400 to-blue-500',
    facts: 'Consistent reports across cultures: tunnel of light, life review, meeting deceased relatives, deep peace. Occurring during clinical death (Parnia\'s AWARE studies).',
    hypotheses: 'Neuroscientific: dying-brain hallucinations, DMT release, neural cascade. Some cases include verified perceptions during flatline that remain unexplained. Research continues; the phenomenon is real, the interpretation is contested.',
  },
];
