// Deep content: Chakra Opening, Vedas + Body + Universe, more temples with villages

export const CHAKRA_OPENING = [
  { id: 'muladhara', name: 'Mūlādhāra', devanagari: 'मूलाधार', english: 'Root', bija: 'लं (Laṁ)', location: 'Base of spine, perineum',
    color: 'from-red-500 to-red-600', element: 'Earth', deity: 'Ganesha, Brahma', petals: 4, sense: 'Smell',
    when_closed: 'Anxiety about survival, chronic fear, financial worry, feeling homeless in body, digestive weakness.',
    when_open: 'Deep sense of belonging, stability under pressure, healthy relationship to money and body, ability to rest.',
    practices: [
      'Sit cross-legged with sit-bones firmly grounded. Feel the earth beneath.',
      'Bija mantra Laṁ (लं) — chant 108 times per day, feeling the vibration at the base of the spine.',
      'Mūla Bandha (root lock): gently contract the pelvic floor, hold for 5 breaths, release. 10 rounds.',
      'Walk barefoot on earth for 10+ minutes daily (grounding, evidence-supported for inflammation).',
      'Eat root vegetables (beets, carrots, sweet potato). Ayurveda: earth-heavy foods stabilize vata.',
      'Sleep with head to South (aligns with earth\'s magnetic field per tradition).',
      'Yoga: Malasana (garland pose), Tadasana (mountain), Balasana (child\'s pose).',
    ],
    science: 'Corresponds to the sacral plexus and coccygeal region. Grounding practices measurably reduce cortisol and inflammation markers (Chevalier et al., 2015).',
  },
  { id: 'svadhisthana', name: 'Svādhiṣṭhāna', devanagari: 'स्वाधिष्ठान', english: 'Sacral', bija: 'वं (Vaṁ)', location: 'Two fingers below navel',
    color: 'from-orange-400 to-orange-600', element: 'Water', deity: 'Vishnu, Rakini', petals: 6, sense: 'Taste',
    when_closed: 'Emotional numbness or overwhelm, creative block, sexual dysfunction, guilt around pleasure, hip/lower-back tightness.',
    when_open: 'Emotional fluidity, creative flow, healthy sensuality, joyful play, comfortable intimacy.',
    practices: [
      'Bija mantra Vaṁ (वं) — 108 repetitions, feel vibration in the pelvic bowl.',
      'Hip-opening yoga: Baddha Konasana, Sukhasana with forward fold, Anjaneyasana.',
      'Belly breathing: hand on lower belly, feel it rise 6 seconds in, fall 6 seconds out, for 10 minutes.',
      'Journaling: what do I feel — right now, in the body, not the mind? Twice a week.',
      'Water contact: swim, bathe with intention, drink water mindfully. Element resonance.',
      'Creative unblocking: sing badly, dance alone, sketch without judgment. Weekly.',
      'Ayurveda: sweet fruits (mango, coconut), warm oils for pelvic massage (abhyanga).',
    ],
    science: 'Corresponds to the sacral nerve plexus and reproductive-endocrine axis. Somatic therapy research (van der Kolk, Levine) shows pelvic-region tension holds unprocessed trauma.',
  },
  { id: 'manipura', name: 'Maṇipūra', devanagari: 'मणिपूर', english: 'Solar Plexus', bija: 'रं (Raṁ)', location: 'Just above navel',
    color: 'from-yellow-400 to-amber-500', element: 'Fire', deity: 'Rudra, Lakini', petals: 10, sense: 'Sight',
    when_closed: 'Low self-worth, indecision, chronic people-pleasing, poor digestion, low energy.',
    when_open: 'Clear will, healthy assertiveness, strong digestion, warm confidence without arrogance.',
    practices: [
      'Bija mantra Raṁ (रं) — 108 repetitions with clear intention.',
      'Kapalabhati (skull-shining breath): 30-60 rapid abdominal exhales, then 3 slow breaths. 3 rounds. NOT for pregnancy or heart conditions.',
      'Agni-sara: on empty stomach, exhale fully, then pump the belly in-out 30 times. 3 rounds.',
      'Sun salutation (Surya Namaskar) 12 rounds at sunrise.',
      'Speak one hard truth per day (kindly). Trains the will.',
      'Ayurveda: eat warming spices (ginger, black pepper, cumin, turmeric). Avoid overeating.',
      'Yoga: Navasana (boat), Dhanurasana (bow), Ardha Matsyendrasana (twist).',
    ],
    science: 'Corresponds to the celiac plexus — the "solar plexus" of Western anatomy — and the gut-brain axis. Fasting and breathwork measurably improve enteric nervous system function.',
  },
  { id: 'anahata', name: 'Anāhata', devanagari: 'अनाहत', english: 'Heart', bija: 'यं (Yaṁ)', location: 'Center of chest',
    color: 'from-emerald-400 to-green-500', element: 'Air', deity: 'Ishvara, Kakini', petals: 12, sense: 'Touch',
    when_closed: 'Loneliness even in company, chronic grief, resentment, difficulty giving or receiving love, chest tightness.',
    when_open: 'Unconditional warmth, forgiveness comes easy, deep listening, capacity to love without losing self.',
    practices: [
      'Bija mantra Yaṁ (यं) — 108 repetitions, hand on heart.',
      'Metta (loving-kindness) meditation daily. "May all beings be safe, happy, healthy, at ease."',
      'Chest-opening asana: Bhujangasana, Ustrasana, Setu Bandhasana — 5 breaths each.',
      'Bhastrika pranayama (bellows breath): 30 forceful equal in-out breaths, 3 rounds. Awakens the heart-lung field.',
      'Practice tonglen: on the in-breath, take in another\'s pain; on the out-breath, send them peace.',
      'Write and mail one letter of appreciation per week.',
      'Music that opens you: Bhajans, Sufi qawwali, Bach, Ludovico Einaudi. Feel it in the chest.',
    ],
    science: 'Corresponds to the cardiac plexus. The heart has ~40,000 neurons (the "little brain in the heart" — HeartMath research) and its electromagnetic field is measurable ~3 feet from the body.',
  },
  { id: 'vishuddha', name: 'Viśuddha', devanagari: 'विशुद्ध', english: 'Throat', bija: 'हं (Haṁ)', location: 'Throat, base of neck',
    color: 'from-sky-400 to-blue-500', element: 'Ether/Space', deity: 'Sadashiva, Shakini', petals: 16, sense: 'Hearing',
    when_closed: 'Habitual silence about important things, chronic throat tension or thyroid issues, difficulty finding words.',
    when_open: 'Clear speech, honest expression, deep listening, resonant voice, aligned communication.',
    practices: [
      'Bija mantra Haṁ (हं) — 108 repetitions.',
      'Chanting Om for 5-10 minutes daily. The final "mmm" vibrates the throat and skull.',
      'Bhramari (bee-breath): hum on the exhale for 5 rounds. Stimulates vagus nerve directly.',
      'Neck stretches: gentle side-to-side, ear-to-shoulder, chin tucks.',
      'Speak one thing you have been avoiding saying — this week. Honest, kind.',
      'Journal: what do I really think about ____ ? — no self-editing.',
      'Sing daily, even off-key. Kirtan (call-and-response chanting) is ideal.',
    ],
    science: 'Corresponds to the cervical plexus and thyroid gland. Vocal chanting stimulates the vagus nerve, measurably raising heart-rate variability (HRV) — a key marker of nervous-system health.',
  },
  { id: 'ajna', name: 'Ājñā', devanagari: 'आज्ञा', english: 'Third Eye', bija: 'ॐ (Om)', location: 'Between the eyebrows',
    color: 'from-indigo-400 to-purple-500', element: 'Light', deity: 'Paramashiva, Hakini', petals: 2, sense: 'Intuition',
    when_closed: 'Overthinking without insight, cynicism, doubt of intuition, headaches, sleep disturbance.',
    when_open: 'Sharp discernment, trustworthy intuition, clear dreams, penetrating insight, sense of inner guidance.',
    practices: [
      'Bija mantra Om (ॐ) — 108 repetitions with awareness at the point between the eyebrows.',
      'Trataka (candle-gazing): fixed gaze at a flame 2 feet away without blinking, then close eyes and watch the after-image. 10-15 min.',
      'Nadi Shodhana (alternate nostril breath): balances left and right hemispheres. 10-20 rounds.',
      'Yoga Nidra: 20-minute conscious deep-rest recording, once daily. Powerful for third eye.',
      'Study one Upanishad slowly — Isha, Kena, or Mandukya. One line per day.',
      'Reduce screens and information intake, especially at night. Ajna needs silence.',
      'Rest fingertip gently between eyebrows for 30 seconds daily to build proprioception.',
    ],
    science: 'Corresponds to the pineal gland, which regulates melatonin/circadian rhythm and may produce trace DMT during REM sleep and death (Strassman research). Long-term meditators show pineal calcification differences.',
  },
  { id: 'sahasrara', name: 'Sahasrāra', devanagari: 'सहस्रार', english: 'Crown', bija: 'Silence', location: 'Top of the head',
    color: 'from-violet-400 to-purple-600', element: 'Beyond elements', deity: 'Parabrahman', petals: 1000, sense: 'Beyond senses',
    when_closed: 'Materialism, loss of meaning, spiritual cynicism, sense of separation, existential emptiness.',
    when_open: 'Sense of unity beyond words, ordinary events glow with meaning, ego softens without disappearing, peace independent of circumstances.',
    practices: [
      'The bija is silence. Sit with no technique. Just be.',
      'Nirvichara meditation: whenever a thought arises, ask "To whom does this arise?" and rest in the awareness that notices.',
      'Study of the Mahavakyas (Great Utterances): Tat Tvam Asi, Aham Brahmasmi, Prajñānam Brahma, Ayam Atma Brahma.',
      'Devotional surrender: whatever your form of the divine, offer everything — sadness, joy, doubt — as it arises. Bhakti opens Sahasrara from a different angle than jnana.',
      'Extended silent retreats: at least one 10-day silent retreat in your life. Vipassana or Zen.',
      'Warning: opening Sahasrara without foundation in the lower six can be destabilizing. Progress through them all.',
      'The crown does not "open" through effort. It opens through the natural falling away of what obscured it.',
    ],
    science: 'Corresponds to the pituitary/hypothalamus and the cortical mantle. Deep meditation states show synchronized gamma waves across the cortex and near-total quieting of the default-mode network (Newberg, Davidson).',
  },
];

export const VEDIC_BODY_COSMOS = {
  intro: "The Vedas and Upanishads insist on a single equation: yat pinde tat brahmande — what is in the body is in the cosmos. The Purusha Sukta (Rig Veda 10.90) describes the universe as a cosmic body. The Chandogya Upanishad returns again and again to correspondences: the sun and the eye, the moon and the mind, breath and wind. Modern science, four thousand years later, is beginning to trace the same correspondences from the other direction.",
  correspondences: [
    { microcosm: 'Head', macrocosm: 'The heavens (Dyaus)', science: 'The brain\'s 86 billion neurons form roughly the same order-of-magnitude complexity as the number of stars in the Milky Way. Both are networks with hubs, edges, small-world properties.' },
    { microcosm: 'Eyes', macrocosm: 'The Sun', science: 'The eye responds to a narrow band of the same electromagnetic radiation the sun emits most abundantly. The Sun as "eye of the world" (Loka Chakshu) is Vedic; the eye as "little sun" is anatomically apt.' },
    { microcosm: 'Mind', macrocosm: 'The Moon', science: 'Menstrual cycles roughly synchronize with the lunar cycle. Sleep and mood show measurable lunar correlations. The mind\'s tides and the moon\'s tides share a governing rhythm.' },
    { microcosm: 'Breath (Prana)', macrocosm: 'The wind (Vayu)', science: 'Every breath you take was once wind. Every wind that circles the globe passes through lungs. The scale is not metaphor — it is anatomy.' },
    { microcosm: 'Body (Kaya)', macrocosm: 'The Earth', science: 'You are ~60% water, matching Earth\'s ocean coverage roughly. Your bones contain calcium forged in stars. The elements of the body are exactly the elements of the earth\'s crust.' },
    { microcosm: 'Blood', macrocosm: 'The rivers', science: 'Vedic hymns liken the seven great rivers to the vessels of the body. Blood distributes what the rivers distribute at planetary scale.' },
    { microcosm: 'Speech (Vak)', macrocosm: 'The primordial sound', science: 'From vibration, form emerges — both in cymatics experiments (sound organizing sand into patterns) and in the ancient claim that "in the beginning was the Word."' },
    { microcosm: 'Heart', macrocosm: 'The cave of Brahman', science: 'The heart is described in the Upanishads as "the cave" where the Self resides. Anatomically, the heart\'s ~40,000 neurons form a distinct nervous system — a real interior world.' },
  ],
  mahabharata_note: "The Mahabharata (Anushasana Parva, Bhishma\'s teachings) elaborates on this correspondence at length: each part of the human body is described as containing a devata (celestial principle). The war of Kurukshetra itself is read allegorically by Adi Shankaracharya as the war between the senses (Kauravas) and the discriminating intellect (Pandavas) fought on the chariot of the body, with Krishna (Self) as charioteer of the mind (Arjuna).",
  quotes: [
    { source: 'Rig Veda 10.90 (Purusha Sukta)', text: 'From his mind was born the moon; from his eye, the sun. From his mouth, Indra and Agni; from his breath, the wind was born.' },
    { source: 'Chandogya Upanishad 8.1', text: 'This little space within the heart is as great as this vast universe. The heavens and the earth are there, and the sun, and the moon, and the stars.' },
    { source: 'Yajur Veda 32.10', text: 'The one shining Being resides in the depths of all beings.' },
  ],
};

export const MORE_TEMPLES_V2 = [
  { name: 'Tanjore (Thanjavur)', country: 'India', region: 'Asia', tradition: 'Hinduism', lat: 10.78, lng: 79.13, image: 'https://images.unsplash.com/photo-1580881091335-4989b5cd39ac?auto=format&fit=crop&w=1200&q=80', note: 'Small town in Tamil Nadu (~220,000). Home of the Brihadeeswarar Temple, a UNESCO site whose 66m tower is topped by a single 80-tonne granite stone.' },
  { name: 'Hampi (Vijayanagara)', country: 'India', region: 'Asia', tradition: 'Hinduism', lat: 15.34, lng: 76.46, image: 'https://images.unsplash.com/photo-1620064916958-605375619af8?auto=format&fit=crop&w=1200&q=80', note: 'Ruined capital of the Vijayanagara Empire (14th-16th c.), tiny village today. Boulder-strewn UNESCO landscape with the Virupaksha Temple still active.' },
  { name: 'Sri Kalahasti', country: 'India', region: 'Asia', tradition: 'Hinduism', lat: 13.75, lng: 79.70, image: 'https://images.unsplash.com/photo-1587899297988-8be9c8a3d5d5?auto=format&fit=crop&w=1200&q=80', note: 'Small pilgrimage town in Andhra Pradesh. Vayu Lingam (air element) temple. Famous kalamkari (natural-dye textile) craft village.' },
  { name: 'Chidambaram', country: 'India', region: 'Asia', tradition: 'Hinduism', lat: 11.40, lng: 79.69, image: 'https://images.unsplash.com/photo-1587899297988-8be9c8a3d5d5?auto=format&fit=crop&w=1200&q=80', note: 'Small Tamil Nadu town. Nataraja Temple represents Akasha (space element). The Chidambara Rahasya (inner sanctum) contains only emptiness.' },
  { name: 'Mahabalipuram', country: 'India', region: 'Asia', tradition: 'Hinduism', lat: 12.62, lng: 80.19, image: 'https://images.unsplash.com/photo-1580881091335-4989b5cd39ac?auto=format&fit=crop&w=1200&q=80', note: 'Coastal Tamil town. Pallava-era rock-cut Shore Temple and Five Rathas (7th c.). Recent tsunami exposed submerged remains hinting at a lost port city.' },
  { name: 'Belur & Halebidu', country: 'India', region: 'Asia', tradition: 'Hinduism', lat: 13.16, lng: 75.86, image: 'https://images.unsplash.com/photo-1567610840009-eb27d64c9d59?auto=format&fit=crop&w=1200&q=80', note: 'Twin villages in Karnataka. Hoysala temples with 12th-century sculpture so detailed it required jeweler\'s tools. Every inch is carved.' },
  { name: 'Dwarka', country: 'India', region: 'Asia', tradition: 'Hinduism', lat: 22.24, lng: 68.97, image: 'https://images.unsplash.com/photo-1600100585499-df0d34cc4c47?auto=format&fit=crop&w=1200&q=80', note: 'Coastal town in Gujarat. Krishna\'s legendary city. Marine archaeology has found submerged structures dated 3,000+ years old off the coast.' },
  { name: 'Ayodhya', country: 'India', region: 'Asia', tradition: 'Hinduism', lat: 26.79, lng: 82.20, image: 'https://images.unsplash.com/photo-1592393991860-9d5cddca8daf?auto=format&fit=crop&w=1200&q=80', note: 'City in Uttar Pradesh on the Sarayu river. Birthplace of Rama in the Ramayana. New grand temple consecrated in 2024.' },
  { name: 'Mathura & Vrindavan', country: 'India', region: 'Asia', tradition: 'Hinduism', lat: 27.50, lng: 77.67, image: 'https://images.unsplash.com/photo-1601924572195-99e59f7be4b5?auto=format&fit=crop&w=1200&q=80', note: 'Twin towns in UP. Birthplace and childhood home of Krishna. Vrindavan\'s temples number in the thousands; the entire town is dedicated to bhakti.' },
  { name: 'Puri', country: 'India', region: 'Asia', tradition: 'Hinduism', lat: 19.80, lng: 85.82, image: 'https://images.unsplash.com/photo-1583405023459-2ce88c53bb27?auto=format&fit=crop&w=1200&q=80', note: 'Coastal town in Odisha. Jagannath Temple, one of Char Dham. Annual Rath Yatra draws 1M+ pilgrims. The flag atop the tower always defies the wind.' },
  { name: 'Rishikesh', country: 'India', region: 'Asia', tradition: 'Hinduism', lat: 30.09, lng: 78.27, image: 'https://images.unsplash.com/photo-1592393991860-9d5cddca8daf?auto=format&fit=crop&w=1200&q=80', note: 'Yoga capital of the world. Small holy town on the Ganga in Uttarakhand. Sivananda Ashram, Beatles Ashram (Maharishi), Parmarth Niketan.' },
  { name: 'Haridwar', country: 'India', region: 'Asia', tradition: 'Hinduism', lat: 29.95, lng: 78.16, image: 'https://images.unsplash.com/photo-1611128063014-7dd2a1e2b5b7?auto=format&fit=crop&w=1200&q=80', note: 'Where the Ganga leaves the Himalayas. Har Ki Pauri ghat hosts the daily Ganga Aarti. Kumbh Mela every 12 years draws tens of millions.' },
  { name: 'Ujjain', country: 'India', region: 'Asia', tradition: 'Hinduism', lat: 23.18, lng: 75.78, image: 'https://images.unsplash.com/photo-1580656949137-1f6d20f4d13b?auto=format&fit=crop&w=1200&q=80', note: 'Ancient city in MP. Home of Mahakaleshwar Jyotirlinga. The Tropic of Cancer passes through — was the prime meridian of Hindu astronomy.' },
  { name: 'Nashik & Trimbakeshwar', country: 'India', region: 'Asia', tradition: 'Hinduism', lat: 19.93, lng: 73.53, image: 'https://images.unsplash.com/photo-1611125832047-1d7ad1e08ef0?auto=format&fit=crop&w=1200&q=80', note: 'Maharashtra city + nearby village. Trimbakeshwar Jyotirlinga sits at the source of the Godavari. One of four Kumbh Mela sites.' },
  { name: 'Pashupatinath', country: 'Nepal', region: 'Asia', tradition: 'Hinduism', lat: 27.71, lng: 85.35, image: 'https://images.unsplash.com/photo-1580074309247-14ba53e57bdd?auto=format&fit=crop&w=1200&q=80', note: 'Kathmandu. One of the most sacred Shiva temples outside India. Cremation ghats along the Bagmati river.' },
  { name: 'Muktinath', country: 'Nepal', region: 'Asia', tradition: 'Hindu/Buddhist', lat: 28.82, lng: 83.87, image: 'https://images.unsplash.com/photo-1541661814024-ef4bab48ba0f?auto=format&fit=crop&w=1200&q=80', note: 'Tiny village at 3,800m in the Himalayas. Where Hindus, Buddhists, and even earlier Bon traditions meet. 108 water spouts.' },
  { name: 'Batu Caves', country: 'Malaysia', region: 'Asia', tradition: 'Hinduism', lat: 3.24, lng: 101.68, image: 'https://images.unsplash.com/photo-1563492065599-3520f775eeed?auto=format&fit=crop&w=1200&q=80', note: 'Suburb of Kuala Lumpur. 400 million-year-old limestone caves converted into Murugan temple. 43m gold statue at the entrance.' },
  { name: 'Prambanan', country: 'Indonesia', region: 'Asia', tradition: 'Hinduism', lat: -7.75, lng: 110.49, image: 'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?auto=format&fit=crop&w=1200&q=80', note: 'Central Java. 9th-century UNESCO Hindu temple complex with 47m Shiva shrine. Coexists with Buddhist Borobudur nearby.' },
  { name: 'My Son', country: 'Vietnam', region: 'Asia', tradition: 'Hinduism (Cham)', lat: 15.76, lng: 108.12, image: 'https://images.unsplash.com/photo-1573352763925-82bd5dfc31d1?auto=format&fit=crop&w=1200&q=80', note: 'Ruins in a Vietnamese valley. Cham civilization temples (4th-14th c.). Bombed in the Vietnam War, still recovering.' },
  { name: 'Konarka village', country: 'India', region: 'Asia', tradition: 'Hinduism', lat: 19.89, lng: 86.09, image: 'https://images.unsplash.com/photo-1580656949137-1f6d20f4d13b?auto=format&fit=crop&w=1200&q=80', note: 'Small village of ~1,700 people in Odisha, forever known for the Sun Temple. 24 stone wheels function as sundials accurate to the minute.' },
];
